from pathlib import Path
import re, json
R=Path(__file__).resolve().parent
js=(R/'v46_23_child_experience.js').read_text(encoding='utf-8')
idx=(R/'index.html').read_text(encoding='utf-8')
api=(R/'api_server.py').read_text(encoding='utf-8')
checks=[]
def ck(name,cond): checks.append((name,bool(cond)))
ck('version api 46.25', "APP_VERSION='46.25'" in api)
ck('server version 46.25', "server_version='PETQuest/46.25'" in api)
ck('script loaded', 'v46_23_child_experience.js?v=46.25' in idx)
ck('age 9 present', "?'9'" in js)
ck('age 10-12 present', "return'10-12'" in js)
ck('age 13-14 present', "?'13-14'" in js)
ck('learn stage', '1. APRENDER' in js)
ck('practice stage', '2. PRACTICAR' in js)
ck('master stage', '3. DOMINAR' in js)
ck('mock stage', '4. SIMULAR' in js)
ck('no entiendo prominent', '🤔 No entiendo' in js)
ck('manual break', 'Necesito una pausa' in js)
ck('break auto threshold', 'answersSinceBreak>=6' in js)
ck('mood ready', 'data-pq23-mood="ready"' in js)
ck('mood help', 'data-pq23-mood="stuck"' in js)
ck('mastery requires evidence', 'n>=5&&acc>=.8' in js)
ck('mastery not single lucky answer', 'una sola vez' in js)
ck('per user storage', "petquest_v4623_child_u_" in js and 'uid()' in js)
ck('server events', "apiRequest('/events'" in js)
ck('diagnostic integrated', 'PETQuestPracticeBank?.diagnosis' in js)
ck('10 item remediation integrated', 'startRemediation' in js)
ck('progress route', 'progressPct()' in js)
ck('daily micro goals', 'Meta de hoy' in js)
ck('retry after error', 'Este error ya se convirtió en una pista' in js)
ck('no peer competition', 'No compites con nadie' in js)
ck('writing help', "view==='writing'" in js)
ck('speaking help', "view==='speaking'" in js)
ck('practice help delegates Milo', "v14Show('understand')" in js)
ck('child experience global object', 'PETQuestChildExperience' in js)
ck('external validation boundary documented', 'external child-UX validation' in (R/'CHILD_LEARNING_EXPERIENCE_V46_23.md').read_text(encoding='utf-8'))
for name,ok in checks: print(('PASS' if ok else 'FAIL'),name)
print(f'{sum(ok for _,ok in checks)}/{len(checks)} PASS')
raise SystemExit(0 if all(ok for _,ok in checks) else 1)
