from pathlib import Path
R=Path(__file__).parent
js=(R/'v46_24_error_dna.js').read_text(encoding='utf-8')
pb=(R/'v46_22_practice_diagnostic.js').read_text(encoding='utf-8')
api=(R/'api_server.py').read_text(encoding='utf-8')
idx=(R/'index.html').read_text(encoding='utf-8')
sw=(R/'sw.js').read_text(encoding='utf-8')
checks=[]
def ck(n,v):checks.append((n,bool(v)));print(('PASS' if v else 'FAIL'),n)
ck('api endpoint',"p=='/api/error-dna'" in api)
ck('student scoped',"student_id=u['id']" in api and "school_id=? AND role='student'" in api)
ck('five domains',all(x in api for x in ["'Grammar'","'Listening'","'Reading'","'Writing'","'Speaking'"]))
for label in ['Past simple','Present perfect','Prepositions','Articles','Times','Numbers','Opinions','Corrected information','Spelling','Inference','Detail','Text cohesion','Organisation','Content','Language','Fluency','Pronunciation','Interaction']:
    ck('label '+label,label in api)
ck('minimum evidence 3',"if n<3: status='insufficient'" in api)
ck('red threshold',"elif score>=60: status='progress'" in api and "else: status='critical'" in api)
ck('green threshold',"if n<3" in api and "elif score>=80: status='mastered'" in api)
ck('three recent remediation mastery',"len(recent)>=3 and all(recent)" in api)
ck('pronunciation proxy warning','automatic_pronunciation_note' in api and 'proxy' in api.lower())
ck('ui loaded','v46_24_error_dna.js?v=46.27' in idx)
ck('sw cached','v46_24_error_dna.js?v=46.27' in sw)
ck('visual legend',all(x in js for x in ['🔴','🟠','🟢','⚪']))
ck('primary issue','Problema prioritario' in js)
ck('10 exercise CTA','Entrenar 10 ejercicios' in js and 'Crear plan de 10 ejercicios' in js)
ck('clickable nodes','data-dna-key' in js and 'openNode' in js)
ck('practice bridge','startMatrixRemediation' in js and 'startMatrixRemediation' in pb)
ck('practice save before render','S.remediation=' in pb and 'save();' in pb)
ck('server evidence sources',all(x in api for x in ['academic_error_events','academic_remediation_attempts','learning_events','speaking_attempts','snapshots']))
print(f'{sum(v for _,v in checks)}/{len(checks)} PASS')
raise SystemExit(0 if all(v for _,v in checks) else 1)
