from pathlib import Path
import json,re,sys
R=Path(__file__).resolve().parent
checks=[]
def ck(n,c,d=''):
    checks.append((n,bool(c),d)); print(('PASS' if c else 'FAIL'),n,d)
cur=json.loads((R/'PET_LEARN_CURRICULUM_V46_27.json').read_text())
js=(R/'v46_27_mastery_orchestrator.js').read_text()
idx=(R/'index.html').read_text(); api=(R/'api_server.py').read_text(); sw=(R/'sw.js').read_text()
ck('curriculum_100',cur.get('lesson_count')==100 and len(cur.get('items',[]))==100)
ck('learn_levels',cur.get('levels')==['A2','A2+','B1-','B1','B1+'])
ck('learn_unique_ids',len({x['id'] for x in cur['items']})==100)
ck('learn_four_skills',{'reading','listening','writing','speaking'}.issubset({x['skill'] for x in cur['items']}))
ck('learn_closed_loop',all(all(k in x for k in ['teach','examples','strategy','check','recheck','mastery']) for x in cur['items']))
ck('six_modules',all(x in js for x in ['1. PET Learn','2. PET Practice','3. PET Exam','4. PET Error DNA','5. PET AI Tutor','6. PET Readiness']))
ck('dashboard_readiness','PET Readiness:' in js and all(x in js for x in ['Reading','Listening','Writing','Speaking']))
ck('skill_score_visible_precision','function scoreLabel' in js and '${scoreLabel(s[k])}%' in js and 'Rendimiento actualizado' in js)
ck('dashboard_errors',all(x in js for x in ['Errores detectados','Corregidos','Pendientes','Reincidentes']))
ck('dashboard_exam_today',all(x in js for x in ['Examen','Hoy','today_minutes']))
ck('continue_button','CONTINUAR MI ENTRENAMIENTO' in js and 'continueTraining' in js)
ck('four_goals',all(x in js for x in ['Solo aprobar','B1 solido','Excelente resultado','Intentar rendimiento B2']))
ck('first_goal_prompt','firstGoalPrompt' in js and 'Elige tu objetivo' in js)
ck('b2_bridge_gate','b2BridgeStatus' in js and 'B2 bridge: 10+ ejercicios y >=80%' in js)
ck('excellent_targets',"reading:85,listening:85,writing:80,speaking:80" in js)
ck('writing_16_20','16/20' in js)
ck('speaking_4_5','4/5' in js and 'latestSpeakingConsistency' in js)
ck('mastery_gate','PET Quest no te promovera automaticamente' in js and 'goalStatus().ok' in js)
ck('probability_gated','probability_enabled' in js and 'Probabilidad estimada:' in js and 'OFF' in js)
ck('error_dna_route','/error-dna' in js and 'startMatrixRemediation' in js)
ck('practice_route','PETQuestPracticeBank' in js and 'adaptive=true' in js)
ck('exam_route',"state.view='mock'" in js)
ck('goal_persisted','masteryGoal' in js and 'persistProfile()' in js)
ck('exam_date_persisted','examDate' in js and 'persistProfile()' in js)
ck('per_user_local','_u_' in js and 'uid()' in js)
ck('backend_today_minutes','today_minutes' in api and "date(created_at)=date('now')" in api)
ck('backend_recurrent','recurrent_targets' in api and "'recurrent':recurrent_targets" in api)
ck('backend_goal_echo','learner_target' in api and 'mastery_goal' in api and 'exam_date' in api)
ck('version_backend',"APP_VERSION='46.27'" in api and "PETQuest/46.27" in api)
ck('script_loaded','v46_27_mastery_orchestrator.js?v=46.27' in idx)
ck('curriculum_cached','PET_LEARN_CURRICULUM_V46_27.json' in sw and 'petquest-v46-27' in sw)
passed=sum(x[1] for x in checks)
print('RESULT',passed,'/',len(checks),'PASS')
sys.exit(0 if passed==len(checks) else 1)
