from pathlib import Path
import json,re,sys
R=Path(__file__).parent; d=json.loads((R/'PRACTICE_BANK_V46_21.json').read_text())
req=['skill','part','cefr','difficulty','grammar','vocabulary','cognitive_skill','distractor_type','accent','audio_speed','target','estimated_time']
checks=[]
def C(n,x): checks.append((n,bool(x)))
items=d['items']; C('total_5000',len(items)==5000); C('unique_ids',len({x['id'] for x in items})==5000); C('unique_prompts',len({x['prompt'] for x in items})==5000); C('matrix_5000_5000',all(all(k in x and x[k] not in (None,'') for k in req) for x in items)); C('difficulty_numeric',all(isinstance(x['difficulty'],(int,float)) and 0<=x['difficulty']<=1 for x in items)); C('levels_6',set(x['cefr'] for x in items)==set(d['levels']) and len(d['levels'])==6); C('competencies_13',set(x['competency'] for x in items)==set(d['competencies']) and len(d['competencies'])==13); C('answer_valid',all(0<=x['answer']<len(x['options']) for x in items)); C('explanations',all(len(x['explanation'])>=15 for x in items)); C('skill_valid',all(x['skill'] in {'reading','writing','listening','speaking'} for x in items)); C('part_valid',all(1<=x['part']<=({'reading':6,'listening':4,'writing':2,'speaking':4}[x['skill']]) for x in items)); C('listening_metadata',all(x['accent']!='n/a' and x['audio_speed']!='n/a' for x in items if x['skill']=='listening')); js=(R/'v46_21_practice_bank.js').read_text(); C('adaptive_mode','🎯 Adaptativo' in js and 'weakness()' in js); C('backend_tracking',"practice_bank_answer" in js and "difficulty:q.difficulty" in js); C('matrix_visible','Matriz diagnóstica del ítem' in js); C('matrix_weakness_engine','matrixWeak()' in js and 'Qué está fallando' in js and 'cognitive_skill' in js); C('version_api',"APP_VERSION='46.27'" in (R/'api_server.py').read_text()); C('index_module','v46_22_practice_diagnostic.js?v=46.27' in (R/'index.html').read_text() and 'v46_23_child_experience.js?v=46.27' in (R/'index.html').read_text());
for n,v in checks: print(('PASS' if v else 'FAIL'),n)
print(f'{sum(v for _,v in checks)}/{len(checks)} PASS');sys.exit(0 if all(v for _,v in checks) else 1)
