// PET Quest V12 — age-adaptive UX, contextual scenes, badges, avatar accessories and guided sessions.
const V12_STORE='petQuestV12Ux';
const V12_DEFAULT={ageBand:'10-12',accessory:'none',badges:[],stickers:0,onboardingDone:false,focusMode:true,lastBadgeCheck:''};
let V12=(()=>{try{return {...V12_DEFAULT,...JSON.parse(localStorage.getItem(V12_STORE)||'{}')}}catch{return {...V12_DEFAULT}}})();
const V12_AGES={
 '7-9':{label:'9 años',tone:'short',helper:'Te lo explico con frases cortitas.',goal:'Una misión pequeña es suficiente.'},
 '10-12':{label:'10–12 años',tone:'balanced',helper:'Te guío paso a paso y tú decides.',goal:'Practica un poco cada día.'},
 '13+':{label:'13–14 años',tone:'independent',helper:'Menos ayuda, más autonomía.',goal:'Entrena como preparación real PET.'}
};
const V12_ACCESSORIES={none:['','Sin accesorio'],cap:['🧢','Gorra'],glasses:['🤓','Lentes'],crown:['👑','Corona'],headphones:['🎧','Audífonos']};
const V12_BADGES=[
 {id:'first-star',icon:'⭐',name:'Primera estrella',desc:'Consigue tu primera respuesta correcta',ok:()=>V11.stars>=1},
 {id:'three-stars',icon:'🌟',name:'Triple brillo',desc:'Consigue 3 estrellas',ok:()=>V11.stars>=3},
 {id:'reader',icon:'📚',name:'Explorador de historias',desc:'Completa 5 respuestas de Reading',ok:()=>data.history.filter(x=>x.skill==='reading').length>=5},
 {id:'listener',icon:'🎧',name:'Oído atento',desc:'Completa 5 respuestas de Listening',ok:()=>data.history.filter(x=>x.skill==='listening').length>=5},
 {id:'writer',icon:'✍️',name:'Creador de ideas',desc:'Completa tu primer Writing',ok:()=>data.writing.length>=1},
 {id:'speaker',icon:'🎙️',name:'Voz valiente',desc:'Practica Speaking',ok:()=>data.speaking.length>=1},
 {id:'repair',icon:'🧠',name:'Error detective',desc:'Vuelve a trabajar un error',ok:()=>data.history.filter(x=>!x.correct).length>=3},
 {id:'mock',icon:'🏰',name:'Valiente PET',desc:'Completa un Mock',ok:()=>data.mockAttempts.length>=1}
];
function v12Save(){localStorage.setItem(V12_STORE,JSON.stringify(V12))}
function v12Age(){return V12_AGES[V12.ageBand]||V12_AGES['10-12']}
function v12Kid(){return typeof uxMode==='function'&&uxMode()==='kid'&&!(typeof data!=='undefined'&&data.profile?.examProfile==='adult')}
function v12Accessory(){return V12_ACCESSORIES[V12.accessory]||V12_ACCESSORIES.none}
function v12AvatarDisplay(){const base=v11Avatar();return `${base[0]}${v12Accessory()[0]}`}
function v12Scene(skill){return `assets/scene_${skill||'reading'}.svg`}
function v12UnlockBadges(){let got=[];V12_BADGES.forEach(b=>{if(b.ok()&&!V12.badges.includes(b.id)){V12.badges.push(b.id);V12.stickers+=1;got.push(b)}});if(got.length){v12Save();requestAnimationFrame(()=>v12BadgeToast(got[0]))}}
function v12BadgeToast(b){if(document.querySelector('.v12-badge-toast'))return;const el=document.createElement('div');el.className='v12-badge-toast';el.innerHTML=`<div>${b.icon}</div><b>¡Nueva insignia!</b><span>${b.name}</span>`;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
function v12AgeModal(force=false){if(document.querySelector('.v12-modal'))return;if(V12.onboardingDone&&!force)return;document.body.insertAdjacentHTML('beforeend',`<div class="v12-modal" role="dialog" aria-modal="true"><div class="v12-modal-card"><div class="v12-modal-hero"><img src="assets/scene_home.svg" alt="Aventura PET Quest"><div><span class="mission-label">Personaliza tu aventura</span><h2>¿Para qué edad preparamos la guía?</h2><p>No cambia el nivel PET. Cambia cuánto te explicamos y cómo te acompañamos.</p></div></div><div class="v12-age-grid">${Object.entries(V12_AGES).map(([id,a])=>`<button data-v12-age="${id}" class="${V12.ageBand===id?'active':''}"><b>${a.label}</b><span>${a.helper}</span></button>`).join('')}</div><div class="row"><button class="btn btn-primary" data-v12-age-save>Guardar y continuar</button>${force?'<button class="btn btn-ghost" data-v12-close>Cerrar</button>':''}</div></div></div>`);document.querySelectorAll('[data-v12-age]').forEach(b=>b.onclick=()=>{V12.ageBand=b.dataset.v12Age;v12Save();document.querySelectorAll('[data-v12-age]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelector('[data-v12-age-save]').onclick=()=>{V12.onboardingDone=true;v12Save();document.querySelector('.v12-modal')?.remove();render()};document.querySelector('[data-v12-close]')?.addEventListener('click',()=>document.querySelector('.v12-modal')?.remove())}
function v12CustomizeModal(){document.querySelector('.v12-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="v12-modal" role="dialog" aria-modal="true"><div class="v12-modal-card"><h2>Personaliza tu compañero</h2><p>${v12AvatarDisplay()} Elige un accesorio. Las insignias se ganan aprendiendo.</p><div class="v12-access-grid">${Object.entries(V12_ACCESSORIES).map(([id,a])=>`<button data-v12-access="${id}" class="${V12.accessory===id?'active':''}"><span>${a[0]||'✨'}</span><b>${a[1]}</b></button>`).join('')}</div><button class="btn btn-primary" data-v12-custom-save>Listo</button></div></div>`);document.querySelectorAll('[data-v12-access]').forEach(b=>b.onclick=()=>{V12.accessory=b.dataset.v12Access;v12Save();document.querySelectorAll('[data-v12-access]').forEach(x=>x.classList.toggle('active',x===b))});document.querySelector('[data-v12-custom-save]').onclick=()=>{document.querySelector('.v12-modal')?.remove();render()}}
function v12Home(){if(!v12Kid()||state.view!=='home')return;const main=document.querySelector('main.container');if(!main)return;const status=main.querySelector('.v11-status');if(status){status.classList.add('v12-status');const btn=status.querySelector('.v11-avatar-btn');if(btn){btn.innerHTML=`<span>${v12AvatarDisplay()}</span><small>${v11Avatar()[1]}</small>`;btn.setAttribute('aria-label','Personalizar avatar');btn.onclick=v12CustomizeModal}status.insertAdjacentHTML('beforeend',`<button class="v12-age-chip" data-v12-age-change>👤 ${v12Age().label}<small>Cambiar guía</small></button>`)}
 const adventure=main.querySelector('.v11-adventure');if(adventure){adventure.insertAdjacentHTML('afterbegin',`<section class="v12-hero-scene"><img src="assets/scene_home.svg" alt="Mapa ilustrado de PET Quest"><div><span class="mission-label">Tu ruta personalizada</span><h2>${v12Age().goal}</h2><p>${v12Age().helper}</p><div class="v12-hero-actions"><button class="btn btn-primary" data-v12-start>▶ Empezar misión</button><button class="btn btn-soft" data-v12-badges>🏅 Mis insignias</button></div></div></section>`)}
 const reward=main.querySelector('.v11-reward');if(reward)reward.insertAdjacentHTML('afterend',`<section class="card v12-collection"><div><span class="mission-label">Mi colección</span><h2>Insignias y stickers</h2><p>Cada logro representa algo que aprendiste.</p></div><div class="v12-collection-stats"><div>🏅 <b>${V12.badges.length}/${V12_BADGES.length}</b><small>insignias</small></div><div>🎟️ <b>${V12.stickers}</b><small>stickers</small></div></div><div class="v12-badge-row">${V12_BADGES.slice(0,5).map(b=>`<span class="${V12.badges.includes(b.id)?'earned':''}" title="${b.name}">${V12.badges.includes(b.id)?b.icon:'🔒'}</span>`).join('')}</div></section>`)
 document.querySelector('[data-v12-age-change]')?.addEventListener('click',()=>v12AgeModal(true));document.querySelector('[data-v12-start]')?.addEventListener('click',()=>{const id=v11MissionTarget();if(id==='mock'){state.view='mock';render()}else startSkill(id,1)});document.querySelector('[data-v12-badges]')?.addEventListener('click',v12BadgesModal)
}
function v12BadgesModal(){document.querySelector('.v12-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="v12-modal" role="dialog" aria-modal="true"><div class="v12-modal-card"><h2>🏅 Mis insignias</h2><p>No compites con otros. Cada insignia marca tu propio avance.</p><div class="v12-badges-grid">${V12_BADGES.map(b=>`<div class="${V12.badges.includes(b.id)?'earned':''}"><span>${V12.badges.includes(b.id)?b.icon:'🔒'}</span><b>${b.name}</b><small>${b.desc}</small></div>`).join('')}</div><button class="btn btn-primary" data-v12-close>Cerrar</button></div></div>`);document.querySelector('[data-v12-close]').onclick=()=>document.querySelector('.v12-modal')?.remove()}
function v12Practice(){if(!v12Kid()||state.view!=='practice')return;const qcard=document.querySelector('.question-card');if(!qcard)return;const skill=state.skill||'reading';const simple=V12.ageBand==='7-9';qcard.insertAdjacentHTML('afterbegin',`<div class="v12-scene"><img src="${v12Scene(skill)}" alt="Escena de ${skill}"><div><span class="mission-label">${simple?'Vamos juntos':'Contexto de la misión'}</span><b>${skill==='reading'?'Entra en la historia':skill==='listening'?'Activa tus oídos':skill==='writing'?'Ordena tus ideas':'Usa tu voz'}</b><p>${simple?'Haz solo un paso cada vez.':v12Age().helper}</p></div></div>`);const side=document.querySelector('.side');if(side){side.insertAdjacentHTML('beforeend',`<div class="v12-focus-box"><b>${v12AvatarDisplay()} Consejo</b><p>${simple?'Si dudas, elimina primero una opción que no tenga sentido.':'Busca una pista concreta antes de elegir.'}</p></div>`)}
}
function v12Studio(){if(!v12Kid()||!['writing','speaking'].includes(state.view))return;const q=document.querySelector('.question-card');if(!q)return;const skill=state.view;q.insertAdjacentHTML('afterbegin',`<div class="v12-scene studio"><img src="${v12Scene(skill)}" alt="Escena de ${skill}"><div><span class="mission-label">${V12.ageBand==='13+'?'Entrenamiento PET':'Misión creativa'}</span><b>${skill==='writing'?'Construye tu respuesta':'Cuenta tu idea con confianza'}</b><p>${V12.ageBand==='7-9'?'Hazlo por partes. Milo te acompaña.':V12.ageBand==='13+'?'Intenta responder con autonomía antes de mirar ayudas.':'Primero idea, luego razón y finalmente detalle.'}</p></div></div>`)}
function v12Adult(){if(v12Kid()||state.view!=='home')return;const main=document.querySelector('main.container');if(!main)return;main.insertAdjacentHTML('afterbegin',`<section class="card v12-adult-note"><div>👨‍👩‍👧</div><div><b>Modo Adulto</b><p>Observa progreso y acompaña. La experiencia infantil se adapta actualmente a <strong>${v12Age().label}</strong>.</p></div><button class="btn btn-soft" data-v12-age-change>Configurar edad</button></section>`);document.querySelector('[data-v12-age-change]')?.addEventListener('click',()=>v12AgeModal(true))}
function enhanceV12(){document.documentElement.dataset.ageBand=V12.ageBand;v12UnlockBadges();v12Home();v12Practice();v12Studio();v12Adult();if(v12Kid()&&!V12.onboardingDone)requestAnimationFrame(()=>v12AgeModal(false))}
const v12RenderBase=render;render=function(){v12RenderBase();requestAnimationFrame(enhanceV12)};requestAnimationFrame(enhanceV12);
