// PET Quest V14 — Milo Guided Tutor
// Closed, predictable tutoring actions for children. Before checking an answer,
// help never reveals the correct option. After checking, full reasoning is allowed.
const V14_STORE='petQuestV14Tutor';
const V14_DEFAULT={helpCounts:{understand:0,hint:0,easier:0,example:0,similar:0,why:0},lastHelp:'',preferredHelp:'',microAttempts:0,microCorrect:0};
let V14=(()=>{try{return {...V14_DEFAULT,...JSON.parse(localStorage.getItem(V14_STORE)||'{}')}}catch{return JSON.parse(JSON.stringify(V14_DEFAULT))}})();
V14.helpCounts={...V14_DEFAULT.helpCounts,...(V14.helpCounts||{})};
function v14Save(){try{localStorage.setItem(V14_STORE,JSON.stringify(V14))}catch{}}
function v14Kid(){return typeof uxMode==='function'&&uxMode()==='kid'&&!(typeof data!=='undefined'&&data.profile?.examProfile==='adult')}
function v14Question(){try{return state.view==='practice'?(currentQuestions()||[])[state.idx]:null}catch{return null}}
function v14Esc(x){return typeof esc==='function'?esc(String(x??'')):String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function v14Count(kind){V14.helpCounts[kind]=(V14.helpCounts[kind]||0)+1;V14.lastHelp=kind;const ranked=Object.entries(V14.helpCounts).sort((a,b)=>b[1]-a[1]);V14.preferredHelp=ranked[0]?.[0]||'';v14Save()}
const V14_FOCUS={
 'so-that':{hint:'Mira la estructura que conecta una intensidad con su resultado.',easy:'La oración dice que algo fue muy interesante y por eso ocurrió otra cosa.',example:'Ejemplo parecido: “The film was so funny that we watched it twice.”'},
 'linkers':{hint:'Pregunta: ¿la segunda idea contrasta, explica una razón o muestra un resultado?',easy:'Compara la primera idea con la segunda y decide cómo se relacionan.',example:'Ejemplo parecido: “I wanted to play outside, but it started raining.”'},
 'prepositions':{hint:'Piensa en la combinación natural que suele acompañar a esa palabra o expresión.',easy:'Busca la palabra pequeña que normalmente va junto al verbo, lugar o tiempo.',example:'Ejemplo: “I am interested in science.” La preposición forma parte de la expresión.'},
 'vocabulary':{hint:'No traduzcas cada palabra. Busca cuál opción encaja mejor con toda la situación.',easy:'Lee la frase completa y pregúntate cuál palabra tiene sentido en ese contexto.',example:'Ejemplo: “The bus was crowded, so we had to stand.” El contexto ayuda a elegir la palabra.'},
 'inference':{hint:'La respuesta puede no aparecer escrita exactamente. Busca dos pistas del texto.',easy:'Piensa: ¿qué podemos entender aunque el texto no lo diga con las mismas palabras?',example:'Si un texto dice “Ana took an umbrella and wore boots”, podemos inferir que esperaba lluvia.'},
 'grammar':{hint:'Mira las palabras antes y después del espacio; ellas suelen indicar la forma necesaria.',easy:'Busca qué forma hace que toda la oración suene completa y correcta.',example:'Ejemplo: “She has lived here for three years.” Las palabras alrededor ayudan a elegir el tiempo.'},
 'default':{hint:'Descarta primero una opción que claramente no encaja y vuelve a leer la frase completa.',easy:'Hazlo en dos pasos: entiende qué pide la pregunta y luego compara solo dos opciones.',example:'Ejemplo de estrategia: lee la oración completa, tapa las opciones e imagina qué tipo de palabra falta.'}
};
function v14FocusHelp(q){const f=String(q?.focus||'').toLowerCase();return V14_FOCUS[f]||Object.entries(V14_FOCUS).find(([k])=>k!=='default'&&f.includes(k))?.[1]||V14_FOCUS.default}
function v14Prompt(kind,q){const h=v14FocusHelp(q);
 if(kind==='understand')return {title:'🦉 Vamos paso a paso',body:`<ol class="v14-steps"><li>Lee solo lo que pregunta: <b>${v14Esc(q.q)}</b></li><li>Vuelve al texto o audio y busca una pista.</li><li>Descarta una opción que no tenga sentido.</li><li>Elige con calma. No necesitas hacerlo perfecto a la primera.</li></ol>`};
 if(kind==='hint')return {title:'💡 Una pista, sin darte la respuesta',body:`<p>${v14Esc(h.hint)}</p><p class="v14-note">Milo no te dirá qué letra elegir antes de que lo intentes.</p>`};
 if(kind==='easier')return {title:'🌱 Más fácil',body:`<p>${v14Esc(h.easy)}</p><div class="v14-easy-box"><b>Tu mini objetivo:</b> encuentra una sola pista antes de mirar otra vez las opciones.</div>`};
 if(kind==='example')return {title:'🧩 Un ejemplo parecido',body:`<p>${v14Esc(h.example)}</p><p class="v14-note">El ejemplo usa otra situación para que puedas descubrir la regla sin copiar la respuesta actual.</p>`};
 if(kind==='why')return {title:'🔎 ¿Por qué?',body:`<p>${v14Esc(q.why||'Revisa cómo la respuesta correcta encaja con el significado y la estructura de la frase.')}</p>${q.tip?`<div class="v14-easy-box"><b>Recuerda:</b> ${v14Esc(q.tip)}</div>`:''}`};
 return {title:'Milo',body:''};
}
const V14_MICRO={
 'prepositions':{q:'Choose the natural phrase: “I am good ___ drawing.”',opts:['at','on','to'],a:0,why:'“Good at” is the usual combination.'},
 'linkers':{q:'Choose the connector: “I was tired, ___ I finished my homework.”',opts:['but','because','so'],a:0,why:'“But” shows contrast.'},
 'so-that':{q:'Choose the pattern: “The game was ___ exciting that everyone cheered.”',opts:['so','such','too'],a:0,why:'Use “so + adjective + that”.'},
 'vocabulary':{q:'Which word fits? “The library was very ___, so I could study easily.”',opts:['quiet','hungry','expensive'],a:0,why:'“Quiet” fits a place where it is easy to study.'},
 'inference':{q:'Leo put on a coat and gloves before leaving. What is most likely true?',opts:['It was cold','It was midnight','He was swimming'],a:0,why:'Coat and gloves are clues that the weather was cold.'},
 'default':{q:'Which strategy is best when you are unsure?',opts:['Read the whole sentence again','Choose immediately','Skip every clue'],a:0,why:'Reading the whole sentence again helps you use context.'}
};
function v14Micro(q){const f=String(q?.focus||'').toLowerCase();return V14_MICRO[f]||V14_MICRO.default}
function v14SimilarHTML(q){const m=v14Micro(q);return `<div class="v14-micro" data-v14-micro><h4>🎯 Mini práctica parecida</h4><p>${v14Esc(m.q)}</p><div class="v14-micro-options">${m.opts.map((o,i)=>`<button type="button" class="v14-micro-opt" data-v14-micro-opt="${i}">${String.fromCharCode(65+i)}. ${v14Esc(o)}</button>`).join('')}</div><div class="v14-micro-feedback" aria-live="polite"></div></div>`}
function v14Panel(){let p=document.querySelector('.v14-tutor-panel');if(!p){p=document.createElement('div');p.className='v14-tutor-panel';p.setAttribute('aria-live','polite');const qcard=document.querySelector('.question-card');qcard?.appendChild(p)}return p}
function v14Show(kind){const q=v14Question();if(!q)return;v14Count(kind);const p=v14Panel();if(!p)return;if(kind==='similar'){p.innerHTML=v14SimilarHTML(q);v14BindMicro();return}const x=v14Prompt(kind,q);p.innerHTML=`<div class="v14-help-card"><button type="button" class="v14-close" data-v14-close aria-label="Cerrar ayuda">×</button><h3>${x.title}</h3>${x.body}</div>`;p.querySelector('[data-v14-close]')?.addEventListener('click',()=>p.innerHTML='')}
function v14BindMicro(){const p=v14Panel(),q=v14Question(),m=v14Micro(q);p?.querySelectorAll('[data-v14-micro-opt]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.done)return;const chosen=+b.dataset.v14MicroOpt;V14.microAttempts++;if(chosen===m.a)V14.microCorrect++;v14Save();p.querySelectorAll('[data-v14-micro-opt]').forEach(x=>{x.dataset.done='1';x.disabled=true;if(+x.dataset.v14MicroOpt===m.a)x.classList.add('correct');else if(x===b)x.classList.add('wrong')});const f=p.querySelector('.v14-micro-feedback');if(f)f.innerHTML=chosen===m.a?`<div class="feedback ok"><b>¡Bien pensado! ⭐</b><div>${v14Esc(m.why)}</div></div>`:`<div class="feedback bad"><b>Casi. Miremos la idea.</b><div>${v14Esc(m.why)}</div></div>`}))}
function v14TutorBar(){if(!v14Kid()||state.view!=='practice')return;const qcard=document.querySelector('.question-card');if(!qcard||qcard.querySelector('.v14-tutor'))return;const checked=!!state.checked;const preferred=V14.preferredHelp;const label=k=>preferred===k?' · favorito':'';const html=`<section class="v14-tutor" aria-label="Ayuda de Milo"><div class="v14-tutor-head"><img src="assets/mascot.svg" alt="Milo"/><div><span class="mission-label">Milo te ayuda</span><b>${checked?'Ahora sí podemos entender el porqué':'Elige la ayuda que necesites'}</b><small>${checked?'Aprender del intento vale más que acertar por suerte.':'Ningún botón te dará la respuesta antes de intentarlo.'}</small></div></div><div class="v14-actions">${checked?`<button type="button" data-v14-help="why">🔎 Explícame por qué</button>`:`<button type="button" data-v14-help="understand">🤔 No entendí${label('understand')}</button><button type="button" data-v14-help="hint">💡 Dame una pista${label('hint')}</button><button type="button" data-v14-help="easier">🌱 Más fácil${label('easier')}</button><button type="button" data-v14-help="example">🧩 Ponme un ejemplo${label('example')}</button><button type="button" data-v14-help="similar">🎯 Algo parecido${label('similar')}</button>`}</div><div class="v14-tutor-panel" aria-live="polite"></div></section>`;
 const anchor=qcard.querySelector('.options');if(anchor)anchor.insertAdjacentHTML('beforebegin',html);else qcard.insertAdjacentHTML('beforeend',html);qcard.querySelectorAll('[data-v14-help]').forEach(b=>b.addEventListener('click',()=>v14Show(b.dataset.v14Help)))}
function v14AdultInsight(){if(v14Kid()||state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v14-adult-help'))return;const total=Object.values(V14.helpCounts).reduce((a,b)=>a+b,0);const map={understand:'No entendí',hint:'Pista',easier:'Explicación fácil',example:'Ejemplo',similar:'Práctica parecida',why:'Explicación posterior'};const top=Object.entries(V14.helpCounts).sort((a,b)=>b[1]-a[1])[0];main.insertAdjacentHTML('beforeend',`<section class="card v14-adult-help"><div class="section-title"><div><h2>🦉 Uso del Tutor Milo</h2><p>Ayudas solicitadas por el estudiante; sirven para personalizar el acompañamiento, no para diagnosticar.</p></div></div><div class="v14-adult-grid"><div><span>Ayudas utilizadas</span><b>${total}</b></div><div><span>Apoyo más usado</span><b>${top&&top[1]?v14Esc(map[top[0]]):'Aún sin datos'}</b></div><div><span>Mini prácticas</span><b>${V14.microAttempts}</b></div><div><span>Aciertos mini práctica</span><b>${V14.microAttempts?Math.round(V14.microCorrect/V14.microAttempts*100)+'%':'—'}</b></div></div></section>`)}
function v14Enhance(){document.documentElement.classList.toggle('v14-kid',v14Kid());v14TutorBar();v14AdultInsight()}
const v14RenderBase=render;
render=function(){v14RenderBase();requestAnimationFrame(v14Enhance)};
requestAnimationFrame(v14Enhance);
