/* PET Quest V16 — Speaking & Writing Studio */
(function(){
'use strict';
const KEY='petquest_v16_learning';
const V16=Object.assign({speaking:{attempts:[],streak:0,best:0},writing:{drafts:[],lastStage:'ideas'},preferences:{modelVoice:'en-GB'}},JSON.parse(localStorage.getItem(KEY)||'{}'));
function save16(){localStorage.setItem(KEY,JSON.stringify(V16))}
function E(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function kid(){return document.documentElement.classList.contains('v15-kid') || (window.V10&&V10.mode==='kid')}
const SPEAK=[
 {title:'My school day',prompt:'Tell me about your school day. What subject do you enjoy most and why?',model:'My favourite subject is science because I enjoy doing experiments. For example, last week we made a small volcano in class.',chunks:['My favourite subject is science.','I enjoy it because we do experiments.','For example, last week we made a small volcano.']},
 {title:'Describe a picture',prompt:'Describe two friends preparing food together in a kitchen.',model:'In the picture, two friends are cooking together in a bright kitchen. One person is cutting vegetables while the other is mixing something in a bowl.',chunks:['Two friends are cooking together.','One person is cutting vegetables.','The other person is mixing something in a bowl.']},
 {title:'Make a suggestion',prompt:'Suggest an activity for an end-of-term celebration.',model:'I think a picnic would be a good idea because everyone can talk and play games. We could also bring music and some simple food.',chunks:['I think a picnic would be a good idea.','Everyone can talk and play games.','We could also bring music and food.']},
 {title:'Give your opinion',prompt:'Do you prefer free time with friends or family? Why?',model:'I usually prefer spending free time with my family because we can relax together. However, I also enjoy meeting my friends at the weekend.',chunks:['I prefer spending free time with my family.','We can relax together.','However, I also enjoy meeting my friends.']}
];
const WRITE=[
 {title:'Email to Alex',task:'Your English friend Alex asks about your school club. Tell Alex what club you joined, why you chose it, and invite Alex to join you one day.',ideas:['What club did you join?','Why did you choose it?','When can Alex join you?'],starter:'Hi Alex,\n\nThanks for your message. I joined...'},
 {title:'Free afternoon article',task:'Write an article: “The best way to spend a free afternoon.”',ideas:['What activity is best?','Why is it enjoyable?','Who can do it with you?'],starter:'The best way to spend a free afternoon is...'},
 {title:'Story starter',task:'Write a story beginning: “When I opened the door, I could not believe what I saw.”',ideas:['What did you see?','How did you feel?','What happened next?'],starter:'When I opened the door, I could not believe what I saw. ...'}
];
function norm(t){return String(t||'').toLowerCase().replace(/[^a-z0-9' ]/g,' ').replace(/\s+/g,' ').trim()}
function similarity(a,b){const A=norm(a).split(' ').filter(Boolean),B=norm(b).split(' ').filter(Boolean);if(!A.length||!B.length)return 0;const set=new Set(B);const hits=A.filter(x=>set.has(x)).length;return Math.round(100*hits/Math.max(A.length,B.length))}
function speakModel(text){if(!('speechSynthesis'in window))return window.toast?.('Audio de modelo no disponible en este navegador');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.88;speechSynthesis.speak(u)}
function recognize(cb){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){window.toast?.('El reconocimiento de voz no está disponible aquí');return}const r=new R();r.lang='en-GB';r.interimResults=false;r.maxAlternatives=1;r.onresult=e=>cb(e.results[0][0].transcript,e.results[0][0].confidence||0);r.onerror=()=>window.toast?.('No pude reconocer la voz. Puedes intentarlo otra vez.');r.start()}
function speakingStudio(){
 const i=Math.max(0,Math.min(3,state.idx||0)),x=SPEAK[i],attempts=V16.speaking.attempts.filter(a=>a.part===i+1),best=attempts.length?Math.max(...attempts.map(a=>a.score)):0;
 el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Speaking Adventure',`Parte ${i+1} de 4 · escucha, repite y crea tu propia respuesta`)}
 <section class="v16-speak-hero card"><div><span class="mission-label">🎙️ Entrena tu voz</span><h2>${E(x.title)}</h2><p>${E(x.prompt)}</p></div><div class="v16-score-orb"><b>${best}%</b><span>mejor intento</span></div></section>
 <div class="v16-two-col"><section class="card"><h3>1. Escucha el modelo</h3><p class="small">Escucha el ritmo. No necesitas copiar cada palabra.</p><div class="v16-model">${E(x.model)}</div><button class="btn btn-primary" data-v16-model="${i}">🔊 Escuchar modelo</button></section>
 <section class="card"><h3>2. Repite por partes</h3><div class="v16-chunks">${x.chunks.map((c,n)=>`<div class="v16-chunk"><span>${n+1}</span><p>${E(c)}</p><button class="btn btn-soft mini" data-v16-chunk="${i}:${n}">🔊</button><button class="btn btn-soft mini" data-v16-repeat="${i}:${n}">🎙️ Repetir</button></div>`).join('')}</div><div id="v16RepeatFeedback" aria-live="polite"></div></section></div>
 <section class="card v16-own-answer"><h3>3. Ahora dilo con tus propias palabras</h3><div class="v16-speak-steps"><span>💬 Responde</span><span>💡 Da una razón</span><span>🧩 Añade un ejemplo</span></div><textarea id="v16SpeakingText" class="textarea" placeholder="Tu transcripción aparecerá aquí o puedes escribir lo que dijiste..."></textarea><div class="row"><button class="btn btn-primary" data-v16-own>🎙️ Hablar</button><button class="btn btn-soft" data-v16-eval>✨ Revisar mi respuesta</button></div><div id="v16SpeakFeedback" aria-live="polite"></div></section>
 <section class="card"><h3>4. ¿Cómo te sentiste?</h3><div class="v16-self-rate"><button class="btn btn-soft" data-v16-self="1">😟 Me costó</button><button class="btn btn-soft" data-v16-self="2">🙂 Bien</button><button class="btn btn-soft" data-v16-self="3">😄 Muy claro</button></div><p class="small">Tu autoevaluación ayuda a Milo a elegir la próxima práctica.</p></section>
 <div class="row action-row"><button class="btn btn-ghost" data-speaking-prev ${i===0?'disabled':''}>← Anterior</button><button class="btn btn-primary" data-speaking-next>${i===3?'Finalizar':'Siguiente →'}</button></div>
 </main></div>`)
}
function evalOwn(text,part){const low=norm(text),words=low.split(' ').filter(Boolean);const reason=/\b(because|so|as)\b/.test(low),example=/\b(for example|for instance|such as|last|when)\b/.test(low),link=(low.match(/\b(and|but|because|so|also|then|however|although)\b/g)||[]).length;let score=Math.min(100,Math.round((Math.min(words.length,45)/45)*45+(reason?20:0)+(example?20:0)+Math.min(link,3)*5));const tips=[];if(words.length<15)tips.push('Añade 1 o 2 frases más.');if(!reason)tips.push('Explica una razón con “because”.');if(!example)tips.push('Añade un ejemplo o detalle concreto.');if(link<2)tips.push('Une ideas con and, but, so o because.');if(!tips.length)tips.push('¡Muy buena estructura! Ahora repítela intentando sonar natural.');V16.speaking.attempts.push({at:new Date().toISOString(),part,score,words:words.length,text});V16.speaking.best=Math.max(V16.speaking.best||0,score);V16.speaking.streak=score>=70?(V16.speaking.streak||0)+1:0;save16();return{score,tips}}
function writingBuilder(){const idx=Math.max(0,Math.min(WRITE.length-1,state.idx||0)),x=WRITE[idx],draft=V16.writing.drafts.find(d=>d.task===idx)||{ideas:['','',''],sentences:['','',''],paragraph:'',final:''};
 el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Writing Builder','De ideas pequeñas a un texto PET completo, sin página en blanco.')}
 <section class="card v16-writing-task"><span class="mission-label">✍️ Tu misión</span><h2>${E(x.title)}</h2><p>${E(x.task)}</p><div class="nav-tabs">${WRITE.map((w,n)=>`<button class="tab ${n===idx?'active':''}" data-v16-write-task="${n}">${n+1}. ${E(w.title)}</button>`).join('')}</div></section>
 <section class="v16-writing-rail" aria-label="Pasos de Writing"><button class="active" data-v16-stage="ideas">1️⃣ Ideas</button><button data-v16-stage="sentences">2️⃣ Frases</button><button data-v16-stage="paragraph">3️⃣ Párrafo</button><button data-v16-stage="final">4️⃣ Texto PET</button></section>
 <section class="card" id="v16WritingStage">${writingStageHtml(idx,draft,V16.writing.lastStage||'ideas')}</section>
 </main></div>`)
}
function writingStageHtml(idx,d,stage){const x=WRITE[idx];if(stage==='ideas')return `<h3>1. Junta 3 ideas</h3><p class="small">Escribe palabras o frases cortas. Todavía no necesitas escribir perfecto.</p>${x.ideas.map((q,n)=>`<label><span>${E(q)}</span><input class="input" data-v16-idea="${n}" value="${E(d.ideas[n]||'')}" placeholder="Mi idea..."></label>`).join('')}<button class="btn btn-primary" data-v16-next-stage="sentences">Convertir en frases →</button>`;
 if(stage==='sentences')return `<h3>2. Convierte tus ideas en frases</h3><p class="notice"><b>Modelo:</b> I chose the art club <b>because</b> I love drawing.</p>${[0,1,2].map(n=>`<label><span>Frase ${n+1}</span><input class="input" data-v16-sentence="${n}" value="${E(d.sentences[n]||d.ideas[n]||'')}" placeholder="Write a complete sentence..."></label>`).join('')}<div class="row"><button class="btn btn-ghost" data-v16-next-stage="ideas">← Ideas</button><button class="btn btn-primary" data-v16-next-stage="paragraph">Unir en párrafo →</button></div>`;
 if(stage==='paragraph')return `<h3>3. Une las frases</h3><p class="small">Usa conectores como <b>and, but, because, so, then</b>.</p><textarea class="textarea" id="v16Paragraph" placeholder="${E(x.starter)}">${E(d.paragraph||d.sentences.filter(Boolean).join(' '))}</textarea><div class="v16-connectors"><button data-v16-insert=" because ">because</button><button data-v16-insert=" and ">and</button><button data-v16-insert=" but ">but</button><button data-v16-insert=" so ">so</button><button data-v16-insert=" then ">then</button></div><div class="row"><button class="btn btn-ghost" data-v16-next-stage="sentences">← Frases</button><button class="btn btn-primary" data-v16-next-stage="final">Construir texto PET →</button></div>`;
 return `<h3>4. Tu texto PET</h3><p class="small">Revisa contenido, organización y lenguaje. Objetivo aproximado: 100 palabras.</p><textarea class="textarea v16-final" id="v16FinalText" placeholder="${E(x.starter)}">${E(d.final||d.paragraph||'')}</textarea><div class="row between"><span><b id="v16WordCount">${(d.final||d.paragraph||'').trim().split(/\s+/).filter(Boolean).length}</b> palabras</span><div class="row"><button class="btn btn-ghost" data-v16-next-stage="paragraph">← Párrafo</button><button class="btn btn-primary" data-v16-writing-review>✨ Revisar mi texto</button></div></div><div id="v16WritingFeedback" aria-live="polite"></div>`}
function getDraft(idx){let d=V16.writing.drafts.find(x=>x.task===idx);if(!d){d={task:idx,ideas:['','',''],sentences:['','',''],paragraph:'',final:'',updated:new Date().toISOString()};V16.writing.drafts.push(d)}return d}
function persistWriting(){const idx=Math.max(0,Math.min(WRITE.length-1,state.idx||0)),d=getDraft(idx);document.querySelectorAll('[data-v16-idea]').forEach(i=>d.ideas[+i.dataset.v16Idea]=i.value);document.querySelectorAll('[data-v16-sentence]').forEach(i=>d.sentences[+i.dataset.v16Sentence]=i.value);const p=document.getElementById('v16Paragraph'),f=document.getElementById('v16FinalText');if(p)d.paragraph=p.value;if(f)d.final=f.value;d.updated=new Date().toISOString();save16();return d}
function setStage(stage){persistWriting();V16.writing.lastStage=stage;save16();const idx=state.idx||0,d=getDraft(idx),host=document.getElementById('v16WritingStage');if(host){host.innerHTML=writingStageHtml(idx,d,stage);document.querySelectorAll('.v16-writing-rail button').forEach(b=>b.classList.toggle('active',b.dataset.v16Stage===stage));bind16()}}
function reviewWriting(){const d=persistWriting(),text=d.final.trim(),words=text.split(/\s+/).filter(Boolean),low=norm(text);const coverage=d.ideas.filter(Boolean).length;const connectors=(low.match(/\b(and|but|because|so|then|however|although|also)\b/g)||[]).length;const sentences=(text.match(/[.!?]+/g)||[]).length;let score=Math.min(100,Math.round(Math.min(words.length,100)/100*35+coverage/3*25+Math.min(connectors,4)/4*20+Math.min(sentences,5)/5*20));const tips=[];if(words.length<80)tips.push('Amplía una idea con un detalle o ejemplo.');if(coverage<3)tips.push('Comprueba que respondes las 3 ideas de la tarea.');if(connectors<2)tips.push('Usa al menos dos conectores para unir ideas.');if(sentences<4)tips.push('Divide el texto en más frases completas.');if(!tips.length)tips.push('¡Muy buen borrador! Haz una última lectura buscando mayúsculas y puntuación.');document.getElementById('v16WritingFeedback').innerHTML=`<div class="feedback ${score>=70?'ok':'neutral'}"><b>Writing Builder: ${score}/100</b><div class="v16-checks"><span>${coverage===3?'✅':'🌱'} Contenido ${coverage}/3</span><span>${connectors>=2?'✅':'🌱'} Conectores ${connectors}</span><span>${words.length>=80?'✅':'🌱'} ${words.length} palabras</span></div><ul>${tips.map(t=>`<li>${E(t)}</li>`).join('')}</ul><div class="small">Feedback orientativo de práctica. La calificación oficial requiere evaluación humana con los criterios del examen.</div></div>`;d.score=score;save16()}
function adultInsight(){if(kid()||state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v16-adult-insight'))return;const sa=V16.speaking.attempts,wd=V16.writing.drafts;main.insertAdjacentHTML('beforeend',`<section class="card v16-adult-insight"><h2>🎙️✍️ Speaking & Writing V16</h2><div class="v16-summary-grid"><div><b>${sa.length}</b><small>intentos Speaking</small></div><div><b>${V16.speaking.best||0}%</b><small>mejor estructura oral</small></div><div><b>${wd.length}</b><small>borradores Writing</small></div><div><b>${wd.length?Math.round(wd.reduce((s,d)=>s+(d.score||0),0)/wd.length):0}%</b><small>Writing guiado</small></div></div><p class="small">La puntuación de Speaking se basa en estructura/transcripción y no constituye una medición acústica de pronunciación.</p></section>`)}
function bind16(){
 document.querySelectorAll('[data-v16-model]').forEach(b=>b.onclick=()=>speakModel(SPEAK[+b.dataset.v16Model].model));
 document.querySelectorAll('[data-v16-chunk]').forEach(b=>b.onclick=()=>{const [i,n]=b.dataset.v16Chunk.split(':').map(Number);speakModel(SPEAK[i].chunks[n])});
 document.querySelectorAll('[data-v16-repeat]').forEach(b=>b.onclick=()=>{const [i,n]=b.dataset.v16Repeat.split(':').map(Number),target=SPEAK[i].chunks[n];recognize((text,confidence)=>{const score=similarity(text,target);document.getElementById('v16RepeatFeedback').innerHTML=`<div class="feedback ${score>=65?'ok':'neutral'}"><b>${score}% de palabras reconocidas en común</b><p>Escuché: “${E(text)}”</p><p>${score>=80?'¡Muy cerca! Repite una vez más buscando ritmo natural.':score>=55?'Buen intento. Escucha el modelo y prueba otra vez.':'Vamos por partes: escucha, respira y repite más despacio.'}</p><div class="small">Es una aproximación basada en reconocimiento de voz; no mide fonemas ni acento con precisión.</div></div>`;V16.speaking.attempts.push({at:new Date().toISOString(),part:i+1,chunk:n+1,score,recognized:text,confidence});save16()})});
 document.querySelector('[data-v16-own]')?.addEventListener('click',()=>recognize(text=>{document.getElementById('v16SpeakingText').value=text}));
 document.querySelector('[data-v16-eval]')?.addEventListener('click',()=>{const ta=document.getElementById('v16SpeakingText'),r=evalOwn(ta.value,(state.idx||0)+1);document.getElementById('v16SpeakFeedback').innerHTML=`<div class="feedback ${r.score>=70?'ok':'neutral'}"><b>Estructura de tu respuesta: ${r.score}/100</b><ul>${r.tips.map(t=>`<li>${E(t)}</li>`).join('')}</ul><div class="small">Evalúa contenido y estructura de la transcripción, no pronunciación acústica.</div></div>`});
 document.querySelectorAll('[data-v16-self]').forEach(b=>b.onclick=()=>{V16.speaking.lastSelf=+b.dataset.v16Self;save16();b.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('btn-primary',x===b));window.toast?.('Autoevaluación guardada')});
 document.querySelectorAll('[data-v16-write-task]').forEach(b=>b.onclick=()=>{persistWriting();state.idx=+b.dataset.v16WriteTask;render()});
 document.querySelectorAll('[data-v16-next-stage]').forEach(b=>b.onclick=()=>setStage(b.dataset.v16NextStage));
 document.querySelectorAll('[data-v16-insert]').forEach(b=>b.onclick=()=>{const t=document.getElementById('v16Paragraph');if(!t)return;const s=t.selectionStart||t.value.length;t.value=t.value.slice(0,s)+b.dataset.v16Insert+t.value.slice(t.selectionEnd||s);t.focus();persistWriting()});
 document.querySelector('[data-v16-writing-review]')?.addEventListener('click',reviewWriting);
 const f=document.getElementById('v16FinalText');if(f)f.oninput=()=>{document.getElementById('v16WordCount').textContent=f.value.trim().split(/\s+/).filter(Boolean).length;persistWriting()};
 document.querySelectorAll('[data-v16-idea],[data-v16-sentence]').forEach(i=>i.oninput=persistWriting)
}
const oldSpeaking=speaking,oldWriting=writing,oldRender=render;
speaking=speakingStudio;writing=writingBuilder;
render=function(){oldRender();requestAnimationFrame(()=>{if(state.view==='speaking'||state.view==='writing')bind16();adultInsight()})};
window.PETQUEST_V16={state:V16,similarity,evalOwn,version:'16.0'};
requestAnimationFrame(()=>{if(state.view==='speaking'||state.view==='writing')render();else adultInsight()});
})();
