// PET Quest V19 — Immersive Reading Lab
(()=>{
'use strict';
const KEY='petQuestV19Reading';
const V19=Object.assign({mode:'learn',chunk:0,showClues:false,eliminated:{},stats:{clues:0,chunks:0,vocab:0,eliminations:0},exam:{active:false,idx:0,answers:[],startedAt:null,finished:[]}},JSON.parse(localStorage.getItem(KEY)||'{}'));
V19.stats=Object.assign({clues:0,chunks:0,vocab:0,eliminations:0},V19.stats||{});V19.exam=Object.assign({active:false,idx:0,answers:[],startedAt:null,finished:[]},V19.exam||{});V19.eliminated=V19.eliminated||{};
const E=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save19=()=>localStorage.setItem(KEY,JSON.stringify(V19));
const readingBank=()=>BANK.reading.slice(0,32);
const focusHelp={
 notices:['acción principal','fecha/hora','obligación o prohibición'],instructions:['must / need / please','quién debe actuar','cuándo'],places:['preposición de lugar','ubicación exacta','cambio de lugar'],matching:['todas las condiciones','precio/horario','preferencias'],collocations:['expresión completa','verbo + sustantivo','frase natural'],grammar:['estructura alrededor del hueco','tiempo verbal','palabras funcionales'],vocabulary:['contexto antes y después','significado lógico','tono de la frase'],detail:['dato específico','frecuencia','quién hace qué'],purpose:['por qué aparece ese detalle','efecto en el texto','intención del autor'],'main-idea':['idea repetida','mejor resumen','no un detalle pequeño'],cohesion:['frase anterior','frase siguiente','conector lógico'],reference:['this/that/it/they','idea anterior','coherencia'],sequence:['orden temporal','before/after','causa y resultado'],inference:['lo que se puede concluir','cambio de situación','evidencia indirecta'],attitude:['at first / but / surprisingly','opinión final','cambio de sentimiento'],prepositions:['expresión fija','lugar/tiempo','palabra que sigue'],articles:['sonido inicial','a/an/the','referencia general/específica'],quantifiers:['contable/incontable','singular/plural','cantidad'],linkers:['contraste','razón','resultado'],'phrasal-verbs':['verbo + partícula','significado conjunto','contexto'], 'relative-clauses':['persona/cosa/lugar','who/which/where','antecedente']
};
const vocabMap={
 must:'debe / obligación',instead:'en cambio / en su lugar',return:'devolver',closed:'cerrado',outdoors:'al aire libre',cheap:'económico',confident:'con confianza',regular:'regular / frecuente',schedule:'horario / planificación',worried:'preocupado',however:'sin embargo',nearly:'casi',expected:'esperaba',surprisingly:'sorprendentemente',repair:'reparar',provide:'proporcionar',available:'disponible',clear:'claro',choose:'elegir',join:'unirse',improve:'mejorar',care:'cuidado',alone:'solo/a',delayed:'retrasado',favour:'favor',engineer:'ingeniero/a'
};
function textFor(q){return q.notice||q.q||''}
function chunksFor(q){const t=textFor(q).trim();if(t.length<110)return [t];const sentences=t.match(/[^.!?]+[.!?]?/g)||[t];if(sentences.length<=2)return sentences;const out=[];for(let i=0;i<sentences.length;i+=2)out.push(sentences.slice(i,i+2).join(' ').trim());return out}
function vocabFor(q){const low=textFor(q).toLowerCase();const found=Object.entries(vocabMap).filter(([k])=>new RegExp('\\b'+k+'\\b','i').test(low)).slice(0,5);if(found.length)return found;const fallback={inference:[['at first','al principio'],['later','más tarde']],attitude:[['expected','esperaba'],['final','final']],cohesion:[['however','sin embargo'],['as a result','como resultado']],matching:[['best','mejor opción'],['wants','quiere']],notices:[['please','por favor / instrucción'],['before','antes de']]};return fallback[q.focus]||[['context','usa el contexto'],['clue','pista']]
}
function clueWords(q){return focusHelp[q.focus]||['idea principal','palabras clave','evidencia del texto']}
function strategy(q){const m={1:'Lee el aviso y decide qué acción o información cambia.',2:'Comprueba una por una todas las condiciones antes de elegir.',3:'Busca evidencia en el texto; no respondas solo por una palabra parecida.',4:'Lee la frase anterior y la siguiente: la opción debe unir las dos.',5:'Mira la estructura completa alrededor del hueco.',6:'Comprueba gramática y expresión fija dentro de toda la oración.'};return m[q.part]||'Encuentra evidencia antes de elegir.'}
function modeBar(){return `<div class="v19-modebar"><button class="${V19.mode==='learn'?'active':''}" data-v19-mode="learn">🌱 Aprender</button><button class="${V19.mode==='exam'?'active':''}" data-v19-mode="exam">🏁 Simular examen</button></div>`}
function learningScreen(){
 const qs=currentQuestions(),q=qs[state.idx];if(!q)return basePractice();const chunks=chunksFor(q),ci=Math.min(V19.chunk,chunks.length-1),elim=V19.eliminated[q.id]||[];
 const solved=state.checked&&state.selected===q.a;const opts=q.opts.map((o,i)=>`<div class="v19-option-wrap ${elim.includes(i)?'is-eliminated':''}"><button class="option ${state.selected===i?'selected':''} ${state.checked&&!solved&&state.selected===i?'wrong':''}" data-opt="${i}" ${solved?'disabled':''}><span class="option-key">${String.fromCharCode(65+i)}</span><span class="option-text">${E(o)}</span></button>${!solved?`<button class="v19-eliminate" data-v19-eliminate="${i}" aria-label="Descartar opción ${String.fromCharCode(65+i)}">✕ descartar</button>`:''}</div>`).join('');
 const fb=state.checked&&!solved?`<div class="feedback bad"><b>❌ Esa respuesta no es correcta.</b><p>Inténtalo nuevamente.</p></div>`:'';
 const clues=V19.showClues?`<div class="v19-cluebox"><b>🔎 Busca estas pistas</b>${clueWords(q).map(x=>`<span>${E(x)}</span>`).join('')}<p>${E(q.tip||strategy(q))}</p></div>`:'';
 el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Reading Lab',`Parte ${q.part} · ${state.idx+1}/${qs.length} · ${E(q.focus)}`)}${modeBar()}<section class="v19-reading-hero card"><img src="assets/scene_reading.svg" alt="Escena de Reading"><div><span class="badge">📖 Aprende a encontrar evidencia</span><h2>${E(strategy(q))}</h2><p>Milo te guía sin revelar la respuesta.</p></div></section><div class="exercise-layout"><section class="card question-card"><div class="v19-read-steps"><span class="active">1 Entiende</span><span>2 Encuentra</span><span>3 Descarta</span><span>4 Justifica</span></div><div class="v19-text-card"><div class="row between"><b>📄 Texto</b><span class="small">Fragmento ${ci+1}/${chunks.length}</span></div><p>${E(chunks[ci])}</p>${chunks.length>1?`<div class="row"><button class="btn btn-ghost mini" data-v19-prev-chunk ${ci===0?'disabled':''}>← anterior</button><button class="btn btn-soft mini" data-v19-next-chunk ${ci===chunks.length-1?'disabled':''}>siguiente fragmento →</button><button class="btn btn-ghost mini" data-v19-show-all>ver texto completo</button></div>`:''}</div><details class="v19-vocab" data-v19-vocab><summary>🧠 Vocabulario contextual (opcional)</summary><div class="v19-vocab-grid">${vocabFor(q).map(([a,b])=>`<div><b>${E(a)}</b><span>${E(b)}</span></div>`).join('')}</div></details><div class="row v19-tools"><button class="btn btn-soft" data-v19-clues>🔎 ${V19.showClues?'Ocultar':'Mostrar'} pistas</button><span class="small">Descarta opciones solo cuando tengas una razón.</span></div>${clues}<div class="prompt">${E(q.q)}</div><div class="options v19-options">${opts}</div>${fb}<div class="row action-row"><button class="btn btn-primary" data-next ${state.selected===null?'disabled':''}>${state.idx===qs.length-1?'Finalizar':'Siguiente →'}</button></div></section><aside class="card side"><h3>🦉 Estrategia Milo</h3><p>${E(strategy(q))}</p><div class="metric"><span>Foco</span><b>${E(q.focus)}</b></div><div class="metric"><span>Pistas usadas</span><b>${V19.stats.clues||0}</b></div><div class="metric"><span>Opciones descartadas</span><b>${V19.stats.eliminations||0}</b></div><button class="btn btn-ghost mini" data-v19-mode="exam">Probar modo examen</button></aside></div></main></div>`)
}
function examQuestions(){return readingBank()}
function startExam(){V19.exam={active:true,idx:0,answers:[],startedAt:Date.now(),finished:V19.exam.finished||[]};save19();render()}
function remainingMs(){return Math.max(0,45*60*1000-(Date.now()-(V19.exam.startedAt||Date.now())))}
function fmt(ms){const s=Math.ceil(ms/1000),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function examScreen(){
 if(!V19.exam.active){el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Reading Exam Practice','32 preguntas · 6 partes · 45 minutos · sin ayudas')}${modeBar()}<section class="card v19-exam-intro"><img src="assets/scene_reading.svg" alt="Reading exam"><h2>Modo examen</h2><p>Trabaja con las 32 preguntas completas. No hay vocabulario, pistas, descarte guiado ni explicación hasta terminar.</p><div class="notice"><b>Práctica PET Quest:</b> contenido original y simulación orientativa; no reproduce materiales oficiales.</div><button class="btn btn-primary" data-v19-start-exam>Empezar Reading Exam</button></section></main></div>`);return}
 if(remainingMs()<=0)return finishExam(true);const qs=examQuestions(),q=qs[V19.exam.idx];if(!q)return finishExam(false);const selected=V19.exam.answers[V19.exam.idx]?.answer;const opts=q.opts.map((o,i)=>`<button class="option ${selected===i?'selected':''}" data-v19-exam-opt="${i}">${String.fromCharCode(65+i)}. ${E(o)}</button>`).join('');
 el(`<div class="app-shell">${topBar()}<main class="container"><div class="mock-top"><div><h1>Reading Exam Practice</h1><p>${V19.exam.idx+1}/32 · Parte ${q.part}</p></div><div class="timer" id="v19Timer">⏱ ${fmt(remainingMs())}</div></div>${modeBar()}<section class="card question-card"><div class="v19-exam-text">${E(textFor(q))}</div><div class="prompt">${E(q.q)}</div><div class="options">${opts}</div><div class="row action-row"><button class="btn btn-primary" data-v19-exam-next ${selected===undefined?'disabled':''}>${V19.exam.idx===31?'Finalizar examen':'Guardar y seguir →'}</button></div><p class="small">Modo examen: sin pistas, traducción, descarte guiado ni explicación inmediata.</p></section></main></div>`);tickTimer()
}
let timerHandle=null;function tickTimer(){clearInterval(timerHandle);timerHandle=setInterval(()=>{const n=document.getElementById('v19Timer');if(!n){clearInterval(timerHandle);return}const ms=remainingMs();n.textContent='⏱ '+fmt(ms);if(ms<=0){clearInterval(timerHandle);finishExam(true)}},1000)}
function finishExam(timeout=false){clearInterval(timerHandle);const qs=examQuestions(),answers=V19.exam.answers,details=qs.map((q,i)=>({qid:q.id,part:q.part,focus:q.focus,correct:answers[i]?.answer===q.a,answer:answers[i]?.answer}));const answered=details.filter((d,i)=>answers[i]!==undefined).length,correct=details.filter(x=>x.correct).length,score=Math.round(correct/32*100);const byPart=[1,2,3,4,5,6].map(p=>{const x=details.filter(d=>d.part===p);return{part:p,total:x.length,correct:x.filter(d=>d.correct).length,pct:x.length?Math.round(x.filter(d=>d.correct).length/x.length*100):0}});const focus={};details.forEach(d=>{focus[d.focus]=focus[d.focus]||{total:0,correct:0};focus[d.focus].total++;if(d.correct)focus[d.focus].correct++});const byFocus=Object.entries(focus).map(([name,x])=>({focus:name,pct:Math.round(x.correct/x.total*100),total:x.total})).sort((a,b)=>a.pct-b.pct);const record={at:new Date().toISOString(),score,correct,total:32,answered,timeout,byPart,byFocus};V19.exam.finished.push(record);V19.exam.active=false;save19();data.mockAttempts.push({date:record.at,skill:'reading',score,correct,total:32,source:'v19-reading-exam'});details.forEach((d,i)=>{if(answers[i]!==undefined)data.history.push({date:record.at,qid:d.qid,skill:'reading',level:3,focus:d.focus,correct:d.correct,answer:d.answer,source:'v19-exam'})});save();
 el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Reading Exam Review','Resultados de tu simulación V19')}<section class="card highlight"><div class="label">RESULTADO</div><div class="big-number">${score}%</div><p>${correct}/32 correctas · ${answered}/32 respondidas${timeout?' · tiempo terminado':''}</p></section><div class="dashboard-grid three">${byPart.map(x=>`<div class="card"><div class="label">Parte ${x.part}</div><div class="big-number">${x.pct}%</div><p>${x.correct}/${x.total}</p></div>`).join('')}</div><section class="card"><h2>🧠 Focos que conviene reforzar</h2><div class="v19-focus-list">${byFocus.slice(0,6).map(x=>`<div><span>${E(x.focus)}</span><b>${x.pct}%</b></div>`).join('')}</div><p class="small">Vuelve a modo Aprender para entrenar evidencia, vocabulario y descarte.</p><button class="btn btn-primary" data-v19-mode="learn">Volver al Reading Lab</button></section></main></div>`);bind19()
}
function adultInsight(){const kid=document.documentElement.classList.contains('v15-kid')||(window.V10&&V10.mode==='kid');if(kid||state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v19-adult-insight'))return;const last=V19.exam.finished?.slice(-1)[0];main.insertAdjacentHTML('beforeend',`<section class="card v19-adult-insight"><h2>📖 Reading V19</h2><div class="v16-summary-grid"><div><b>${V19.stats.clues||0}</b><small>pistas usadas</small></div><div><b>${V19.stats.chunks||0}</b><small>fragmentos navegados</small></div><div><b>${V19.stats.eliminations||0}</b><small>descartes razonados</small></div><div><b>${last?last.score:'—'}${last?'%':''}</b><small>último exam practice</small></div></div><p class="small">Una precisión alta con pocas ayudas indica más autonomía que la misma precisión dependiendo siempre de pistas.</p></section>`)}
function bind19(){
 document.querySelectorAll('[data-v19-mode]').forEach(b=>b.onclick=()=>{V19.mode=b.dataset.v19Mode;V19.chunk=0;V19.showClues=false;save19();if(V19.mode==='exam'){state.view='practice';state.skill='reading'}render()});
 document.querySelector('[data-v19-clues]')?.addEventListener('click',()=>{V19.showClues=!V19.showClues;if(V19.showClues)V19.stats.clues++;save19();render()});
 document.querySelector('[data-v19-next-chunk]')?.addEventListener('click',()=>{V19.chunk++;V19.stats.chunks++;save19();render()});
 document.querySelector('[data-v19-prev-chunk]')?.addEventListener('click',()=>{V19.chunk=Math.max(0,V19.chunk-1);V19.stats.chunks++;save19();render()});
 document.querySelector('[data-v19-show-all]')?.addEventListener('click',()=>{const q=currentQuestions()[state.idx];document.querySelector('.v19-text-card p').textContent=textFor(q);V19.stats.chunks++;save19()});
 document.querySelector('[data-v19-vocab]')?.addEventListener('toggle',e=>{if(e.target.open){V19.stats.vocab++;save19()}});
 document.querySelectorAll('[data-v19-eliminate]').forEach(b=>b.onclick=e=>{e.stopPropagation();const q=currentQuestions()[state.idx],i=+b.dataset.v19Eliminate;V19.eliminated[q.id]=V19.eliminated[q.id]||[];const arr=V19.eliminated[q.id],pos=arr.indexOf(i);if(pos>=0)arr.splice(pos,1);else{arr.push(i);V19.stats.eliminations++}save19();render()});
 document.querySelector('[data-v19-start-exam]')?.addEventListener('click',startExam);
 document.querySelectorAll('[data-v19-exam-opt]').forEach(b=>b.onclick=()=>{V19.exam.answers[V19.exam.idx]={answer:+b.dataset.v19ExamOpt};save19();render()});
 document.querySelector('[data-v19-exam-next]')?.addEventListener('click',()=>{if(V19.exam.idx<31){V19.exam.idx++;save19();render()}else finishExam(false)});
}
const basePractice=practice;practice=function(){if(state.skill==='reading'){if(V19.mode==='exam')return examScreen();return learningScreen()}return basePractice()};
const baseBind=bind;bind=function(){baseBind();if(state.view==='practice'&&state.skill==='reading')bind19()};
const baseRender=render;render=function(){baseRender();requestAnimationFrame(()=>{if(state.view==='practice'&&state.skill==='reading')bind19();adultInsight()})};
window.PETQUEST_V19={state:V19,chunksFor,vocabFor,readingBank,version:'19.0'};
requestAnimationFrame(adultInsight);
})();
