// PET Quest V21 — Weekly Evolution & Explainable Readiness
(()=>{
'use strict';
const KEY='petQuestV21Weekly';
const DEFAULT={weeklyGoal:3,lastSeenWeek:'',snapshots:[],celebratedWeeks:[],version:'21.0'};
let V21;try{V21=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));V21.snapshots=V21.snapshots||[];V21.celebratedWeeks=V21.celebratedWeeks||[]}catch(_){V21=JSON.parse(JSON.stringify(DEFAULT))}
const save21=()=>{try{localStorage.setItem(KEY,JSON.stringify(V21))}catch(_){}};
const E=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kid=()=>typeof uxMode==='function'?uxMode()==='kid':document.documentElement.classList.contains('v15-kid');
const SK={reading:{icon:'📖',label:'Reading'},listening:{icon:'🎧',label:'Listening'},writing:{icon:'✍️',label:'Writing'},speaking:{icon:'🎙️',label:'Speaking'}};
function monday(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function isoDay(d){return d.toISOString().slice(0,10)}
function weekKey(d=new Date()){return isoDay(monday(d))}
function inRange(date,start,end){const t=new Date(date||0).getTime();return t>=start.getTime()&&t<end.getTime()}
function rows(skill,start,end){return (data.history||[]).filter(x=>x.skill===skill&&inRange(x.date,start,end))}
function pctRows(r){return r.length?Math.round(r.filter(x=>x.correct).length/r.length*100):null}
function drafts(start,end){const all=window.PETQUEST_V16?.state?.writing?.drafts||[];return all.filter(x=>inRange(x.updated||x.date||x.at,start,end))}
function speech(start,end){const a=window.PETQUEST_V16?.state?.speaking?.attempts||[];return a.filter(x=>inRange(x.at||x.date,start,end))}
function journeys(start,end){const h=window.PETQUEST_V20?.state?.history||[];return h.filter(x=>inRange(x.at,start,end))}
function skillCurrent(){try{return window.PETQUEST_V20?.skillSnapshot?.()||{}}catch(_){return{}}}
function weekStats(offset=0){const start=addDays(monday(),offset*7),end=addDays(start,7),current=skillCurrent();const skills={};
 ['reading','listening'].forEach(s=>{const r=rows(s,start,end);skills[s]={practice:r.length,accuracy:pctRows(r),score:current[s]?.score??(pctRows(r)??0),evidence:current[s]?.evidence??r.length}});
 const wd=drafts(start,end),sp=speech(start,end);
 skills.writing={practice:wd.length,accuracy:null,score:current.writing?.score??(wd.length?70:0),evidence:current.writing?.evidence??wd.length};
 skills.speaking={practice:sp.length+(window.PETQUEST_V17?.state?.stats?.turns||0),accuracy:null,score:current.speaking?.score??(sp.length?70:0),evidence:current.speaking?.evidence??sp.length};
 const j=journeys(start,end),answers=(data.history||[]).filter(x=>inRange(x.date,start,end));const activeDays=new Set(answers.map(x=>(x.date||'').slice(0,10)));wd.forEach(x=>activeDays.add((x.updated||x.date||'').slice(0,10)));sp.forEach(x=>activeDays.add((x.at||x.date||'').slice(0,10)));
 return{key:isoDay(start),start,end,skills,journeys:j.length,answers:answers.length,correct:answers.filter(x=>x.correct).length,accuracy:pctRows(answers),activeDays:activeDays.size,helps:j.reduce((n,x)=>n+(+x.helps||0),0),minutes:j.reduce((n,x)=>n+(+x.minutes||0),0)}
}
function trend(cur,prev){if(cur==null||prev==null)return{delta:null,dir:'new',label:'Sin comparación'};const d=cur-prev;return{delta:d,dir:d>=4?'up':d<=-4?'down':'flat',label:d>=4?`+${d} pts`:d<=-4?`${d} pts`:'estable'}}
function confidence(snap){const ev=Object.values(snap).reduce((n,x)=>n+(+x.evidence||0),0);if(ev>=45)return{level:'Alta',pct:90,copy:'Hay suficiente actividad distribuida entre habilidades.'};if(ev>=20)return{level:'Media',pct:68,copy:'La estimación ya tiene base, pero conviene seguir reuniendo evidencia.'};return{level:'Inicial',pct:42,copy:'Todavía hay poca evidencia. Úsalo como orientación, no como conclusión.'}}
function explainableReadiness(){const snap=skillCurrent();const vals=['reading','listening','writing','speaking'].map(s=>+snap[s]?.score||0);const raw=Math.round(vals.reduce((a,b)=>a+b,0)/4);const conf=confidence(snap);const adjusted=Math.round(raw*(.82+.18*conf.pct/100));const prev=weekStats(-1),cur=weekStats(0);const weeklyTrend=trend(cur.accuracy,prev.accuracy);return{raw,score:Math.max(0,Math.min(100,adjusted)),confidence:conf,snap,weeklyTrend}}
function weakestSkill(){const snap=skillCurrent();return ['reading','listening','writing','speaking'].map(s=>({skill:s,score:+snap[s]?.score||0})).sort((a,b)=>a.score-b.score)[0]}
function strongestSkill(){const snap=skillCurrent();return ['reading','listening','writing','speaking'].map(s=>({skill:s,score:+snap[s]?.score||0})).sort((a,b)=>b.score-a.score)[0]}
function weeklyGoal(){const w=weakestSkill(),cur=weekStats(0);const target=Math.max(3,Math.min(5,+V21.weeklyGoal||3));const done=cur.journeys;return{target,done,left:Math.max(0,target-done),pct:Math.min(100,Math.round(done/target*100)),focus:w.skill,focusScore:w.score}}
function nextWeekPlan(){const w=weakestSkill(),s=strongestSkill(),r=explainableReadiness();return[
 {icon:'🎯',title:`2 sesiones de ${SK[w.skill].label}`,copy:`Es la principal oportunidad actual (${w.score}%).`},
 {icon:'🌿',title:`1 sesión de ${SK[s.skill].label}`,copy:'Mantenemos una fortaleza para conservar confianza.'},
 {icon:'🧠',title:'1 bloque de reparar errores',copy:'Convierte errores repetidos en aprendizaje recuperable.'},
 {icon:'🏁',title:r.confidence.level==='Inicial'?'Reúne más evidencia antes del simulacro':'Mini comprobación al final',copy:r.confidence.level==='Inicial'?'Primero necesitamos más actividad para que la predicción sea estable.':'Comprueba autonomía después del refuerzo, no antes.'}
 ]}
function snapshotWeek(){const wk=weekKey(),s=weekStats(0),r=explainableReadiness();const snap={week:wk,at:new Date().toISOString(),readiness:r.score,confidence:r.confidence.level,accuracy:s.accuracy,activeDays:s.activeDays,journeys:s.journeys,answers:s.answers,skills:Object.fromEntries(Object.entries(r.snap).map(([k,v])=>[k,+v.score||0]))};const i=V21.snapshots.findIndex(x=>x.week===wk);if(i>=0)V21.snapshots[i]=snap;else V21.snapshots.push(snap);V21.snapshots=V21.snapshots.slice(-26);save21();return snap}
function deltaBadge(d){if(d==null)return'<span class="v21-delta neutral">nuevo</span>';return `<span class="v21-delta ${d>=4?'up':d<=-4?'down':'neutral'}">${d>0?'+':''}${d} pts</span>`}
function skillWeeklyCards(){const cur=weekStats(0),prev=weekStats(-1),snap=skillCurrent();return ['reading','listening','writing','speaking'].map(s=>{const now=+snap[s]?.score||0;const old=V21.snapshots.slice().reverse().find(x=>x.week!==weekKey())?.skills?.[s];const d=old==null?null:now-old;return `<div class="v21-skill-card"><span>${SK[s].icon} ${SK[s].label}</span><b>${now}%</b>${deltaBadge(d)}<small>${cur.skills[s].practice||0} actividades esta semana · evidencia ${snap[s]?.evidence||0}</small></div>`}).join('')}
function kidWeekly(){const main=document.querySelector('main.container');if(!main||main.querySelector('.v21-week-kid'))return;const g=weeklyGoal(),r=explainableReadiness(),cur=weekStats(0),prev=weekStats(-1),t=trend(cur.accuracy,prev.accuracy),w=weakestSkill(),s=strongestSkill();const hero=main.querySelector('.v20-journey-home')||main.firstElementChild;const html=`<section class="card v21-week-kid"><div class="v21-head"><div><span class="mission-label">V21 · Tu semana</span><h2>🌈 Mira cuánto estás creciendo</h2><p>${g.left?`Te faltan ${g.left} ruta${g.left===1?'':'s'} para cumplir tu objetivo semanal.`:'¡Objetivo semanal cumplido! Ahora toca consolidar.'}</p></div><div class="v21-week-ring"><b>${g.done}/${g.target}</b><span>rutas</span></div></div><div class="v21-goalbar"><span><i style="width:${g.pct}%"></i></span></div><div class="v21-kid-grid"><div><span>🏆 Fortaleza</span><b>${SK[s.skill].label}</b><small>${s.score}% actual</small></div><div><span>🎯 Próximo foco</span><b>${SK[w.skill].label}</b><small>${w.score}% actual</small></div><div><span>📅 Días activos</span><b>${cur.activeDays}</b><small>esta semana</small></div><div><span>🌱 Tendencia</span><b>${E(t.label)}</b><small>${cur.accuracy==null?'Aún reuniendo respuestas':cur.accuracy+'% precisión semanal'}</small></div></div><button class="btn btn-soft" data-v21-details>Ver mi progreso explicado</button></section>`;hero?.insertAdjacentHTML('afterend',html)}
function adultWeekly(){const main=document.querySelector('main.container');if(!main||main.querySelector('.v21-week-adult'))return;const r=explainableReadiness(),cur=weekStats(0),prev=weekStats(-1),t=trend(cur.accuracy,prev.accuracy),plan=nextWeekPlan();main.insertAdjacentHTML('beforeend',`<section class="card v21-week-adult"><div class="row between"><div><span class="mission-label">Weekly Evolution V21</span><h2>📈 Evolución semanal explicable</h2><p>Compara evidencia reciente y separa nivel estimado de confianza de la predicción.</p></div><div class="v21-readiness"><b>${r.score}%</b><span>PET readiness</span><small>confianza ${r.confidence.level.toLowerCase()}</small></div></div><div class="v21-explain"><div><b>Cómo se forma</b><p>Promedio de Reading, Listening, Writing y Speaking, moderado por la cantidad de evidencia disponible.</p></div><div><b>Confianza: ${r.confidence.level}</b><p>${E(r.confidence.copy)}</p></div><div><b>Tendencia semanal</b><p>${E(t.label)}${cur.accuracy!=null?' · '+cur.accuracy+'% precisión':''}</p></div></div><div class="v21-skills">${skillWeeklyCards()}</div><h3>Próxima semana</h3><div class="v21-plan-next">${plan.map(x=>`<div><span>${x.icon}</span><div><b>${E(x.title)}</b><small>${E(x.copy)}</small></div></div>`).join('')}</div><div class="row"><button class="btn btn-soft" data-v21-export>Exportar resumen CSV</button></div></section>`)}
function detailsModal(){document.querySelector('.v21-modal')?.remove();const r=explainableReadiness(),cur=weekStats(0),prev=weekStats(-1),w=weakestSkill(),s=strongestSkill();document.body.insertAdjacentHTML('beforeend',`<div class="v21-modal"><div class="v21-modal-card"><button class="v21-close" data-v21-close aria-label="Cerrar">×</button><span class="mission-label">Tu progreso explicado</span><h2>🌱 No es solo una nota</h2><p>PET Quest mira las cuatro habilidades y también cuánta práctica existe antes de estimar tu preparación.</p><div class="v21-skills">${skillWeeklyCards()}</div><div class="notice"><b>Hoy:</b> ${r.score}% de preparación estimada · confianza ${r.confidence.level.toLowerCase()}.</div><p><b>Lo que mejor va:</b> ${SK[s.skill].label} (${s.score}%).</p><p><b>Lo que practicaremos más:</b> ${SK[w.skill].label} (${w.score}%).</p><p><b>Esta semana:</b> ${cur.activeDays} días activos, ${cur.answers} respuestas y ${cur.journeys} rutas completas.</p><p class="small">Esto es una estimación pedagógica interna, no un resultado oficial de Cambridge.</p></div></div>`);document.querySelector('[data-v21-close]')?.addEventListener('click',()=>document.querySelector('.v21-modal')?.remove())}
function exportCSV(){const cur=weekStats(0),r=explainableReadiness(),snap=r.snap;const rows=[['week','readiness','confidence','active_days','journeys','answers','accuracy','reading','listening','writing','speaking'],[cur.key,r.score,r.confidence.level,cur.activeDays,cur.journeys,cur.answers,cur.accuracy??'',...['reading','listening','writing','speaking'].map(s=>snap[s]?.score??'')]];const csv=rows.map(x=>x.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`petquest_week_${cur.key}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bind21(){document.querySelector('[data-v21-details]')?.addEventListener('click',detailsModal);document.querySelector('[data-v21-export]')?.addEventListener('click',exportCSV)}
function maybeSnapshot(){const wk=weekKey();if(V21.lastSeenWeek!==wk){V21.lastSeenWeek=wk;save21()}snapshotWeek()}
const before=render;render=function(){before();requestAnimationFrame(()=>{if(state.view==='home'){kid()?kidWeekly():adultWeekly()}bind21();maybeSnapshot()})};
window.PETQUEST_V21={state:V21,weekStats,explainableReadiness,weeklyGoal,nextWeekPlan,snapshotWeek,weekKey,version:'21.0'};
requestAnimationFrame(()=>{if(state.view==='home'){kid()?kidWeekly():adultWeekly()}bind21();maybeSnapshot()});
})();
