// PET Quest V22 — Parent & Teacher Intelligence Center
(()=>{
'use strict';
const KEY='petQuestV22AdultIntelligence';
const DEFAULT={weeklyAdultGoal:1,lastViewed:'',notes:[],version:'22.0'};
let V22;try{V22=Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'));V22.notes=V22.notes||[]}catch(_){V22=JSON.parse(JSON.stringify(DEFAULT))}
const save22=()=>{try{localStorage.setItem(KEY,JSON.stringify(V22))}catch(_){}};
const E=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const adult=()=>typeof uxMode==='function'?uxMode()==='adult':!document.documentElement.classList.contains('v15-kid');
const SK={reading:{icon:'📖',label:'Reading'},listening:{icon:'🎧',label:'Listening'},writing:{icon:'✍️',label:'Writing'},speaking:{icon:'🎙️',label:'Speaking'}};
function monday(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function inRange(date,start,end){const t=new Date(date||0).getTime();return t>=start.getTime()&&t<end.getTime()}
function rowsFor(start,end){return (data.history||[]).filter(x=>inRange(x.date,start,end))}
function pct(rows){return rows.length?Math.round(rows.filter(x=>x.correct).length/rows.length*100):null}
function journeysFor(start,end){return (window.PETQUEST_V20?.state?.history||[]).filter(x=>inRange(x.at,start,end))}
function currentSkills(){try{return window.PETQUEST_V20?.skillSnapshot?.()||{}}catch(_){return{}}}
function skillRows(rows,skill){return rows.filter(x=>x.skill===skill)}
function focusStats(rows){const m={};rows.forEach(x=>{const f=String(x.focus||'general').trim()||'general';m[f]??={n:0,ok:0};m[f].n++;if(x.correct)m[f].ok++});return Object.entries(m).map(([focus,v])=>({focus,n:v.n,pct:Math.round(v.ok/v.n*100)})).sort((a,b)=>a.pct-b.pct||b.n-a.n)}
function evidenceScore(skills){return Object.values(skills).reduce((n,x)=>n+(+x.evidence||0),0)}
function week(offset=0){const start=addDays(monday(),offset*7),end=addDays(start,7),rows=rowsFor(start,end),journeys=journeysFor(start,end),skills=currentSkills();const active=new Set(rows.map(x=>String(x.date||'').slice(0,10)));journeys.forEach(x=>active.add(String(x.at||'').slice(0,10)));return{start,end,rows,journeys,skills,answers:rows.length,accuracy:pct(rows),activeDays:active.size,minutes:journeys.reduce((n,x)=>n+(+x.minutes||0),0),helps:journeys.reduce((n,x)=>n+(+x.helps||0),0),journeyAnswers:journeys.reduce((n,x)=>n+(+x.answers||0),0)}}
function skillRank(){const s=currentSkills();return Object.keys(SK).map(k=>({skill:k,score:+s[k]?.score||0,evidence:+s[k]?.evidence||0})).sort((a,b)=>a.score-b.score)}
function readiness(){try{return window.PETQUEST_V21?.explainableReadiness?.()||null}catch(_){return null}}
function autonomy(cur){const denom=Math.max(1,cur.journeyAnswers||cur.answers);const helpRate=cur.helps/denom;let score=Math.round(100-Math.min(75,helpRate*100));if(cur.answers<4)score=Math.min(score,65);const level=score>=82?'Alta':score>=62?'En desarrollo':'Necesita acompañamiento';return{score,level,helpRate,copy:score>=82?'Resuelve la mayoría de actividades con poca ayuda.':score>=62?'Alterna intentos independientes con apoyo de Milo.':'Esta semana necesitó apoyo frecuente; conviene acompañar sin dar respuestas.'}}
function learningStory(){const cur=week(0),prev=week(-1),rank=skillRank(),weak=rank[0],strong=rank[rank.length-1],a=autonomy(cur);const curFocus=focusStats(cur.rows),prevFocus=focusStats(prev.rows);let overcome=null;
 for(const p of prevFocus){const n=curFocus.find(x=>x.focus===p.focus);if(p.n>=2&&p.pct<70&&n&&n.n>=2&&n.pct-p.pct>=15){overcome={focus:p.focus,before:p.pct,now:n.pct,delta:n.pct-p.pct};break}}
 const pending=curFocus.find(x=>x.n>=2&&x.pct<75)||curFocus[0]||null;
 const accDelta=cur.accuracy!=null&&prev.accuracy!=null?cur.accuracy-prev.accuracy:null;
 return{cur,prev,weak,strong,autonomy:a,overcome,pending,accDelta};
}
function adultActions(story){const a=[];const w=story.weak,s=story.strong,p=story.pending,auto=story.autonomy;
 a.push({icon:'🎯',title:`Haz 2 sesiones cortas de ${SK[w.skill].label}`,copy:`Es la oportunidad principal actual (${w.score}%). Mantén sesiones breves y termina antes de que aparezca fatiga.`});
 if(p)a.push({icon:'🧠',title:`Pregunta por “${p.focus}”`,copy:`En vez de explicar la respuesta, pide al niño que te muestre la pista que encontró. Precisión reciente: ${p.pct}%.`});
 if(auto.score<82)a.push({icon:'🌿',title:'Celebra un intento sin ayuda',copy:'Esta semana conviene reforzar autonomía. Reconoce el proceso aunque la respuesta no sea perfecta.'});
 else a.push({icon:'🏆',title:`Mantén ${SK[s.skill].label} como fortaleza`,copy:'Una misión ligera de mantenimiento conserva confianza sin quitar tiempo al foco prioritario.'});
 a.push({icon:'💬',title:'Haz una pregunta, no una clase',copy:'Pregunta “¿qué fue más fácil hoy?” o “¿qué pista te ayudó?”. Evita corregir cada error fuera de la app.'});
 return a.slice(0,4)
}
function statusPill(label,type='neutral'){return `<span class="v22-pill ${type}">${E(label)}</span>`}
function summaryCards(st){const trend=st.accDelta==null?'Sin comparación':st.accDelta>3?`+${st.accDelta} pts`:st.accDelta<-3?`${st.accDelta} pts`:'Estable';return `<div class="v22-summary-grid"><div><span>⏱ Estudió</span><b>${st.cur.minutes||0} min</b><small>${st.cur.activeDays} días activos</small></div><div><span>✅ Respondió</span><b>${st.cur.answers}</b><small>${st.cur.accuracy==null?'Aún sin precisión':st.cur.accuracy+'% precisión'}</small></div><div><span>🌱 Evolución</span><b>${E(trend)}</b><small>vs. semana anterior</small></div><div><span>🧭 Autonomía</span><b>${st.autonomy.score}%</b><small>${E(st.autonomy.level)}</small></div></div>`}
function skillGrid(st){const snap=currentSkills();return `<div class="v22-skill-grid">${Object.keys(SK).map(k=>{const v=snap[k]||{};let tag='Mantener',t='neutral';if(k===st.weak.skill){tag='Prioridad';t='warn'}else if(k===st.strong.skill){tag='Fortaleza';t='good'}return `<div><div class="row between"><span>${SK[k].icon} ${SK[k].label}</span>${statusPill(tag,t)}</div><b>${+v.score||0}%</b><small>evidencia ${+v.evidence||0}</small><span class="v22-meter"><i style="width:${Math.max(0,Math.min(100,+v.score||0))}%"></i></span></div>`}).join('')}</div>`}
function insightBlocks(st){const improved=st.overcome?`Superó <b>${E(st.overcome.focus)}</b>: pasó de ${st.overcome.before}% a ${st.overcome.now}%.`:(st.accDelta!=null&&st.accDelta>=4?`La precisión semanal subió <b>${st.accDelta} puntos</b>.`:'Aún no hay evidencia suficiente de un error superado; sigue observando la próxima semana.');const pending=st.pending?`<b>${E(st.pending.focus)}</b> sigue siendo un foco de trabajo (${st.pending.pct}% en ${st.pending.n} intentos).`:`La principal oportunidad general es <b>${SK[st.weak.skill].label}</b> (${st.weak.score}%).`;
 return `<div class="v22-questions"><article><span>1</span><div><b>¿Qué hizo?</b><p>${st.cur.journeys} rutas · ${st.cur.answers} respuestas · ${st.cur.minutes||0} min · ${st.cur.activeDays} días.</p></div></article><article><span>2</span><div><b>¿Qué aprendió?</b><p>${SK[st.strong.skill].label} es su fortaleza actual (${st.strong.score}%).</p></div></article><article><span>3</span><div><b>¿Qué superó?</b><p>${improved}</p></div></article><article><span>4</span><div><b>¿Qué sigue pendiente?</b><p>${pending}</p></div></article><article><span>5</span><div><b>¿Cuánta ayuda necesitó?</b><p>${st.autonomy.copy} ${st.cur.helps} ayudas registradas en rutas esta semana.</p></div></article></div>`}
function renderCenter(){if(!adult()||state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v22-intelligence'))return;const st=learningStory(),r=readiness(),actions=adultActions(st);const target=main.querySelector('.v21-week-adult')||main.lastElementChild;const html=`<section class="card v22-intelligence"><div class="v22-head"><div><span class="mission-label">V22 · Parent & Teacher Intelligence Center</span><h2>🧭 Qué pasó y qué hacer ahora</h2><p>Una lectura accionable de aprendizaje, autonomía y próximo acompañamiento. Sin diagnósticos emocionales.</p></div><div class="v22-readiness"><b>${r?.score??Math.round((st.weak.score+st.strong.score)/2)}%</b><span>preparación estimada</span><small>${r?.confidence?.level?'confianza '+r.confidence.level.toLowerCase():'evidencia en crecimiento'}</small></div></div>${summaryCards(st)}${insightBlocks(st)}<h3>Mapa de habilidades</h3>${skillGrid(st)}<div class="v22-autonomy"><div><span>🌿 Autonomía esta semana</span><b>${st.autonomy.score}% · ${E(st.autonomy.level)}</b><p>${E(st.autonomy.copy)}</p></div><span class="v22-autonomy-ring" style="--p:${st.autonomy.score}"><i>${st.autonomy.score}%</i></span></div><h3>Qué puede hacer el adulto esta semana</h3><div class="v22-actions">${actions.map(x=>`<article><span>${x.icon}</span><div><b>${E(x.title)}</b><p>${E(x.copy)}</p></div></article>`).join('')}</div><div class="v22-footer"><div><b>Regla de acompañamiento:</b><span> guía el proceso, no resuelvas por él.</span></div><div class="row"><button class="btn btn-soft" data-v22-copy>Copiar resumen</button><button class="btn btn-soft" data-v22-export>Exportar CSV</button></div></div></section>`;
 target?.insertAdjacentHTML('afterend',html);V22.lastViewed=new Date().toISOString();save22();
}
function plainSummary(){const st=learningStory(),r=readiness();return [`PET Quest — resumen semanal`, `Preparación estimada: ${r?.score??'—'}%${r?.confidence?.level?' · confianza '+r.confidence.level:''}`, `Actividad: ${st.cur.answers} respuestas · ${st.cur.minutes||0} min · ${st.cur.activeDays} días`, `Precisión: ${st.cur.accuracy??'—'}%`, `Fortaleza: ${SK[st.strong.skill].label} ${st.strong.score}%`, `Prioridad: ${SK[st.weak.skill].label} ${st.weak.score}%`, `Autonomía: ${st.autonomy.score}% · ${st.autonomy.level}`, st.overcome?`Superó: ${st.overcome.focus} (${st.overcome.before}% → ${st.overcome.now}%)`:'Error superado: evidencia insuficiente', st.pending?`Pendiente: ${st.pending.focus} ${st.pending.pct}%`:'Pendiente: reforzar '+SK[st.weak.skill].label].join('\n')}
function exportCSV(){const st=learningStory(),r=readiness(),rows=[['metric','value'],['readiness',r?.score??''],['confidence',r?.confidence?.level??''],['answers',st.cur.answers],['minutes',st.cur.minutes],['active_days',st.cur.activeDays],['accuracy',st.cur.accuracy??''],['autonomy',st.autonomy.score],['helps',st.cur.helps],['strong_skill',st.strong.skill],['strong_score',st.strong.score],['weak_skill',st.weak.skill],['weak_score',st.weak.score],['overcome_focus',st.overcome?.focus||''],['pending_focus',st.pending?.focus||'']];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='petquest_adult_intelligence.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bind22(){document.querySelector('[data-v22-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(plainSummary());typeof toast==='function'&&toast('Resumen copiado')}catch(_){prompt('Copia este resumen:',plainSummary())}});document.querySelector('[data-v22-export]')?.addEventListener('click',exportCSV)}
const priorRender=render;render=function(){priorRender();requestAnimationFrame(()=>{renderCenter();bind22()})};
window.PETQUEST_V22={state:V22,week,learningStory,adultActions,autonomy,plainSummary,version:'22.0'};
requestAnimationFrame(()=>{renderCenter();bind22()});
})();
