// PET Quest V24 — Learning Portfolio: visible evidence of growth for child and adult.
(()=>{
'use strict';
const KEY='petQuestV24Portfolio';
const DEF={masteredWords:[],featuredWriting:null,featuredSpeaking:null,lastOpened:null,version:'24.0'};
let V24;try{V24=Object.assign({},DEF,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){V24={...DEF}}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(V24))}catch(_){}};
const E=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kid=()=>typeof uxMode==='function'?uxMode()==='kid':document.documentElement.classList.contains('v15-kid');
const getStore=(k,d={})=>{try{return Object.assign({},d,JSON.parse(localStorage.getItem(k)||'{}'))}catch(_){return d}};
const v11=()=>getStore('petQuestV11Ux',{stars:0,chests:0,completedMissions:0,avatar:'owl'});
const v12=()=>getStore('petQuestV12Ux',{badges:[],stickers:0});
const v16=()=>getStore('petquest_v16_learning',{speaking:{attempts:[]},writing:{drafts:[]}});
function writingItems(){return (v16().writing?.drafts||[]).filter(d=>(d.final||d.paragraph||'').trim()).map((d,i)=>({id:i,text:(d.final||d.paragraph||'').trim(),score:+d.score||0,at:d.updated||'',words:(d.final||d.paragraph||'').trim().split(/\s+/).filter(Boolean).length})).sort((a,b)=>b.score-a.score||String(b.at).localeCompare(String(a.at)))}
function speakingItems(){return (v16().speaking?.attempts||[]).filter(a=>a.text||a.recognized).map((a,i)=>({id:i,text:a.text||a.recognized||'',score:+a.score||0,at:a.at||'',part:a.part||'',words:+a.words||String(a.text||a.recognized||'').trim().split(/\s+/).filter(Boolean).length})).sort((a,b)=>b.score-a.score||String(b.at).localeCompare(String(a.at)))}
function bestWriting(){const a=writingItems();return a.find(x=>x.id===V24.featuredWriting)||a[0]||null}
function bestSpeaking(){const a=speakingItems();return a.find(x=>x.id===V24.featuredSpeaking)||a[0]||null}
function badgeInfo(){const b=v12().badges||[];return {count:b.length,ids:b,stickers:+v12().stickers||0}}
function worlds(){const r=typeof readiness==='function'?readiness():0;return [
 {icon:'📖',name:'Bosque de Historias',done:true},
 {icon:'🎧',name:'Bahía de Sonidos',done:true},
 {icon:'✍️',name:'Taller de Ideas',done:r>=20||writingItems().length>0},
 {icon:'🎙️',name:'Isla de la Voz',done:r>=35||speakingItems().length>0},
 {icon:'🏰',name:'Castillo PET',done:r>=50||(data?.mockAttempts||[]).length>0}
]}
function timeline(){const items=[];
 (data?.history||[]).filter(x=>x.correct).slice(-40).forEach(x=>items.push({at:x.date||'',icon:x.skill==='reading'?'📖':x.skill==='listening'?'🎧':'⭐',title:x.skill==='reading'?'Pista de Reading superada':'Escucha comprendida',sub:x.focus||'práctica'}));
 writingItems().forEach(x=>items.push({at:x.at,icon:'✍️',title:'Writing guardado',sub:`${x.words} palabras · ${x.score||'—'}%`}));
 speakingItems().slice(0,12).forEach(x=>items.push({at:x.at,icon:'🎙️',title:'Speaking practicado',sub:`${x.score||'—'}% · parte ${x.part||'—'}`}));
 (data?.mockAttempts||[]).forEach(x=>items.push({at:x.date||x.at||'',icon:'🏰',title:'Simulacro completado',sub:`${x.skill||'PET'} · ${x.score??x.percent??'—'}%`}));
 V24.masteredWords.forEach(x=>items.push({at:x.at,icon:'🧠',title:'Palabra dominada',sub:x.term}));
 return items.filter(x=>x.at).sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,14)
}
function stats(){const h=data?.history||[],correct=h.filter(x=>x.correct).length,w=writingItems(),s=speakingItems(),b=badgeInfo(),wd=worlds();return{answers:h.length,correct,precision:h.length?Math.round(correct/h.length*100):0,writings:w.length,speaking:s.length,mastered:V24.masteredWords.length,badges:b.count,stickers:b.stickers,worlds:wd.filter(x=>x.done).length,stars:+v11().stars||0}}
function kidCard(){const st=stats(),bw=bestWriting(),bs=bestSpeaking();return `<section class="card v24-home v24-kid"><div class="v24-cover"><img src="assets/portfolio.svg" alt="Portafolio de aprendizaje"><div><span class="mission-label">V24 · Mi portafolio</span><h2>✨ Mira todo lo que ya puedes hacer</h2><p>Tus mejores trabajos, palabras, insignias y aventuras quedan aquí.</p><button class="btn btn-primary" data-v24-open>📒 Abrir mi portafolio</button></div></div><div class="v24-mini"><div><b>${st.worlds}/5</b><span>mundos</span></div><div><b>${st.badges}</b><span>insignias</span></div><div><b>${st.mastered}</b><span>palabras dominadas</span></div><div><b>${Math.max(bw?.score||0,bs?.score||0)}%</b><span>trabajo destacado</span></div></div></section>`}
function adultCard(){const st=stats();return `<section class="card v24-home v24-adult"><div class="section-title"><div><span class="mission-label">V24 · Evidencia de aprendizaje</span><h2>📒 Learning Portfolio</h2><p>Trabajos y hitos concretos, no solo promedios.</p></div><button class="btn btn-primary" data-v24-open>Ver portafolio completo</button></div><div class="v24-adult-stats"><div><b>${st.writings}</b><span>Writing guardados</span></div><div><b>${st.speaking}</b><span>evidencias Speaking</span></div><div><b>${st.mastered}</b><span>palabras dominadas</span></div><div><b>${st.precision}%</b><span>precisión histórica</span></div></div></section>`}
function evidenceHtml(){const bw=bestWriting(),bs=bestSpeaking();return `<div class="v24-evidence-grid"><article class="v24-evidence"><div class="v24-evidence-head"><span>✍️</span><div><b>Mi Writing destacado</b><small>${bw?`${bw.score||'—'}% · ${bw.words} palabras`:'Aún no hay un texto guardado'}</small></div></div>${bw?`<blockquote>${E(bw.text.slice(0,520))}${bw.text.length>520?'…':''}</blockquote>`:'<p>Completa un Writing Builder y aparecerá aquí.</p>'}</article><article class="v24-evidence"><div class="v24-evidence-head"><span>🎙️</span><div><b>Mi Speaking destacado</b><small>${bs?`${bs.score||'—'}% · parte ${bs.part||'—'}`:'Aún no hay una respuesta guardada'}</small></div></div>${bs?`<blockquote>${E(bs.text.slice(0,420))}${bs.text.length>420?'…':''}</blockquote>`:'<p>Practica una respuesta oral y aparecerá aquí.</p>'}</article></div>`}
function modal(){document.querySelector('.v24-modal')?.remove();V24.lastOpened=new Date().toISOString();save();const st=stats(),b=badgeInfo(),tl=timeline(),wd=worlds();document.body.insertAdjacentHTML('beforeend',`<div class="v24-modal" role="dialog" aria-modal="true" aria-label="Learning Portfolio"><div class="v24-modal-card"><div class="v24-modal-head"><div><span class="mission-label">Mi crecimiento</span><h2>${kid()?'🌈 Todo lo que estoy aprendiendo':'📒 Evidencias del progreso'}</h2><p>${kid()?'No compites con nadie. Este portafolio muestra tu propio camino.':'Trabajos, dominio, logros y cronología de aprendizaje del estudiante.'}</p></div><button class="btn btn-ghost" data-v24-close>✕ Cerrar</button></div><div class="v24-summary"><div><b>${st.answers}</b><span>actividades</span></div><div><b>${st.precision}%</b><span>precisión</span></div><div><b>${st.stars}</b><span>estrellas</span></div><div><b>${st.badges}</b><span>insignias</span></div><div><b>${st.mastered}</b><span>palabras dominadas</span></div></div><section><h3>🗺️ Mis mundos</h3><div class="v24-worlds">${wd.map(x=>`<div class="${x.done?'done':''}"><span>${x.icon}</span><b>${E(x.name)}</b><small>${x.done?'Explorado':'Siguiente aventura'}</small></div>`).join('')}</div></section><section><h3>🌟 Mis mejores evidencias</h3>${evidenceHtml()}</section><section><h3>🏅 Mi colección</h3><div class="v24-badges">${b.ids.length?b.ids.map(id=>`<span title="${E(id)}">🏅</span>`).join(''):'<p class="muted">Las insignias aparecerán a medida que avances.</p>'}<div class="v24-sticker">🎟️ <b>${b.stickers}</b> stickers</div></div></section><section><h3>🧠 Palabras que ya dominé</h3><div class="v24-words">${V24.masteredWords.length?V24.masteredWords.slice(-16).reverse().map(x=>`<span>${E(x.term)}</span>`).join(''):'<p class="muted">Cuando marques una palabra como dominada, quedará guardada aquí.</p>'}</div></section><section><h3>🕒 Mi línea de crecimiento</h3><div class="v24-timeline">${tl.length?tl.map(x=>`<div><span>${x.icon}</span><div><b>${E(x.title)}</b><small>${E(x.sub)} · ${new Date(x.at).toLocaleDateString()}</small></div></div>`).join(''):'<p class="muted">Completa actividades para construir tu historia.</p>'}</div></section>${kid()?'':`<div class="row"><button class="btn btn-soft" data-v24-copy>Copiar resumen</button><button class="btn btn-soft" data-v24-csv>Exportar CSV</button></div>`}</div></div>`);bindModal()}
function summaryText(){const st=stats(),bw=bestWriting(),bs=bestSpeaking();return `PET Quest — Learning Portfolio\nActividades: ${st.answers}\nPrecisión: ${st.precision}%\nMundos: ${st.worlds}/5\nInsignias: ${st.badges}\nPalabras dominadas: ${st.mastered}\nWriting destacado: ${bw?`${bw.score||'—'}% · ${bw.words} palabras`:'sin evidencia'}\nSpeaking destacado: ${bs?`${bs.score||'—'}% · parte ${bs.part||'—'}`:'sin evidencia'}`}
function exportCsv(){const rows=[['type','date','title','detail'],...timeline().map(x=>['timeline',x.at,x.title,x.sub]),...V24.masteredWords.map(x=>['mastered_word',x.at,x.term,'mastered'])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='petquest_learning_portfolio.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bindModal(){document.querySelector('[data-v24-close]')?.addEventListener('click',()=>document.querySelector('.v24-modal')?.remove());document.querySelector('[data-v24-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(summaryText());window.toast?.('Resumen copiado')}catch(_){}});document.querySelector('[data-v24-csv]')?.addEventListener('click',exportCsv)}
function captureMastered(){document.addEventListener('click',e=>{const b=e.target.closest?.('[data-master-word]');if(!b)return;const term=b.dataset.masterWord;if(term&&!V24.masteredWords.some(x=>x.term===term)){V24.masteredWords.push({term,at:new Date().toISOString()});save()}},true)}
function render24(){if(state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v24-home'))return;const anchor=main.querySelector('.v23-kid,.v23-adult')||main.querySelector('.v22-intelligence')||main.firstElementChild;anchor?.insertAdjacentHTML('afterend',kid()?kidCard():adultCard());document.querySelector('[data-v24-open]')?.addEventListener('click',modal)}
const css=`
.v24-home{margin-top:16px}.v24-cover{display:grid;grid-template-columns:180px 1fr;gap:20px;align-items:center}.v24-cover img{width:100%;max-height:150px}.v24-cover h2{margin:.25rem 0}.v24-mini,.v24-adult-stats,.v24-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:14px}.v24-mini div,.v24-adult-stats div,.v24-summary div{padding:10px;border-radius:14px;background:#f7f7fb;text-align:center}.v24-mini b,.v24-adult-stats b,.v24-summary b{display:block;font-size:1.3rem}.v24-mini span,.v24-adult-stats span,.v24-summary span{font-size:.76rem}.v24-modal{position:fixed;inset:0;background:rgba(28,30,48,.58);z-index:10020;display:flex;align-items:flex-start;justify-content:center;padding:24px;overflow:auto}.v24-modal-card{background:#fff;width:min(1050px,100%);border-radius:24px;padding:22px;box-shadow:0 24px 80px rgba(0,0,0,.25)}.v24-modal-head{display:flex;justify-content:space-between;gap:16px}.v24-modal-head h2{margin:.25rem 0}.v24-summary{grid-template-columns:repeat(5,1fr)}.v24-modal-card section{margin-top:22px}.v24-worlds{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.v24-worlds div{padding:12px;border-radius:16px;background:#f3f3f7;display:flex;flex-direction:column;align-items:center;text-align:center;opacity:.62}.v24-worlds div.done{background:#eaf8ef;opacity:1}.v24-worlds span{font-size:1.8rem}.v24-worlds small{font-size:.72rem}.v24-evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.v24-evidence{border:1px solid rgba(70,70,120,.13);border-radius:18px;padding:14px}.v24-evidence-head{display:flex;gap:10px;align-items:center}.v24-evidence-head>span{font-size:2rem}.v24-evidence-head small{display:block}.v24-evidence blockquote{margin:12px 0 0;padding:12px;border-left:4px solid #7777df;background:#f8f8fc;border-radius:0 12px 12px 0;white-space:pre-wrap}.v24-badges,.v24-words{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.v24-badges>span{font-size:1.7rem}.v24-sticker,.v24-words>span{padding:7px 10px;border-radius:999px;background:#f2f2f7}.v24-timeline{display:grid;gap:8px}.v24-timeline>div{display:flex;gap:10px;align-items:center;padding:10px;border-radius:14px;background:#f8f8fb}.v24-timeline>div>span{font-size:1.5rem}.v24-timeline small{display:block}.v24-adult-stats{margin:0}.v24-adult .section-title{align-items:center}@media(max-width:720px){.v24-cover{grid-template-columns:1fr}.v24-cover img{max-height:120px}.v24-mini,.v24-adult-stats,.v24-summary{grid-template-columns:repeat(2,1fr)}.v24-worlds{grid-template-columns:repeat(2,1fr)}.v24-evidence-grid{grid-template-columns:1fr}.v24-modal{padding:10px}.v24-modal-card{padding:15px;border-radius:18px}.v24-modal-head{flex-direction:column}.v24-modal-head .btn{align-self:flex-end}}
`;
if(!document.getElementById('v24-css')){const st=document.createElement('style');st.id='v24-css';st.textContent=css;document.head.appendChild(st)}
captureMastered();
const prior=render;render=function(){prior();requestAnimationFrame(render24)};
window.PETQUEST_V24={state:V24,stats,timeline,writingItems,speakingItems,version:'24.0'};
requestAnimationFrame(render24);
})();
