// PET Quest V25 — Personal Learning Path: flexible preferences, milestones and future roadmap.
(()=>{
'use strict';
const KEY='petQuestV25PersonalPath';
const DEF={preference:'mixed',goal:'balanced',weeklyMinutes:40,lastReview:null,version:'25.0'};
let V25;try{V25=Object.assign({},DEF,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){V25={...DEF}}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(V25))}catch(_){}};
const E=s=>typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kid=()=>typeof uxMode==='function'?uxMode()==='kid':document.documentElement.classList.contains('v15-kid');
const meta={reading:{icon:'📖',label:'Reading'},listening:{icon:'🎧',label:'Listening'},writing:{icon:'✍️',label:'Writing'},speaking:{icon:'🎙️',label:'Speaking'}};
function snapshots(){try{if(window.PETQUEST_V20?.skillSnapshot)return window.PETQUEST_V20.skillSnapshot()}catch(_){};return{reading:{score:50,evidence:0},listening:{score:50,evidence:0},writing:{score:50,evidence:0},speaking:{score:50,evidence:0}}}
function rank(){return Object.entries(snapshots()).map(([skill,x])=>({skill,score:Math.round(+x.score||0),evidence:+x.evidence||0})).sort((a,b)=>a.score-b.score)}
function supportProfile(){let h={};try{h=JSON.parse(localStorage.getItem('petQuestV14Tutor')||'{}')}catch(_){};const uses=h.helpUses||h.analytics?.helpUses||{};const total=Object.values(uses).reduce((s,x)=>s+(+x||0),0);let observed='mixed';if(total){const top=Object.entries(uses).sort((a,b)=>(+b[1]||0)-(+a[1]||0))[0]?.[0]||'';observed=/example|similar/.test(top)?'practice':/easy|understand/.test(top)?'visual':/hint/.test(top)?'mixed':'mixed'}return{uses,total,observed}}
function preference(){const map={mixed:{icon:'🧭',label:'Mezcla inteligente',desc:'Combina imágenes, audio, práctica y explicación.'},visual:{icon:'🖼️',label:'Más visual',desc:'Prioriza escenas, fragmentos y pasos visibles.'},audio:{icon:'🎧',label:'Más audio',desc:'Incluye escucha y repetición con mayor frecuencia.'},practice:{icon:'🧩',label:'Aprender haciendo',desc:'Prioriza mini prácticas y producción activa.'}};return map[V25.preference]||map.mixed}
function recommendedPace(){const arr=rank(),avg=Math.round(arr.reduce((s,x)=>s+x.score,0)/4),ev=arr.reduce((s,x)=>s+x.evidence,0);if(ev<12)return{minutes:30,label:'Suave',reason:'Primero reunimos evidencia con sesiones cortas.'};if(avg<65)return{minutes:45,label:'Guiado',reason:'Conviene practicar con frecuencia y apoyo.'};if(avg<80)return{minutes:55,label:'Equilibrado',reason:'Buen ritmo para consolidar y avanzar.'};return{minutes:45,label:'Consolidación',reason:'Menos volumen y más calidad/simulacros.'}}
function milestone(skill,score){const stages=[{min:0,max:54,label:'Construir base',icon:'🌱',next:'Comprender instrucciones y responder con apoyo.'},{min:55,max:69,label:'Ganar seguridad',icon:'🧭',next:'Resolver tareas B1 con menos pistas.'},{min:70,max:82,label:'Consolidar B1',icon:'⭐',next:'Mantener precisión y autonomía.'},{min:83,max:91,label:'Preparar examen',icon:'🏁',next:'Practicar a tiempo y sin ayudas.'},{min:92,max:100,label:'Mantener dominio',icon:'🏆',next:'Conservar el nivel con práctica variada.'}];const s=stages.find(x=>score>=x.min&&score<=x.max)||stages[0];return{skill,score,...s}}
function roadmap(){const r=rank(),weak=r[0],strong=r[r.length-1],items=r.map(x=>milestone(x.skill,x.score));return{items,weak,strong,readiness:Math.round(r.reduce((s,x)=>s+x.score,0)/4)}}
function nextGoals(){const rm=roadmap(),pref=preference(),pace=recommendedPace(),goals=[];goals.push({icon:meta[rm.weak.skill].icon,title:`Subir ${meta[rm.weak.skill].label} a ${Math.min(100,rm.weak.score+8)}%`,why:`Es la principal oportunidad actual (${rm.weak.score}%).`});if(rm.weak.evidence<5)goals.push({icon:'🔎',title:'Reunir más evidencia',why:'Necesitamos más actividades antes de aumentar dificultad.'});else goals.push({icon:'🧠',title:'Reducir ayudas gradualmente',why:'La autonomía confirma que el aprendizaje se sostiene.'});goals.push({icon:pref.icon,title:`Usar ${pref.label.toLowerCase()}`,why:pref.desc});goals.push({icon:'⏱️',title:`Meta semanal: ${V25.weeklyMinutes||pace.minutes} min`,why:'En sesiones cortas repartidas, sin acumular deuda.'});return goals.slice(0,4)}
function pathHtml(){const rm=roadmap();return `<div class="v25-roadmap">${rm.items.map((x,i)=>`<article class="v25-stage ${i===0?'priority':''}"><div class="v25-stage-icon">${meta[x.skill].icon}</div><div><small>${E(meta[x.skill].label)}</small><b>${x.score}% · ${E(x.label)}</b><p>${E(x.next)}</p></div><span class="v25-stage-num">${i+1}</span></article>`).join('')}<article class="v25-stage goal"><div class="v25-stage-icon">🏰</div><div><small>Meta</small><b>Castillo PET</b><p>Demostrar las cuatro habilidades con autonomía y tiempo de examen.</p></div><span class="v25-stage-num">★</span></article></div>`}
function kidCard(){const rm=roadmap(),p=preference();return `<section class="card v25-home"><div class="v25-hero"><img src="assets/roadmap.svg" alt="Mapa futuro hacia PET"><div><span class="mission-label">V25 · Mi camino personal</span><h2>🗺️ Mira qué viene después</h2><p>Milo usa tu progreso para elegir el próximo paso. Tu camino puede cambiar cuando tú cambias.</p><div class="v25-pills"><span>${meta[rm.weak.skill].icon} Próximo foco: <b>${meta[rm.weak.skill].label}</b></span><span>${p.icon} Preferencia: <b>${p.label}</b></span></div><button class="btn btn-primary" data-v25-open>Ver mi mapa futuro</button></div></div></section>`}
function adultCard(){const rm=roadmap(),pace=recommendedPace();return `<section class="card v25-home v25-adult"><div class="section-title"><div><span class="mission-label">V25 · Personal Learning Path</span><h2>🧭 Ruta personalizada y explicable</h2><p>Fortalezas, prioridad, preferencia flexible, ritmo y próximos hitos.</p></div><button class="btn btn-primary" data-v25-open>Ver ruta completa</button></div><div class="v25-stats"><div><b>${rm.readiness}%</b><span>promedio 4 habilidades</span></div><div><b>${meta[rm.weak.skill].label}</b><span>prioridad</span></div><div><b>${meta[rm.strong.skill].label}</b><span>fortaleza</span></div><div><b>${pace.minutes} min</b><span>ritmo semanal sugerido</span></div></div></section>`}
function modal(){document.querySelector('.v25-modal')?.remove();V25.lastReview=new Date().toISOString();save();const rm=roadmap(),p=preference(),pace=recommendedPace(),sp=supportProfile(),goals=nextGoals();document.body.insertAdjacentHTML('beforeend',`<div class="v25-modal" role="dialog" aria-modal="true" aria-label="Ruta personalizada"><div class="v25-modal-card"><header class="v25-modal-head"><div><span class="mission-label">${kid()?'Mi próximo camino':'Personal Learning Path'}</span><h2>🧭 ${kid()?'Así voy a llegar al Castillo PET':'Ruta futura explicable'}</h2><p>${kid()?'No tienes que hacerlo todo hoy. Vamos un paso a la vez.':'La ruta combina desempeño, evidencia y preferencias flexibles; no usa etiquetas fijas de “estilo de aprendizaje”.'}</p></div><button class="btn btn-ghost" data-v25-close>✕ Cerrar</button></header><section><h3>🗺️ Mapa futuro</h3>${pathHtml()}</section><section class="v25-grid"><article><h3>🎯 Próximos objetivos</h3>${goals.map(g=>`<div class="v25-goal"><span>${g.icon}</span><div><b>${E(g.title)}</b><small>${E(g.why)}</small></div></div>`).join('')}</article><article><h3>✨ Cómo me gusta practicar</h3><p class="muted">Esto es una preferencia flexible, no una etiqueta permanente.</p><div class="v25-pref-buttons">${[['mixed','🧭 Mezcla'],['visual','🖼️ Visual'],['audio','🎧 Audio'],['practice','🧩 Haciendo']].map(([v,l])=>`<button class="btn ${V25.preference===v?'btn-primary':'btn-soft'}" data-v25-pref="${v}">${l}</button>`).join('')}</div><div class="notice"><b>${p.icon} ${p.label}</b><br>${E(p.desc)}</div>${sp.total?`<small>Señal observada: ${sp.total} usos de ayuda. La preferencia elegida siempre tiene prioridad.</small>`:''}<h3>⏱️ Ritmo</h3><label>Meta semanal <select data-v25-minutes><option value="30">30 min</option><option value="40">40 min</option><option value="50">50 min</option><option value="60">60 min</option></select></label><p>${E(pace.reason)}</p></article></section><section><h3>📍 Estado por habilidad</h3><div class="v25-skill-grid">${rm.items.map(x=>`<div><span>${meta[x.skill].icon} ${meta[x.skill].label}</span><b>${x.score}%</b><small>${E(x.label)}</small><progress max="100" value="${x.score}"></progress></div>`).join('')}</div></section>${kid()?'':`<section><h3>🔎 Lectura para el adulto</h3><p><b>Prioridad:</b> ${meta[rm.weak.skill].label} (${rm.weak.score}%). <b>Fortaleza:</b> ${meta[rm.strong.skill].label} (${rm.strong.score}%). El orden puede cambiar conforme llegue nueva evidencia.</p><div class="row"><button class="btn btn-soft" data-v25-copy>Copiar ruta</button><button class="btn btn-soft" data-v25-csv>Exportar CSV</button></div></section>`}</div></div>`);const sel=document.querySelector('[data-v25-minutes]');if(sel)sel.value=String(V25.weeklyMinutes||40);bindModal()}
function textSummary(){const rm=roadmap(),p=preference();return `PET Quest — Ruta personalizada\nPreparación promedio: ${rm.readiness}%\nPrioridad: ${meta[rm.weak.skill].label} ${rm.weak.score}%\nFortaleza: ${meta[rm.strong.skill].label} ${rm.strong.score}%\nPreferencia flexible: ${p.label}\nMeta semanal: ${V25.weeklyMinutes} min\nPróximos objetivos:\n${nextGoals().map(g=>'- '+g.title).join('\n')}`}
function csv(){const rm=roadmap(),rows=[['skill','score','stage','next'],...rm.items.map(x=>[meta[x.skill].label,x.score,x.label,x.next])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='petquest_personal_learning_path.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function bindModal(){document.querySelector('[data-v25-close]')?.addEventListener('click',()=>document.querySelector('.v25-modal')?.remove());document.querySelectorAll('[data-v25-pref]').forEach(b=>b.addEventListener('click',()=>{V25.preference=b.dataset.v25Pref;save();modal()}));document.querySelector('[data-v25-minutes]')?.addEventListener('change',e=>{V25.weeklyMinutes=+e.target.value||40;save()});document.querySelector('[data-v25-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(textSummary());window.toast?.('Ruta copiada')}catch(_){}});document.querySelector('[data-v25-csv]')?.addEventListener('click',csv)}
function render25(){if(state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v25-home'))return;const anchor=main.querySelector('.v24-home')||main.querySelector('.v23-kid,.v23-adult')||main.firstElementChild;anchor?.insertAdjacentHTML('afterend',kid()?kidCard():adultCard());document.querySelector('[data-v25-open]')?.addEventListener('click',modal)}
const css=`.v25-home{margin-top:16px}.v25-hero{display:grid;grid-template-columns:240px 1fr;gap:22px;align-items:center}.v25-hero img{width:100%;border-radius:18px}.v25-pills{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.v25-pills span{background:#f4f3fb;border-radius:999px;padding:7px 10px}.v25-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.v25-stats div{background:#f7f7fb;padding:10px;border-radius:14px;text-align:center}.v25-stats b{display:block}.v25-modal{position:fixed;inset:0;background:rgba(25,27,48,.6);z-index:10030;padding:22px;overflow:auto;display:flex;justify-content:center;align-items:flex-start}.v25-modal-card{width:min(1080px,100%);background:#fff;border-radius:24px;padding:22px;box-shadow:0 22px 80px rgba(0,0,0,.28)}.v25-modal-head{display:flex;justify-content:space-between;gap:18px}.v25-roadmap{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.v25-stage{position:relative;background:#f7f7fb;border:1px solid rgba(70,70,120,.12);border-radius:18px;padding:12px;min-height:145px}.v25-stage.priority{outline:3px solid rgba(91,91,214,.22)}.v25-stage.goal{background:#fff6db}.v25-stage-icon{font-size:1.9rem}.v25-stage small,.v25-stage b,.v25-stage p{display:block}.v25-stage p{font-size:.78rem;margin:.4rem 0}.v25-stage-num{position:absolute;right:10px;top:9px;background:#fff;border-radius:50%;width:27px;height:27px;display:grid;place-items:center}.v25-grid{display:grid;grid-template-columns:1.2fr 1fr;gap:14px;margin-top:20px}.v25-grid>article{padding:14px;border:1px solid rgba(70,70,120,.12);border-radius:18px}.v25-goal{display:flex;gap:10px;padding:10px;background:#f8f8fb;border-radius:14px;margin:8px 0}.v25-goal>span{font-size:1.5rem}.v25-goal small{display:block}.v25-pref-buttons{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.v25-skill-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.v25-skill-grid>div{padding:12px;border-radius:15px;background:#f7f7fb}.v25-skill-grid span,.v25-skill-grid b,.v25-skill-grid small{display:block}.v25-skill-grid progress{width:100%;margin-top:8px}@media(max-width:760px){.v25-hero{grid-template-columns:1fr}.v25-hero img{max-height:190px}.v25-stats,.v25-skill-grid{grid-template-columns:repeat(2,1fr)}.v25-roadmap{grid-template-columns:1fr}.v25-stage{min-height:0}.v25-grid{grid-template-columns:1fr}.v25-modal{padding:8px}.v25-modal-card{padding:15px}.v25-modal-head{flex-direction:column}}`;
if(!document.getElementById('v25-css')){const s=document.createElement('style');s.id='v25-css';s.textContent=css;document.head.appendChild(s)}
const prior=render;render=function(){prior();requestAnimationFrame(render25)};
window.PETQUEST_V25={state:V25,snapshots,rank,roadmap,nextGoals,recommendedPace,version:'25.0'};
requestAnimationFrame(render25);
})();
