// PET Quest V26 — Teacher & School Operations Center.
(()=>{
'use strict';
const S={classes:[],students:[],intel:null,selected:null,loading:false};
const esc26=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleOK=()=>API?.token&&['teacher','school','admin'].includes(API?.user?.role);
const skillMeta={reading:['📖','Reading'],listening:['🎧','Listening'],writing:['✍️','Writing'],speaking:['🎙️','Speaking']};
async function load26(){if(!roleOK())return;S.loading=true;try{const [c,st]=await Promise.all([apiRequest('/classes'),apiRequest('/school-students')]);S.classes=c.classes||[];S.students=st.students||[];if(!S.selected&&S.classes.length)S.selected=S.classes[0].id;if(S.selected)S.intel=await apiRequest('/class-intelligence?course_id='+S.selected)}catch(e){console.warn('V26 load',e)}finally{S.loading=false;render26()}}
function weakest(r){const vals=[['reading',+r.reading||0],['listening',+r.listening||0],['writing',+r.writing||0],['speaking',+r.speaking||0]].filter(x=>x[1]>0);return vals.length?vals.sort((a,b)=>a[1]-b[1])[0]:['reading',0]}
function classOptions(){return S.classes.map(c=>`<option value="${c.id}" ${+S.selected===+c.id?'selected':''}>${esc26(c.name)} · ${c.student_count||0} alumnos</option>`).join('')}
function studentOptions(){return S.students.filter(x=>!x.disabled).map(s=>`<option value="${s.id}">${esc26(s.name)} · ${esc26(s.email)}</option>`).join('')}
function intelligenceHtml(){const I=S.intel;if(!I)return '<div class="empty">Selecciona una clase para analizarla.</div>';const avg=I.averages||{},cp=I.common_priority||'reading',m=skillMeta[cp]||['🎯',cp];return `<div class="v26-kpis"><div><b>${I.students?.length||0}</b><span>alumnos con datos</span></div><div><b>${m[0]} ${m[1]}</b><span>debilidad común</span></div><div><b>${I.risk_count||0}</b><span>requieren seguimiento</span></div><div><b>${Math.round(((avg.reading||0)+(avg.listening||0)+(avg.writing||0)+(avg.speaking||0))/4)||0}%</b><span>promedio 4 habilidades</span></div></div><div class="v26-skillrow">${Object.entries(skillMeta).map(([k,[ic,n]])=>`<div><span>${ic} ${n}</span><b>${avg[k]||0}%</b><progress max="100" value="${avg[k]||0}"></progress></div>`).join('')}</div><div class="v26-table"><table><thead><tr><th>Alumno</th><th>Readiness</th><th>Precisión</th><th>Prioridad individual</th><th>Estado</th></tr></thead><tbody>${(I.students||[]).map(r=>{const w=weakest(r),wm=skillMeta[w[0]];const risk=(r.readiness<65||r.accuracy<60)&&r.attempts>0;return `<tr><td>${esc26(r.name)}</td><td>${r.readiness||0}%</td><td>${r.accuracy||0}%</td><td>${wm[0]} ${wm[1]} ${w[1]}%</td><td><span class="v26-status ${risk?'risk':'ok'}">${risk?'Reforzar':'En curso'}</span></td></tr>`}).join('')||'<tr><td colspan="5">Aún no hay snapshots sincronizados.</td></tr>'}</tbody></table></div><div class="notice"><b>Plan grupal sugerido:</b> reforzar ${m[1]} en una actividad breve colectiva. La prioridad individual de cada alumno se conserva en su ruta personal.</div><button class="btn btn-primary" data-v26-group>Asignar refuerzo grupal de ${m[1]}</button>`}
function panel(){return `<section class="card v26-center"><div class="section-title"><div><span class="mission-label">V26 · Teacher & School Operations</span><h2>🏫 Centro operativo de clases</h2><p>Crea clases, matricula alumnos, asigna refuerzos y detecta debilidades comunes sin perder la personalización individual.</p></div><button class="btn btn-soft" data-v26-refresh>Actualizar</button></div><div class="v26-grid"><article><h3>1. Clase</h3><label>Clase<select data-v26-class>${classOptions()||'<option>Sin clases</option>'}</select></label><div class="row"><input data-v26-class-name placeholder="Ej. PET B1 · 6A"><button class="btn btn-soft" data-v26-create-class>Crear clase</button></div></article><article><h3>2. Matricular alumno</h3><label>Alumno<select data-v26-student>${studentOptions()||'<option>Sin alumnos</option>'}</select></label><button class="btn btn-soft" data-v26-enroll>Matricular en clase</button></article><article><h3>3. Asignar ruta</h3><label>Habilidad<select data-v26-skill>${Object.entries(skillMeta).map(([k,[i,n]])=>`<option value="${k}">${i} ${n}</option>`).join('')}</select></label><div class="row"><input data-v26-title placeholder="Refuerzo semanal"><input data-v26-due type="date"></div><button class="btn btn-soft" data-v26-assign>Asignar a la clase</button></article></div><div data-v26-msg></div><section class="v26-intel"><h3>4. Inteligencia de grupo</h3>${intelligenceHtml()}</section></section>`}
function inject(){if(!roleOK()||!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v26-center'))return;main.insertAdjacentHTML('beforeend',panel());bind26()}
function msg(t,ok=true){const x=document.querySelector('[data-v26-msg]');if(x)x.innerHTML=`<div class="feedback ${ok?'ok':'bad'}">${esc26(t)}</div>`}
async function refreshIntel(){if(!S.selected)return;try{S.intel=await apiRequest('/class-intelligence?course_id='+S.selected);render26()}catch(e){msg('No se pudo actualizar el análisis.',false)}}
function render26(){const old=document.querySelector('.v26-center');if(old){old.outerHTML=panel();bind26()}else requestAnimationFrame(inject)}
function bind26(){document.querySelector('[data-v26-refresh]')?.addEventListener('click',load26);document.querySelector('[data-v26-class]')?.addEventListener('change',async e=>{S.selected=+e.target.value;await refreshIntel()});document.querySelector('[data-v26-create-class]')?.addEventListener('click',async()=>{const name=document.querySelector('[data-v26-class-name]')?.value.trim();if(!name)return msg('Escribe un nombre para la clase.',false);try{const r=await apiRequest('/courses',{method:'POST',body:{name}});S.selected=r.id;await load26();msg('Clase creada.')}catch(e){msg('No se pudo crear la clase: '+e.message,false)}});document.querySelector('[data-v26-enroll]')?.addEventListener('click',async()=>{const sid=+document.querySelector('[data-v26-student]')?.value;if(!S.selected||!sid)return msg('Selecciona clase y alumno.',false);try{await apiRequest('/enrollments',{method:'POST',body:{course_id:S.selected,student_id:sid}});await load26();msg('Alumno matriculado.')}catch(e){msg('No se pudo matricular: '+e.message,false)}});document.querySelector('[data-v26-assign]')?.addEventListener('click',async()=>{if(!S.selected)return msg('Selecciona una clase.',false);const skill=document.querySelector('[data-v26-skill]').value,title=document.querySelector('[data-v26-title]').value.trim()||`Refuerzo ${skillMeta[skill][1]}`,due=document.querySelector('[data-v26-due]').value;try{await apiRequest('/assignments',{method:'POST',body:{course_id:S.selected,title,skill,due_date:due}});msg('Ruta asignada a la clase.')}catch(e){msg('No se pudo asignar: '+e.message,false)}});document.querySelector('[data-v26-group]')?.addEventListener('click',async()=>{const skill=S.intel?.common_priority||'reading';if(!S.selected)return;try{await apiRequest('/assignments',{method:'POST',body:{course_id:S.selected,title:`Refuerzo grupal · ${skillMeta[skill][1]}`,skill,due_date:''}});msg(`Refuerzo grupal de ${skillMeta[skill][1]} asignado.`)}catch(e){msg('No se pudo crear el refuerzo.',false)}})}
const css=`.v26-center{margin-top:16px}.v26-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.v26-grid article{background:#f8f8fc;border:1px solid rgba(70,70,120,.12);padding:14px;border-radius:18px}.v26-grid input,.v26-grid select{width:100%;min-height:42px}.v26-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.v26-kpis>div,.v26-skillrow>div{background:#f7f7fb;border-radius:15px;padding:11px;text-align:center}.v26-kpis b,.v26-kpis span{display:block}.v26-skillrow{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.v26-skillrow span,.v26-skillrow b{display:block}.v26-skillrow progress{width:100%}.v26-table{overflow:auto;margin:12px 0}.v26-table table{width:100%;border-collapse:collapse}.v26-table th,.v26-table td{padding:9px;border-bottom:1px solid #eee;text-align:left}.v26-status{padding:4px 8px;border-radius:999px;font-size:.78rem}.v26-status.risk{background:#fff0df}.v26-status.ok{background:#eaf8ef}@media(max-width:850px){.v26-grid{grid-template-columns:1fr}.v26-kpis,.v26-skillrow{grid-template-columns:repeat(2,1fr)}}`;
if(!document.getElementById('v26-css')){const st=document.createElement('style');st.id='v26-css';st.textContent=css;document.head.appendChild(st)}
const prev=render;render=function(){prev();requestAnimationFrame(()=>{inject();if(roleOK()&&['teacher','school','reports'].includes(state.view)&&!S.classes.length&&!S.loading)load26()})};
window.PETQUEST_V26={state:S,load:load26,version:'26.0'};
requestAnimationFrame(inject);
})();
