// PET Quest V27 — Classroom Intelligence System.
(()=>{
'use strict';
const V27={school:null,classIntel:null,plan:null,selected:null,loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta={reading:['📖','Reading'],listening:['🎧','Listening'],writing:['✍️','Writing'],speaking:['🎙️','Speaking']};
const roleOK=()=>API?.token&&['teacher','school','admin'].includes(API?.user?.role);
function scoreClass(c){const a=c.averages||{};const vals=Object.values(a).filter(x=>+x>0);return vals.length?Math.round(vals.reduce((x,y)=>x+(+y),0)/vals.length):0}
function weakest(r){const vals=Object.keys(meta).map(k=>[k,+r[k]||0]).filter(x=>x[1]>0);return vals.length?vals.sort((a,b)=>a[1]-b[1])[0]:['reading',0]}
async function load27(){if(!roleOK())return;V27.loading=true;try{V27.school=await apiRequest('/school-intelligence');if(!V27.selected&&V27.school.classes?.length)V27.selected=V27.school.classes[0].id;if(V27.selected){[V27.classIntel,V27.plan]=await Promise.all([apiRequest('/class-intelligence?course_id='+V27.selected),apiRequest('/weekly-class-plan?course_id='+V27.selected)])}}catch(e){console.warn('V27 load',e)}finally{V27.loading=false;render27()}}
function classCards(){const rows=V27.school?.classes||[];return rows.map(c=>{const p=meta[c.common_priority]||['🎯',c.common_priority];return `<button class="v27-classcard ${+c.id===+V27.selected?'active':''}" data-v27-pick="${c.id}"><strong>${esc(c.name)}</strong><span>${c.students_with_data||0}/${c.enrolled||0} con datos</span><div><b>${scoreClass(c)}%</b> promedio · <b>${c.readiness||0}%</b> readiness</div><small>${p[0]} Prioridad: ${p[1]} · ${c.risk_count||0} seguimiento</small></button>`}).join('')||'<div class="empty">Crea una clase para comenzar.</div>'}
function compareTable(){const rows=V27.school?.classes||[];return `<div class="v27-table"><table><thead><tr><th>Clase</th><th>Reading</th><th>Listening</th><th>Writing</th><th>Speaking</th><th>Readiness</th><th>Riesgo</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.name)}</td>${['reading','listening','writing','speaking'].map(k=>`<td>${c.averages?.[k]||0}%</td>`).join('')}<td>${c.readiness||0}%</td><td>${c.risk_count||0}</td></tr>`).join('')||'<tr><td colspan="7">Sin datos comparables.</td></tr>'}</tbody></table></div>`}
function clusterCandidates(){const I=V27.classIntel;if(!I)return [];const cp=I.common_priority||'reading';return (I.students||[]).filter(r=>{const w=weakest(r);return w[0]===cp && (w[1]<75 || r.readiness<70)}).map(r=>r.id)}
function planHtml(){const P=V27.plan;if(!P)return '<div class="empty">Selecciona una clase.</div>';return `<div class="v27-plan">${(P.plan||[]).map(x=>{const m=meta[x.skill]||['🎯',x.skill];return `<article><b>${x.day}</b><span>${m[0]} ${m[1]} · ${x.minutes} min</span><small>${esc(x.purpose)}</small></article>`}).join('')}</div><p class="muted">Plan sugerido a partir de promedios actuales. El profesor puede adaptarlo.</p>`}
function groupsHtml(){const gs=V27.school?.support_groups||[];return gs.length?`<div class="v27-groups">${gs.slice(0,8).map(g=>{const m=meta[g.skill]||['🎯',g.skill];return `<div><b>${m[0]} ${esc(g.name)}</b><span>${esc(g.course_name||'')} · ${g.member_count||0} alumnos</span><small>${esc(g.focus||'Refuerzo temporal')}</small></div>`}).join('')}</div>`:'<div class="empty">Aún no hay grupos temporales de refuerzo.</div>'}
function panel(){const I=V27.classIntel,cp=I?.common_priority||'reading',cm=meta[cp]||['🎯',cp],members=clusterCandidates();return `<section class="card v27-center"><div class="section-title"><div><span class="mission-label">V27 · Classroom Intelligence</span><h2>🧠 Inteligencia de aula</h2><p>Compara clases, detecta patrones comunes y crea refuerzos temporales sin alterar la ruta individual.</p></div><button class="btn btn-soft" data-v27-refresh>Actualizar</button></div><div class="v27-cards">${classCards()}</div><h3>Comparación entre clases</h3>${compareTable()}<div class="v27-grid"><article><h3>Clase seleccionada</h3>${I?`<div class="v27-kpi"><b>${esc(I.course?.name)}</b><span>${I.students?.length||0} alumnos con evidencia</span></div><div class="v27-kpi"><b>${cm[0]} ${cm[1]}</b><span>debilidad común</span></div><div class="v27-kpi"><b>${I.risk_count||0}</b><span>requieren seguimiento</span></div>`:'<div class="empty">Sin análisis.</div>'}</article><article><h3>Grupo temporal sugerido</h3><p>${members.length?`${members.length} alumno(s) comparten necesidad prioritaria en ${cm[1]}.`:'No hay suficientes alumnos con la misma necesidad para sugerir un grupo.'}</p><input data-v27-group-name value="Refuerzo ${cm[1]}" aria-label="Nombre del grupo"><input data-v27-focus value="${esc(cp)}" aria-label="Foco"><button class="btn btn-primary" data-v27-create-group ${members.length?'':'disabled'}>Crear grupo temporal (${members.length})</button></article><article><h3>Plan semanal colectivo</h3>${planHtml()}<button class="btn btn-soft" data-v27-assign-week>Asignar prioridad semanal</button></article></div><h3>Grupos temporales activos</h3>${groupsHtml()}<div data-v27-msg></div><div class="notice"><b>Regla V27:</b> el grupo temporal organiza refuerzo compartido, pero no cambia la matrícula ni reemplaza la prioridad personal de cada alumno.</div></section>`}
function msg(t,ok=true){const x=document.querySelector('[data-v27-msg]');if(x)x.innerHTML=`<div class="feedback ${ok?'ok':'bad'}">${esc(t)}</div>`}
function inject(){if(!roleOK()||!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v27-center'))return;main.insertAdjacentHTML('beforeend',panel());bind27()}
function render27(){const old=document.querySelector('.v27-center');if(old){old.outerHTML=panel();bind27()}else requestAnimationFrame(inject)}
async function pick(id){V27.selected=+id;try{[V27.classIntel,V27.plan]=await Promise.all([apiRequest('/class-intelligence?course_id='+id),apiRequest('/weekly-class-plan?course_id='+id)]);render27()}catch(e){msg('No se pudo analizar la clase.',false)}}
function bind27(){document.querySelector('[data-v27-refresh]')?.addEventListener('click',load27);document.querySelectorAll('[data-v27-pick]').forEach(b=>b.addEventListener('click',()=>pick(b.dataset.v27Pick)));document.querySelector('[data-v27-create-group]')?.addEventListener('click',async()=>{if(!V27.selected)return;const ids=clusterCandidates(),skill=V27.classIntel?.common_priority||'reading',name=document.querySelector('[data-v27-group-name]')?.value.trim()||`Refuerzo ${meta[skill][1]}`,focus=document.querySelector('[data-v27-focus]')?.value.trim()||skill;try{await apiRequest('/support-groups',{method:'POST',body:{course_id:V27.selected,name,skill,focus,student_ids:ids}});await load27();msg('Grupo temporal creado sin modificar las rutas individuales.')}catch(e){msg('No se pudo crear el grupo: '+e.message,false)}});document.querySelector('[data-v27-assign-week]')?.addEventListener('click',async()=>{if(!V27.selected||!V27.plan)return;const skill=V27.plan.priority||'reading';try{await apiRequest('/assignments',{method:'POST',body:{course_id:V27.selected,title:`Plan semanal colectivo · ${meta[skill][1]}`,skill,due_date:''}});msg(`Prioridad semanal de ${meta[skill][1]} asignada.`)}catch(e){msg('No se pudo crear la asignación.',false)}})}
const css=`.v27-center{margin-top:16px}.v27-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px;margin:12px 0}.v27-classcard{border:1px solid rgba(80,80,130,.16);background:#fafafe;border-radius:18px;padding:13px;text-align:left;cursor:pointer}.v27-classcard.active{outline:3px solid rgba(91,91,214,.25);background:#f1f1ff}.v27-classcard strong,.v27-classcard span,.v27-classcard small{display:block}.v27-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:14px}.v27-grid article{background:#f8f8fc;border:1px solid rgba(70,70,120,.12);padding:14px;border-radius:18px}.v27-grid input{width:100%;min-height:42px;margin:4px 0}.v27-kpi{padding:8px 0;border-bottom:1px solid #eee}.v27-kpi b,.v27-kpi span{display:block}.v27-table{overflow:auto}.v27-table table{width:100%;border-collapse:collapse}.v27-table th,.v27-table td{padding:9px;border-bottom:1px solid #eee;text-align:left}.v27-plan{display:grid;gap:6px}.v27-plan article,.v27-groups>div{display:flex;flex-direction:column;border-left:4px solid rgba(91,91,214,.35);padding:7px 9px;background:white;border-radius:10px;margin:5px 0}.v27-groups{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px}@media(max-width:900px){.v27-grid{grid-template-columns:1fr}}`;
if(!document.getElementById('v27-css')){const st=document.createElement('style');st.id='v27-css';st.textContent=css;document.head.appendChild(st)}
const prev=render;render=function(){prev();requestAnimationFrame(()=>{inject();if(roleOK()&&['teacher','school','reports'].includes(state.view)&&!V27.school&&!V27.loading)load27()})};
window.PETQUEST_V27={state:V27,load:load27,version:'27.0'};
requestAnimationFrame(inject);
})();
