// PET Quest V28 — Teacher Planning & Intervention Engine.
(()=>{
'use strict';
const V28={plan:null,course:null,loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta={reading:['📖','Reading'],listening:['🎧','Listening'],writing:['✍️','Writing'],speaking:['🎙️','Speaking']};
const roleOK=()=>API?.token&&['teacher','school','admin'].includes(API?.user?.role);
function currentCourse(){return window.PETQUEST_V27?.state?.selected||null}
async function load28(){if(!roleOK())return;const cid=currentCourse();if(!cid)return;V28.loading=true;try{V28.course=cid;V28.plan=await apiRequest('/intervention-plan?course_id='+cid)}catch(e){console.warn('V28 load',e);V28.plan=null}finally{V28.loading=false;render28()}}
function interventionCards(){const rows=V28.plan?.interventions||[];if(!rows.length)return '<div class="empty">No hay grupos con evidencia suficiente para intervención. Mantén la ruta personalizada.</div>';return rows.map((x,i)=>{const m=meta[x.skill]||['🎯',x.label];return `<article class="v28-intervention"><div class="v28-rank">${i+1}</div><div><h4>${m[0]} ${esc(x.label)} · prioridad ${esc(x.priority)}</h4><p><b>${x.count}</b> alumno(s) · promedio <b>${x.average}%</b> · ${x.minutes} min</p><small>${esc(x.activity)}</small><small><b>Criterio de salida:</b> ${esc(x.success_criteria)}</small><div class="v28-students">${x.students.slice(0,8).map(s=>`<span>${esc(s.name)} · ${s.score}%</span>`).join('')}</div><button class="btn btn-primary" data-v28-assign="${i}">Crear intervención</button></div></article>`}).join('')}
function advance(){const rows=V28.plan?.advance_candidates||[];return rows.length?rows.map(s=>`<div class="v28-person"><b>🚀 ${esc(s.name)}</b><span>${s.readiness}% readiness · ${s.accuracy}% precisión</span></div>`).join(''):'<div class="empty">Aún no hay alumnos con evidencia suficiente para recomendar avance.</div>'}
function follow(){const rows=V28.plan?.follow_up||[];return rows.length?rows.map(s=>`<div class="v28-person"><b>🛟 ${esc(s.name)}</b><span>${s.readiness}% readiness · ${s.accuracy}% precisión</span></div>`).join(''):'<div class="empty">No hay alumnos con señal de seguimiento intensivo.</div>'}
function panel(){const P=V28.plan;return `<section class="card v28-center"><div class="section-title"><div><span class="mission-label">V28 · Intervention Engine</span><h2>🧭 Planificación e intervención</h2><p>Convierte la evidencia de aula en grupos, actividades y criterios de seguimiento concretos.</p></div><button class="btn btn-soft" data-v28-refresh>Recalcular</button></div>${P?`<div class="v28-summary"><div><b>${P.student_count}</b><span>alumnos con reporte</span></div><div><b>${P.interventions.length}</b><span>intervenciones sugeridas</span></div><div><b>${P.advance_candidates.length}</b><span>listos para avanzar</span></div><div><b>${P.follow_up.length}</b><span>seguimiento</span></div></div><h3>Intervenciones priorizadas</h3><div class="v28-list">${interventionCards()}</div><div class="v28-grid"><article><h3>🚀 Pueden avanzar</h3>${advance()}</article><article><h3>🛟 Requieren seguimiento</h3>${follow()}</article></div>`:'<div class="empty">Selecciona una clase y pulsa Recalcular.</div>'}<div data-v28-msg></div><div class="notice"><b>Regla V28:</b> una intervención colectiva complementa la ruta individual. El criterio de salida evita mantener a un alumno indefinidamente en un grupo de refuerzo.</div></section>`}
function msg(t,ok=true){const x=document.querySelector('[data-v28-msg]');if(x)x.innerHTML=`<div class="feedback ${ok?'ok':'bad'}">${esc(t)}</div>`}
async function assign(idx){const x=V28.plan?.interventions?.[idx];const cid=currentCourse();if(!x||!cid)return;try{await apiRequest('/support-groups',{method:'POST',body:{course_id:cid,name:`Intervención ${x.label}`,skill:x.skill,focus:x.success_criteria,student_ids:x.student_ids}});await apiRequest('/assignments',{method:'POST',body:{course_id:cid,title:`Intervención ${x.label} · ${x.minutes} min`,skill:x.skill,due_date:''}});msg(`Intervención de ${x.label} creada para ${x.count} alumno(s).`);if(window.PETQUEST_V27?.load)await window.PETQUEST_V27.load()}catch(e){msg('No se pudo crear la intervención: '+e.message,false)}}
function bind(){document.querySelector('[data-v28-refresh]')?.addEventListener('click',load28);document.querySelectorAll('[data-v28-assign]').forEach(b=>b.addEventListener('click',()=>assign(+b.dataset.v28Assign)))}
function inject(){if(!roleOK()||!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v28-center'))return;main.insertAdjacentHTML('beforeend',panel());bind()}
function render28(){const old=document.querySelector('.v28-center');if(old){old.outerHTML=panel();bind()}else requestAnimationFrame(inject)}
const css=`.v28-center{margin-top:16px}.v28-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.v28-summary>div{padding:12px;border-radius:16px;background:#f7f7fd;text-align:center}.v28-summary b,.v28-summary span{display:block}.v28-summary b{font-size:1.35rem}.v28-list{display:grid;gap:10px}.v28-intervention{display:grid;grid-template-columns:40px 1fr;gap:10px;border:1px solid rgba(70,70,120,.12);border-radius:18px;padding:12px;background:#fbfbff}.v28-rank{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#5b5bd6;color:white;font-weight:800}.v28-intervention h4{margin:0 0 6px}.v28-intervention small{display:block;margin:4px 0}.v28-students{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.v28-students span{padding:5px 8px;background:#efeffb;border-radius:999px;font-size:.86rem}.v28-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.v28-grid article{padding:14px;background:#f8f8fc;border-radius:18px}.v28-person{display:flex;justify-content:space-between;gap:8px;padding:8px 0;border-bottom:1px solid #eee}.v28-person span{font-size:.9rem;color:#666}@media(max-width:800px){.v28-summary{grid-template-columns:1fr 1fr}.v28-grid{grid-template-columns:1fr}.v28-person{flex-direction:column}}`;
if(!document.getElementById('v28-css')){const st=document.createElement('style');st.id='v28-css';st.textContent=css;document.head.appendChild(st)}
const prev=render;render=function(){prev();requestAnimationFrame(()=>{inject();const cid=currentCourse();if(roleOK()&&['teacher','school','reports'].includes(state.view)&&cid&&cid!==V28.course&&!V28.loading)load28()})};
window.PETQUEST_V28={state:V28,load:load28,version:'28.0'};
requestAnimationFrame(inject);
})();
