// PET Quest V29 — Intervention Outcome Engine
(()=>{
'use strict';
const V29={course:null,data:null,effect:null,loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleOK=()=>API?.token&&['teacher','school','admin'].includes(API?.user?.role);
const currentCourse=()=>window.PETQUEST_V27?.state?.selected||null;
const labels={reading:'📖 Reading',listening:'🎧 Listening',writing:'✍️ Writing',speaking:'🎙️ Speaking'};
const recLabel={close:'✅ Cerrar',extend:'🕒 Extender',change_strategy:'🔄 Cambiar estrategia',collect_more_data:'📊 Reunir evidencia'};
async function load29(){if(!roleOK())return;const cid=currentCourse();if(!cid)return;V29.loading=true;try{V29.course=cid;V29.data=await apiRequest('/intervention-outcomes?course_id='+cid);V29.effect=await apiRequest('/intervention-effectiveness')}catch(e){console.warn('V29',e)}finally{V29.loading=false;render29()}}
function outcomeCard(x){const delta=Number(x.delta||0);return `<article class="v29-outcome"><div class="v29-head"><div><b>${esc(x.group_name)}</b><span>${labels[x.skill]||esc(x.skill)}</span></div><strong class="${delta>=0?'v29-up':'v29-down'}">${delta>=0?'+':''}${delta}</strong></div><div class="v29-beforeafter"><div><span>Antes</span><b>${Number(x.baseline_average||0).toFixed(0)}%</b></div><div>→</div><div><span>Ahora</span><b>${Number(x.current_average||0).toFixed(0)}%</b></div></div><p><b>Decisión:</b> ${recLabel[x.recommendation]||esc(x.recommendation)}</p><small>${esc(x.success_criteria||'Sin criterio registrado')}</small><div class="v29-members">${(x.members||[]).slice(0,10).map(m=>`<span>${esc(m.name)} ${Number(m.delta||0)>=0?'+':''}${Number(m.delta||0).toFixed(0)}</span>`).join('')}</div>${x.status!=='closed'?`<button class="btn btn-primary" data-v29-evaluate="${x.group_id}">Reevaluar ahora</button>`:'<span class="badge">Cerrada</span>'}</article>`}
function effectiveness(){const rows=V29.effect?.by_skill||[];if(!rows.length)return '<div class="empty">Aún no hay intervenciones evaluadas.</div>';return `<div class="v29-effect">${rows.map(r=>`<div><b>${labels[r.skill]||r.skill}</b><span>${r.interventions} intervención(es)</span><strong>${Number(r.average_gain||0)>=0?'+':''}${Number(r.average_gain||0).toFixed(1)} pts</strong><small>${r.successful||0} cierre(s) recomendado(s)</small></div>`).join('')}</div>`}
function panel(){const rows=V29.data?.outcomes||[];return `<section class="card v29-center"><div class="section-title"><div><span class="mission-label">V29 · Outcome Engine</span><h2>📈 ¿Funcionó la intervención?</h2><p>Compara la línea base con el resultado actual y decide si conviene cerrar, extender o cambiar la estrategia.</p></div><button class="btn btn-soft" data-v29-refresh>Actualizar</button></div><div class="v29-list">${rows.length?rows.map(outcomeCard).join(''):'<div class="empty">Crea una intervención V28 para empezar a medir resultados.</div>'}</div><h3>Qué está funcionando mejor</h3>${effectiveness()}<div data-v29-msg></div><div class="notice"><b>Regla V29:</b> una mejora grupal no sustituye el seguimiento individual. La recomendación se basa en cambio observado y evidencia disponible.</div></section>`}
function msg(t,ok=true){const n=document.querySelector('[data-v29-msg]');if(n)n.innerHTML=`<div class="feedback ${ok?'ok':'bad'}">${esc(t)}</div>`}
async function evaluate(gid){try{const r=await apiRequest('/interventions/evaluate',{method:'POST',body:{group_id:+gid}});msg(`${recLabel[r.recommendation]||r.recommendation}: ${r.reason}`);await load29()}catch(e){msg('No se pudo reevaluar: '+e.message,false)}}
function bind(){document.querySelector('[data-v29-refresh]')?.addEventListener('click',load29);document.querySelectorAll('[data-v29-evaluate]').forEach(b=>b.addEventListener('click',()=>evaluate(b.dataset.v29Evaluate)))}
function inject(){if(!roleOK()||!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v29-center'))return;main.insertAdjacentHTML('beforeend',panel());bind()}
function render29(){const old=document.querySelector('.v29-center');if(old){old.outerHTML=panel();bind()}else requestAnimationFrame(inject)}
const css=`.v29-center{margin-top:16px}.v29-list{display:grid;gap:12px}.v29-outcome{border:1px solid #e6e6f2;border-radius:18px;padding:14px;background:#fff}.v29-head{display:flex;justify-content:space-between;gap:12px}.v29-head span{display:block;color:#666;font-size:.9rem}.v29-head strong{font-size:1.3rem}.v29-up{color:#16803b}.v29-down{color:#b42318}.v29-beforeafter{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:10px;margin:12px 0}.v29-beforeafter>div{padding:10px;border-radius:14px;background:#f7f7fd;text-align:center}.v29-beforeafter>div:nth-child(2){background:transparent}.v29-beforeafter span,.v29-beforeafter b{display:block}.v29-members{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.v29-members span{background:#f1f1f8;padding:5px 8px;border-radius:999px;font-size:.84rem}.v29-effect{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.v29-effect>div{padding:12px;border-radius:16px;background:#f8f8fc}.v29-effect b,.v29-effect span,.v29-effect strong,.v29-effect small{display:block;margin:2px 0}@media(max-width:850px){.v29-effect{grid-template-columns:1fr 1fr}}@media(max-width:520px){.v29-effect{grid-template-columns:1fr}.v29-head{flex-direction:column}}`;
if(!document.getElementById('v29-css')){const s=document.createElement('style');s.id='v29-css';s.textContent=css;document.head.appendChild(s)}
const prev=render;render=function(){prev();requestAnimationFrame(()=>{inject();const cid=currentCourse();if(roleOK()&&['teacher','school','reports'].includes(state.view)&&cid&&cid!==V29.course&&!V29.loading)load29()})};
window.PETQUEST_V29={state:V29,load:load29,version:'29.0'};requestAnimationFrame(inject);
})();
