// PET Quest V30 — School Impact & Quality Engine
(()=>{
'use strict';
const V30={data:null,loading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleOK=()=>API?.token&&['teacher','school','admin'].includes(API?.user?.role);
const skillIcon={reading:'📖',listening:'🎧',writing:'✍️',speaking:'🎙️'};
const pct=n=>`${Number(n||0).toFixed(0)}%`;
const delta=n=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(1)}`;
async function load30(){if(!roleOK())return;V30.loading=true;try{V30.data=await apiRequest('/school-impact')}catch(e){console.warn('V30',e)}finally{V30.loading=false;render30()}}
function classes(){const rows=V30.data?.classes||[];if(!rows.length)return '<div class="empty">Aún no hay clases con datos.</div>';return `<div class="v30-table"><div class="v30-row v30-th"><span>Clase</span><span>Readiness</span><span>Precisión</span><span>Riesgo</span></div>${rows.map(r=>`<div class="v30-row"><b>${esc(r.name)}</b><span>${pct(r.readiness)}</span><span>${pct(r.accuracy)}</span><span>${r.risk_count||0}</span></div>`).join('')}</div>`}
function interventions(){const x=V30.data?.interventions||{};const rows=x.by_skill||[];return `<div class="v30-kpis"><div><span>Intervenciones evaluadas</span><b>${x.evaluated||0}</b></div><div><span>Ganancia media</span><b>${delta(x.average_gain)} pts</b></div><div><span>Cierres recomendados</span><b>${x.successful||0}</b></div></div>${rows.length?`<div class="v30-skills">${rows.map(r=>`<div><b>${skillIcon[r.skill]||''} ${esc(r.skill)}</b><span>${r.interventions} interv.</span><strong>${delta(r.average_gain)} pts</strong></div>`).join('')}</div>`:''}`}
function growth(){const g=V30.data?.growth||{};const has=Object.keys(g).length; if(!has)return '<div class="notice">Guarda un corte de periodo para empezar a medir crecimiento institucional real.</div>';return `<div class="v30-growth">${['readiness','accuracy','reading','listening','writing','speaking'].map(k=>`<div><span>${skillIcon[k]||'📈'} ${k}</span><b class="${Number(g[k]||0)>=0?'v30-pos':'v30-neg'}">${delta(g[k])}</b></div>`).join('')}</div>`}
function priorities(){const rows=V30.data?.priorities||[];return rows.length?`<div class="v30-priorities">${rows.map((p,i)=>`<div><b>${i+1}. ${esc(p.label)}</b><span>${esc(p.reason)}</span></div>`).join('')}</div>`:'<div class="empty">Sin prioridades críticas detectadas.</div>'}
function panel(){const d=V30.data||{};const s=d.school||{};return `<section class="card v30-center"><div class="section-title"><div><span class="mission-label">V30 · School Impact & Quality</span><h2>🏫 Impacto y calidad del colegio</h2><p>Separa actividad, crecimiento académico, efectividad de intervenciones y riesgo para tomar decisiones con evidencia.</p></div><button class="btn btn-soft" data-v30-refresh>Actualizar</button></div><div class="v30-hero"><div><span>Preparación institucional</span><b>${pct(s.readiness)}</b></div><div><span>Precisión</span><b>${pct(s.accuracy)}</b></div><div><span>Alumnos con datos</span><b>${s.students_with_data||0}/${s.students_total||0}</b></div><div><span>Riesgo</span><b class="v30-risk-${esc(d.risk_level||'low')}">${esc((d.risk_level||'low').toUpperCase())}</b></div></div><h3>Crecimiento vs. último corte</h3>${growth()}<div class="v30-actions"><button class="btn btn-primary" data-v30-snapshot>Guardar corte de periodo</button><button class="btn btn-soft" data-v30-csv>Exportar CSV</button></div><h3>Comparación de clases</h3>${classes()}<h3>Efectividad de intervenciones</h3>${interventions()}<h3>Prioridades ejecutivas</h3>${priorities()}<div data-v30-msg></div><div class="notice"><b>Interpretación:</b> estos indicadores apoyan decisiones escolares; no sustituyen evaluación docente ni certificación oficial PET.</div></section>`}
function msg(t,ok=true){const n=document.querySelector('[data-v30-msg]');if(n)n.innerHTML=`<div class="feedback ${ok?'ok':'bad'}">${esc(t)}</div>`}
async function snapshot(){try{const label=new Date().toISOString().slice(0,10);const r=await apiRequest('/school-impact/snapshot',{method:'POST',body:{period_label:label}});msg(`Corte ${r.period_label} guardado.`);await load30()}catch(e){msg('No se pudo guardar el corte: '+e.message,false)}}
function csv(){if(!API?.token)return;fetch('/api/school-impact.csv',{headers:{Authorization:'Bearer '+API.token}}).then(r=>{if(!r.ok)throw Error('export');return r.blob()}).then(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='petquest_school_impact.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}).catch(()=>msg('No se pudo exportar CSV.',false))}
function bind(){document.querySelector('[data-v30-refresh]')?.addEventListener('click',load30);document.querySelector('[data-v30-snapshot]')?.addEventListener('click',snapshot);document.querySelector('[data-v30-csv]')?.addEventListener('click',csv)}
function inject(){if(!roleOK()||!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v30-center'))return;main.insertAdjacentHTML('beforeend',panel());bind();if(!V30.data&&!V30.loading)load30()}
function render30(){const old=document.querySelector('.v30-center');if(old){old.outerHTML=panel();bind()}else requestAnimationFrame(inject)}
const css=`.v30-center{margin-top:16px}.v30-hero,.v30-kpis,.v30-growth,.v30-skills{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.v30-hero>div,.v30-kpis>div,.v30-growth>div,.v30-skills>div{padding:12px;border-radius:16px;background:#f8f8fc}.v30-hero span,.v30-hero b,.v30-kpis span,.v30-kpis b,.v30-skills span,.v30-skills strong{display:block}.v30-hero b{font-size:1.35rem}.v30-risk-high,.v30-neg{color:#b42318}.v30-risk-medium{color:#9a6700}.v30-risk-low,.v30-pos{color:#16803b}.v30-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.v30-table{display:grid;gap:4px}.v30-row{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:8px;padding:9px 10px;border-radius:12px;background:#fafafe}.v30-th{font-size:.82rem;color:#666;background:#f0f0f7}.v30-priorities{display:grid;gap:8px}.v30-priorities>div{padding:11px;border-left:4px solid #6656d9;background:#f8f7ff;border-radius:10px}.v30-priorities b,.v30-priorities span{display:block}@media(max-width:850px){.v30-hero,.v30-kpis,.v30-growth,.v30-skills{grid-template-columns:1fr 1fr}}@media(max-width:560px){.v30-hero,.v30-kpis,.v30-growth,.v30-skills{grid-template-columns:1fr}.v30-row{grid-template-columns:1.5fr 1fr 1fr}.v30-row>*:last-child{display:none}}`;
if(!document.getElementById('v30-css')){const s=document.createElement('style');s.id='v30-css';s.textContent=css;document.head.appendChild(s)}
const prev=render;render=function(){prev();requestAnimationFrame(inject)};
window.PETQUEST_V30={state:V30,load:load30,version:'30.0'};requestAnimationFrame(inject);
})();
