// PET Quest V31 — Executive Academic Review
(()=>{
'use strict';
const V31={data:null,loading:false,window:'monthly'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>`${Number(n||0).toFixed(0)}%`;
const dlt=n=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(1)}`;
const roleOK=()=>API?.token&&['teacher','school','admin'].includes(API?.user?.role);
const icon={reading:'📖',listening:'🎧',writing:'✍️',speaking:'🎙️'};
function lineChart(){const h=V31.data?.history||[];if(!h.length)return '<div class="empty">Guarda un corte mensual o trimestral para construir la tendencia.</div>';const pts=[...h,{period_label:'Actual',readiness:V31.data?.school?.readiness||0,accuracy:V31.data?.school?.accuracy||0}];const w=720,H=190,pad=28, max=100;const xy=(v,i)=>[pad+i*(w-2*pad)/Math.max(1,pts.length-1),H-pad-(Number(v||0)/max)*(H-2*pad)];const path=k=>pts.map((r,i)=>{const [x,y]=xy(r[k],i);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ');return `<div class="v31-chart-wrap"><svg class="v31-chart" viewBox="0 0 ${w} ${H}" role="img" aria-label="Tendencia de preparación y precisión"><line x1="${pad}" y1="${H-pad}" x2="${w-pad}" y2="${H-pad}" class="v31-axis"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${H-pad}" class="v31-axis"/>${[25,50,75,100].map(v=>{const y=xy(v,0)[1];return `<line x1="${pad}" y1="${y}" x2="${w-pad}" y2="${y}" class="v31-grid"/><text x="2" y="${y+4}" class="v31-label">${v}</text>`}).join('')}<path d="${path('readiness')}" class="v31-line v31-readiness"/><path d="${path('accuracy')}" class="v31-line v31-accuracy"/>${pts.map((r,i)=>{const [x,y]=xy(r.readiness,i);return `<circle cx="${x}" cy="${y}" r="4" class="v31-dot"/><text x="${x}" y="${H-6}" text-anchor="middle" class="v31-label">${esc(String(r.period_label||'').slice(0,12))}</text>`}).join('')}</svg><div class="v31-legend"><span>● Preparación</span><span>— Precisión</span></div></div>`}
function skillBars(){const s=V31.data?.school||{};return `<div class="v31-skill-bars">${['reading','listening','writing','speaking'].map(k=>`<div class="v31-skill"><div><b>${icon[k]} ${k[0].toUpperCase()+k.slice(1)}</b><span>${pct(s[k])}</span></div><div class="v31-track"><i style="width:${Math.max(0,Math.min(100,Number(s[k]||0)))}%"></i></div></div>`).join('')}</div>`}
function classTable(){const rows=V31.data?.classes||[];if(!rows.length)return '<div class="empty">Aún no hay cursos con datos.</div>';const imp=Object.fromEntries((V31.data?.class_improvements||[]).map(x=>[x.id,x]));return `<div class="v31-table"><div class="v31-row v31-head"><span>Curso</span><span>Profesor</span><span>Preparación</span><span>Cambio</span><span>Riesgo</span></div>${rows.map(r=>{const x=imp[r.id];return `<div class="v31-row"><b>${esc(r.name)}</b><span>${esc(r.teacher)}</span><span>${pct(r.readiness)}</span><span class="${x&&Number(x.delta)>=0?'v31-pos':'v31-neg'}">${x?dlt(x.delta):'—'}</span><span>${r.risk_count||0}</span></div>`}).join('')}</div><div class="notice">La comparación es por curso/cohorte. PET Quest no crea rankings públicos de estudiantes.</div>`}
function interventions(){const x=V31.data?.interventions||{}, rows=x.by_skill||[];return `<div class="v31-kpis"><div><span>Evaluadas</span><b>${x.evaluated||0}</b></div><div><span>Ganancia media</span><b>${dlt(x.average_gain)} pts</b></div><div><span>Cierres recomendados</span><b>${x.successful||0}</b></div></div>${rows.length?`<div class="v31-strategies">${rows.map(r=>`<div><b>${icon[r.skill]||''} ${esc(r.skill)}</b><span>${r.interventions} intervención(es)</span><strong>${dlt(r.average_gain)} pts</strong></div>`).join('')}</div>`:'<div class="empty">Aún no hay intervenciones evaluadas.</div>'}`}
function priorities(){const p=V31.data?.priorities||[];return p.length?`<div class="v31-priorities">${p.map((r,i)=>`<article><b>${i+1}. ${esc(r.label)}</b><p>${esc(r.reason)}</p></article>`).join('')}</div>`:'<div class="empty">Sin prioridades críticas detectadas.</div>'}
function panel(){const d=V31.data||{},s=d.school||{},g=d.growth||{};return `<section class="card v31-review" id="v31-review"><div class="section-title"><div><span class="mission-label">V31 · Executive Academic Review</span><h2>📊 Revisión académica ejecutiva</h2><p>Impacto, calidad, riesgo y efectividad en una sola lectura para dirección.</p></div><button class="btn btn-soft v31-no-print" data-v31-refresh>Actualizar</button></div><div class="v31-controls v31-no-print"><label>Periodo <select data-v31-window><option value="monthly" ${V31.window==='monthly'?'selected':''}>Mensual</option><option value="quarterly" ${V31.window==='quarterly'?'selected':''}>Trimestral</option></select></label><button class="btn btn-primary" data-v31-snapshot>Guardar corte</button><button class="btn btn-soft" data-v31-print>Imprimir / Guardar PDF</button><button class="btn btn-soft" data-v31-csv>Exportar CSV</button></div><div class="v31-hero"><div><span>Preparación</span><b>${pct(s.readiness)}</b><small>${g.readiness===undefined?'sin corte previo':`${dlt(g.readiness)} pts`}</small></div><div><span>Precisión</span><b>${pct(s.accuracy)}</b><small>${g.accuracy===undefined?'sin corte previo':`${dlt(g.accuracy)} pts`}</small></div><div><span>Alumnos con evidencia</span><b>${s.students_with_data||0}/${s.students_total||0}</b><small>cobertura académica</small></div><div><span>Seguimiento</span><b>${s.risk_count||0}</b><small>señal operacional</small></div></div><h3>Tendencia ${V31.window==='monthly'?'mensual':'trimestral'}</h3>${lineChart()}<h3>Calidad por habilidad</h3>${skillBars()}<h3>Cursos y docentes</h3>${classTable()}<h3>Impacto de intervenciones</h3>${interventions()}<h3>Prioridades para dirección</h3>${priorities()}<div data-v31-msg></div><footer class="v31-report-note">PET Quest · Revisión ejecutiva · ${new Date().toLocaleDateString()} · Los indicadores apoyan decisiones académicas y no sustituyen evaluación docente ni certificación oficial.</footer></section>`}
function msg(t,ok=true){const n=document.querySelector('[data-v31-msg]');if(n)n.innerHTML=`<div class="feedback ${ok?'ok':'bad'}">${esc(t)}</div>`}
async function load(){if(!roleOK())return;V31.loading=true;try{V31.data=await apiRequest(`/executive-review?window=${V31.window}`)}catch(e){console.warn('V31',e);V31.data=null}finally{V31.loading=false;render31()}}
async function snapshot(){try{const label=prompt('Nombre del periodo',V31.window==='monthly'?new Date().toISOString().slice(0,7):`Q${Math.floor(new Date().getMonth()/3)+1}-${new Date().getFullYear()}`);if(!label)return;await apiRequest('/executive-review/snapshot',{method:'POST',body:{period_label:label,window_type:V31.window}});msg(`Corte ${label} guardado.`);await load()}catch(e){msg('No se pudo guardar el corte: '+e.message,false)}}
function csv(){if(!API?.token)return;fetch('/api/executive-review.csv',{headers:{Authorization:'Bearer '+API.token}}).then(r=>{if(!r.ok)throw Error('export');return r.blob()}).then(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='petquest_executive_review.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)}).catch(()=>msg('No se pudo exportar CSV.',false))}
function bind(){document.querySelector('[data-v31-refresh]')?.addEventListener('click',load);document.querySelector('[data-v31-window]')?.addEventListener('change',e=>{V31.window=e.target.value;load()});document.querySelector('[data-v31-snapshot]')?.addEventListener('click',snapshot);document.querySelector('[data-v31-print]')?.addEventListener('click',()=>window.print());document.querySelector('[data-v31-csv]')?.addEventListener('click',csv)}
function inject(){if(!roleOK()||!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v31-review'))return;main.insertAdjacentHTML('beforeend',panel());bind();if(!V31.data&&!V31.loading)load()}
function render31(){const old=document.querySelector('.v31-review');if(old){old.outerHTML=panel();bind()}else requestAnimationFrame(inject)}
const css=`.v31-review{margin-top:16px}.v31-controls{display:flex;gap:8px;flex-wrap:wrap;align-items:end}.v31-controls label{display:grid;gap:4px}.v31-controls select{padding:9px;border-radius:10px;border:1px solid #ccc}.v31-hero,.v31-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.v31-hero>div,.v31-kpis>div{background:#f8f8fc;padding:13px;border-radius:16px}.v31-hero span,.v31-hero b,.v31-hero small,.v31-kpis span,.v31-kpis b{display:block}.v31-hero b{font-size:1.45rem}.v31-pos{color:#147a39}.v31-neg{color:#b42318}.v31-chart-wrap{overflow:auto;background:#fbfbfe;border-radius:16px;padding:10px}.v31-chart{width:100%;min-width:620px;max-height:230px}.v31-axis{stroke:#aaa;stroke-width:1}.v31-grid{stroke:#e6e6ef;stroke-width:1}.v31-line{fill:none;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.v31-readiness{stroke:#5b5bd6}.v31-accuracy{stroke:#444;stroke-dasharray:7 6}.v31-dot{fill:#5b5bd6}.v31-label{font-size:10px;fill:#777}.v31-legend{display:flex;gap:16px;font-size:.85rem;color:#555}.v31-skill-bars{display:grid;gap:10px}.v31-skill>div:first-child{display:flex;justify-content:space-between}.v31-track{height:10px;border-radius:99px;background:#ececf5;overflow:hidden}.v31-track i{display:block;height:100%;background:#5b5bd6;border-radius:inherit}.v31-table{display:grid;gap:4px}.v31-row{display:grid;grid-template-columns:1.4fr 1.4fr .8fr .7fr .6fr;gap:8px;padding:9px 10px;background:#fafafe;border-radius:11px;align-items:center}.v31-head{font-size:.8rem;color:#666;background:#efeff7}.v31-strategies{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.v31-strategies>div{padding:10px;border-radius:14px;background:#f8f7ff}.v31-strategies span,.v31-strategies strong{display:block}.v31-priorities{display:grid;gap:8px}.v31-priorities article{padding:11px;border-left:4px solid #5b5bd6;background:#f8f7ff;border-radius:10px}.v31-priorities p{margin:4px 0 0}.v31-report-note{margin-top:18px;padding-top:12px;border-top:1px solid #ddd;font-size:.78rem;color:#666}@media(max-width:850px){.v31-hero,.v31-kpis,.v31-strategies{grid-template-columns:1fr 1fr}.v31-row{grid-template-columns:1.3fr 1fr .7fr}.v31-row>*:nth-child(2),.v31-row>*:last-child{display:none}}@media(max-width:560px){.v31-hero,.v31-kpis,.v31-strategies{grid-template-columns:1fr}}@media print{body *{visibility:hidden!important}#v31-review,#v31-review *{visibility:visible!important}#v31-review{position:absolute;left:0;top:0;width:100%;box-shadow:none;border:none}.v31-no-print{display:none!important}.v31-chart-wrap{overflow:visible}.v31-chart{min-width:0}.v31-report-note{display:block}.v31-row{break-inside:avoid}.v31-review h3{break-after:avoid}}`;
if(!document.getElementById('v31-css')){const st=document.createElement('style');st.id='v31-css';st.textContent=css;document.head.appendChild(st)}
const prev=render;render=function(){prev();requestAnimationFrame(inject)};
window.PETQUEST_V31={state:V31,load,version:'31.0'};requestAnimationFrame(inject);
})();
