(()=>{
const V32={data:null}; const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ok(){return typeof API!=='undefined'&&API.user&&['school','admin'].includes(API.user.role)}
async function req(path,opt={}){return apiRequest(path,opt)}
function panel(){const d=V32.data||{},goals=d.goals||[],acts=d.actions||[],alerts=d.alerts||[],m=d.metrics||{};return `<section class="card v32" id="v32-governance"><div class="section-title"><div><span class="mission-label">V32 · School Governance & Quality Assurance</span><h2>🏛️ Gobierno académico</h2><p>Objetivos, responsables, acciones, desviaciones y revisión de impacto.</p></div><button class="btn btn-soft" data-v32-refresh>Actualizar</button></div><div class="v32-kpis"><div><span>Preparación</span><b>${Math.round(m.readiness||0)}%</b></div><div><span>Precisión</span><b>${Math.round(m.accuracy||0)}%</b></div><div><span>Riesgo</span><b>${m.risk_count||0}</b></div><div><span>Alertas</span><b>${alerts.length}</b></div></div>${alerts.length?`<div class="v32-alerts">${alerts.map(a=>`<article><b>⚠️ ${esc(a.label)}</b><span>${esc(a.message)}</span></article>`).join('')}</div>`:'<div class="feedback ok">✅ Sin desviaciones críticas abiertas.</div>'}<div class="v32-actions"><button class="btn btn-primary" data-v32-goal>+ Objetivo</button></div><h3>Objetivos académicos</h3>${goals.length?`<div class="v32-list">${goals.map(g=>`<article><div><b>${esc(g.title)}</b><small>${esc(g.owner_name||'Sin responsable')} · vence ${esc(g.due_date||'sin fecha')}</small></div><div><strong>${Number(g.live_value||0).toFixed(1)} → ${Number(g.target_value||0).toFixed(1)}</strong><span class="${Number(g.gap||0)>0?'bad':'ok'}">brecha ${Number(g.gap||0).toFixed(1)}</span></div><div class="v32-buttons"><button class="btn btn-soft" data-v32-action="${g.id}">+ Acción</button><button class="btn btn-soft" data-v32-review="${g.id}" data-v32-value="${g.live_value||0}">Revisar</button></div></article>`).join('')}</div>`:'<div class="empty">Aún no hay objetivos de gobierno académico.</div>'}<h3>Acciones y compromisos</h3>${acts.length?`<div class="v32-list">${acts.map(a=>`<article><div><b>${esc(a.title)}</b><small>${esc(a.owner_name||'Sin responsable')} · ${esc(a.due_date||'sin fecha')}</small></div><div><strong>${esc(a.status)}</strong><span>${esc(a.expected_impact||'')}</span></div>${a.status==='open'?`<button class="btn btn-soft" data-v32-done="${a.id}">Marcar hecha</button>`:''}</article>`).join('')}</div>`:'<div class="empty">No hay acciones registradas.</div>'}</section>`}
function render32(){const old=document.querySelector('#v32-governance');if(old)old.outerHTML=panel();else inject();bind()}
async function load(){if(!ok())return;try{V32.data=await req('/governance');render32()}catch(e){console.warn('V32',e)}}
function inject(){if(!ok()||!['school','reports','teacher'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('#v32-governance'))return;main.insertAdjacentHTML('beforeend',panel());bind();if(!V32.data)load()}
function bind(){document.querySelector('[data-v32-refresh]')?.addEventListener('click',load);document.querySelector('[data-v32-goal]')?.addEventListener('click',async()=>{const title=prompt('Objetivo académico');if(!title)return;const metric=prompt('Métrica: readiness, accuracy, reading, listening, writing, speaking o risk_count','reading')||'reading';const target=prompt('Meta numérica','78');if(target===null)return;const due=prompt('Fecha objetivo YYYY-MM-DD','2026-12-15')||'';await req('/governance/goals',{method:'POST',body:{title,metric,target_value:Number(target),due_date:due}});load()});document.querySelectorAll('[data-v32-action]').forEach(b=>b.addEventListener('click',async()=>{const title=prompt('Acción/compromiso');if(!title)return;const impact=prompt('Impacto esperado','Mejorar el indicador antes de la próxima revisión')||'';const due=prompt('Fecha YYYY-MM-DD','2026-09-30')||'';await req('/governance/actions',{method:'POST',body:{goal_id:Number(b.dataset.v32Action),title,expected_impact:impact,due_date:due}});load()}));document.querySelectorAll('[data-v32-review]').forEach(b=>b.addEventListener('click',async()=>{const observed=Number(prompt('Valor observado',b.dataset.v32Value));if(!Number.isFinite(observed))return;const decision=prompt('Decisión: continue, close, adjust o escalate','continue')||'continue';const note=prompt('Nota de revisión','')||'';await req('/governance/review',{method:'POST',body:{goal_id:Number(b.dataset.v32Review),observed_value:observed,decision,note}});load()}));document.querySelectorAll('[data-v32-done]').forEach(b=>b.addEventListener('click',async()=>{await req('/governance/actions/status',{method:'POST',body:{action_id:Number(b.dataset.v32Done),status:'done'}});load()}))}
const css=`.v32{margin-top:16px}.v32-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.v32-kpis>div{padding:12px;border-radius:14px;background:#f7f7fc}.v32-kpis span,.v32-kpis b{display:block}.v32-kpis b{font-size:1.35rem}.v32-alerts{display:grid;gap:8px;margin:12px 0}.v32-alerts article{padding:10px;border-left:4px solid #c2410c;background:#fff7ed;border-radius:10px}.v32-alerts span,.v32-list small,.v32-list span{display:block}.v32-list{display:grid;gap:8px}.v32-list article{display:grid;grid-template-columns:1.5fr 1fr auto;gap:10px;align-items:center;padding:12px;background:#fafafe;border-radius:14px}.v32-buttons{display:flex;gap:6px;flex-wrap:wrap}.v32-actions{margin:12px 0}@media(max-width:760px){.v32-kpis{grid-template-columns:1fr 1fr}.v32-list article{grid-template-columns:1fr}}`;
if(!document.getElementById('v32-css')){const st=document.createElement('style');st.id='v32-css';st.textContent=css;document.head.appendChild(st)}
const prev=render;render=function(){prev();requestAnimationFrame(inject)};window.PETQUEST_V32={load,version:'32.0'};requestAnimationFrame(inject)
})();
