(()=>{
const V33={data:null};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ok(){return typeof API!=='undefined'&&API.user&&['school','admin'].includes(API.user.role)}
async function req(path,opt={}){return apiRequest(path,opt)}
const L={reading:'Reading',listening:'Listening',writing:'Writing',speaking:'Speaking',readiness:'Readiness',accuracy:'Precisión'};
function forecastCards(d){const f=d.forecast||{};return ['30','60','90'].map(h=>{const x=f[h]?.readiness||{};return `<article><small>${h} días</small><b>${Math.round(x.with_action||0)}%</b><span>si actuamos</span><em>${Math.round(x.no_action||0)}% sin acción</em></article>`}).join('')}
function panel(){const d=V33.data||{},c=d.current||{},cap=d.capacity||{},targets=d.strategic_targets||[];const sk=d.priority_skill||'reading';return `<section class="card v33" id="v33-strategy"><div class="section-title"><div><span class="mission-label">V33 · Academic Strategy & Forecasting</span><h2>🔭 Estrategia y proyección académica</h2><p>Escenarios 30/60/90 días, metas anuales y capacidad orientativa.</p></div><button class="btn btn-soft" data-v33-refresh>Actualizar</button></div><div class="v33-note"><b>Confianza ${esc(d.confidence||'low')}</b><span>${esc(d.method_note||'')}</span></div><div class="v33-kpis"><div><span>Readiness actual</span><b>${Math.round(c.readiness||0)}%</b></div><div><span>Prioridad</span><b>${esc(L[sk]||sk)}</b></div><div><span>Riesgo</span><b>${c.risk_count||0}</b></div><div><span>Ganancia histórica intervención</span><b>+${Number(d.historic_intervention_gain||0).toFixed(1)}</b></div></div><h3>Escenarios de preparación</h3><div class="v33-forecast">${forecastCards(d)}</div><p class="muted">El escenario “si actuamos” usa solo una fracción conservadora del impacto histórico; no es una promesa.</p><h3>Capacidad orientativa</h3><div class="v33-cap"><div><b>${cap.suggested_groups||0}</b><span>grupos sugeridos</span></div><div><b>${cap.teacher_hours_week||0} h</b><span>docente/semana</span></div><div><b>${cap.students_per_group||6}</b><span>alumnos/grupo</span></div></div><small>${esc(cap.assumption||'')}</small><div class="v33-actions"><button class="btn btn-primary" data-v33-target>+ Meta anual</button></div><h3>Metas estratégicas</h3>${targets.length?`<div class="v33-list">${targets.map(t=>`<article><div><b>${esc(t.year)} · ${esc(L[t.metric]||t.metric)}</b><small>${esc(t.owner_name||'Sin responsable')}</small></div><strong>${Number(t.target_value||0).toFixed(1)}${t.metric==='risk_count'?'':'%'}</strong></article>`).join('')}</div>`:'<div class="empty">Aún no hay metas anuales registradas.</div>'}</section>`}
function inject(){if(!ok()||!['school','reports','teacher'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('#v33-strategy'))return;main.insertAdjacentHTML('beforeend',panel());bind();if(!V33.data)load()}
function render33(){const old=document.querySelector('#v33-strategy');if(old)old.outerHTML=panel();else inject();bind()}
async function load(){if(!ok())return;try{V33.data=await req('/strategy-forecast');render33()}catch(e){console.warn('V33',e)}}
function bind(){document.querySelector('[data-v33-refresh]')?.addEventListener('click',load);document.querySelector('[data-v33-target]')?.addEventListener('click',async()=>{const metric=(prompt('Métrica: readiness, accuracy, reading, listening, writing, speaking o risk_count','readiness')||'').toLowerCase();if(!metric)return;const target=prompt('Meta anual','80');if(target===null)return;const year=prompt('Año',String(new Date().getFullYear()));if(year===null)return;const note=prompt('Nota estratégica','')||'';await req('/strategy-targets',{method:'POST',body:{metric,target_value:Number(target),year:Number(year),note}});load()})}
const css=`.v33{margin-top:16px}.v33-note{padding:12px;border-radius:14px;background:#eef6ff;display:grid;gap:4px}.v33-kpis,.v33-cap{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.v33-kpis>div,.v33-cap>div,.v33-forecast article{padding:12px;border-radius:14px;background:#f8f8fc}.v33-kpis span,.v33-kpis b,.v33-cap span,.v33-cap b,.v33-forecast span,.v33-forecast b,.v33-forecast em{display:block}.v33-kpis b,.v33-cap b,.v33-forecast b{font-size:1.35rem}.v33-forecast{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.v33-forecast article{background:#f3fbf6}.v33-forecast em{font-style:normal;color:#667085}.v33-list{display:grid;gap:8px}.v33-list article{display:flex;justify-content:space-between;align-items:center;padding:12px;background:#fafafe;border-radius:14px}.v33-list small{display:block}.v33-actions{margin:12px 0}@media(max-width:760px){.v33-kpis{grid-template-columns:1fr 1fr}.v33-forecast,.v33-cap{grid-template-columns:1fr}}`;
if(!document.getElementById('v33-css')){const st=document.createElement('style');st.id='v33-css';st.textContent=css;document.head.appendChild(st)}
const prev=render;render=function(){prev();requestAnimationFrame(inject)};window.PETQUEST_V33={load,version:'33.0'};requestAnimationFrame(inject)
})();
