(()=>{
const V34={meta:null,results:[]};const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const LABEL={reading:'Reading',listening:'Listening',writing:'Writing',speaking:'Speaking'};
function allowed(){return typeof API!=='undefined'&&API.user&&['school','admin'].includes(API.user.role)}
async function rq(path,opt={}){return apiRequest(path,opt)}
function card(r,i){const x=r.expected||{},e=r.effort||{},inp=r.inputs||{};return `<article class="v34-scenario"><header><b>${E(r.name||`Escenario ${i+1}`)}</b><span class="v34-confidence ${E(r.confidence)}">${E(r.confidence)}</span></header><div class="v34-big">+${Number(x.skill_delta||0).toFixed(1)} pts</div><small>${E(LABEL[inp.target_skill]||inp.target_skill)} · rango ${Number((x.skill_delta_range||[0])[0]).toFixed(1)}–${Number((x.skill_delta_range||[0,0])[1]).toFixed(1)}</small><div class="v34-mini"><span><b>${e.teacher_hours_total||0}h</b> esfuerzo</span><span><b>${e.students_covered||0}</b> alumnos</span><span><b>${r.efficiency_index||0}</b> eficiencia</span></div><p>${E(r.recommendation||'')}</p></article>`}
function view(){const m=V34.meta||{},cur=m.current||{},best=V34.results.slice().sort((a,b)=>(b.efficiency_index||0)-(a.efficiency_index||0))[0];return `<section class="card v34" id="v34-simulator"><div class="section-title"><div><span class="mission-label">V34 · Academic Decision Simulator</span><h2>🧮 Simulador de decisiones académicas</h2><p>Compara impacto esperado, cobertura y esfuerzo antes de comprometer recursos.</p></div><button class="btn btn-soft" data-v34-refresh>Actualizar</button></div><div class="v34-warning"><b>Simulación, no garantía.</b><span>${E(m.model_note||'')}</span></div><div class="v34-kpis"><div><span>Readiness</span><b>${Math.round(cur.readiness||0)}%</b></div><div><span>Prioridad actual</span><b>${E(LABEL[m.priority_skill]||m.priority_skill||'—')}</b></div><div><span>Riesgo</span><b>${cur.risk_count||0}</b></div><div><span>Intervenciones históricas</span><b>${m.historic_intervention_count||0}</b></div></div><div class="v34-controls"><label>Horas docentes extra / semana<input data-v34-hours type="number" min="0" max="12" step="0.5" value="2"></label><label>Semanas<input data-v34-weeks type="number" min="1" max="16" value="8"></label><label>Habilidad<select data-v34-skill>${['reading','listening','writing','speaking'].map(s=>`<option value="${s}" ${s===m.priority_skill?'selected':''}>${LABEL[s]}</option>`).join('')}</select></label><label>Cobertura<select data-v34-coverage><option value="risk_only">Mayor riesgo</option><option value="priority">Necesidad en habilidad</option><option value="all">Todos con evidencia</option></select></label><label>Intensidad<select data-v34-intensity><option value="standard">Estándar</option><option value="intensive">Intensiva</option></select></label><button class="btn btn-primary" data-v34-run>Simular escenario</button></div><div class="v34-presets"><button class="btn btn-soft" data-v34-presets>Comparar 4 escenarios sugeridos</button></div>${best?`<div class="v34-best"><b>Mejor eficiencia relativa ahora:</b> ${E(best.name||'Escenario')} · índice ${best.efficiency_index}</div>`:''}<div class="v34-grid">${V34.results.map(card).join('')}</div></section>`}
function mount(){if(!allowed()||!['school','reports','teacher'].includes(state.view))return;const main=document.querySelector('main.container');if(!main)return;const old=main.querySelector('#v34-simulator');if(old)old.outerHTML=view();else main.insertAdjacentHTML('beforeend',view());bind()}
async function meta(){if(!API?.token||!allowed()||!['school','reports','teacher'].includes(state.view))return;try{V34.meta=await rq('/decision-simulator');mount()}catch(e){console.warn('V34 meta',e)}}
async function simulate(inp,name){const r=await rq('/decision-simulator/run',{method:'POST',body:inp});r.name=name||'Escenario personalizado';return r}
async function runOne(){const q=s=>document.querySelector(s);const inp={extra_teacher_hours:Number(q('[data-v34-hours]')?.value||0),weeks:Number(q('[data-v34-weeks]')?.value||8),target_skill:q('[data-v34-skill]')?.value||'reading',coverage:q('[data-v34-coverage]')?.value||'risk_only',intensity:q('[data-v34-intensity]')?.value||'standard'};try{V34.results=[await simulate(inp,'Escenario personalizado'),...V34.results].slice(0,6);mount()}catch(e){alert('No se pudo ejecutar la simulación.') }}
async function presets(){if(!V34.meta)return;const out=[];for(const p of V34.meta.presets||[]){const {name,...inp}=p;delete inp.id;out.push(await simulate(inp,name))}V34.results=out;mount()}
function bind(){document.querySelector('[data-v34-refresh]')?.addEventListener('click',meta);document.querySelector('[data-v34-run]')?.addEventListener('click',runOne);document.querySelector('[data-v34-presets]')?.addEventListener('click',()=>presets().catch(()=>alert('No se pudieron comparar los escenarios.')))}
const css=`.v34{margin-top:16px}.v34-warning{padding:12px 14px;border-radius:14px;background:#fff7e8;display:grid;gap:3px}.v34-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.v34-kpis>div,.v34-scenario{background:#f8f8fc;border-radius:14px;padding:12px}.v34-kpis span,.v34-kpis b{display:block}.v34-kpis b{font-size:1.25rem}.v34-controls{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;align-items:end}.v34-controls label{display:grid;gap:4px;font-size:.84rem}.v34-controls input,.v34-controls select{min-height:42px;border:1px solid #d9d9e5;border-radius:10px;padding:8px;background:white}.v34-controls .btn{min-height:42px}.v34-presets{margin:12px 0}.v34-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.v34-scenario header{display:flex;justify-content:space-between;gap:8px}.v34-confidence{padding:2px 8px;border-radius:999px;background:#eee;font-size:.75rem}.v34-confidence.high{background:#e9f8ee}.v34-confidence.low{background:#fff1ed}.v34-big{font-size:1.8rem;font-weight:800;margin-top:8px}.v34-mini{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:10px 0}.v34-mini span{padding:7px;background:white;border-radius:10px;font-size:.8rem}.v34-mini b{display:block}.v34-best{padding:10px 12px;background:#eef8ff;border-radius:12px;margin-bottom:10px}@media(max-width:900px){.v34-controls{grid-template-columns:1fr 1fr}.v34-grid{grid-template-columns:1fr}}@media(max-width:600px){.v34-kpis,.v34-controls{grid-template-columns:1fr 1fr}.v34-mini{grid-template-columns:1fr}}`;
if(!document.getElementById('v34-css')){const st=document.createElement('style');st.id='v34-css';st.textContent=css;document.head.appendChild(st)}
const oldRender=render;render=function(){oldRender();requestAnimationFrame(()=>{mount();if(API?.token&&allowed()&&['school','reports','teacher'].includes(state.view)&&!V34.meta)meta()})};window.PETQUEST_V34={version:'34.0',meta,simulate};requestAnimationFrame(()=>{mount();if(API?.token&&allowed()&&['school','reports','teacher'].includes(state.view)&&!V34.meta)meta()})
})();
