(()=>{
const V35={meta:null,result:null};const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const L={reading:'Reading',listening:'Listening',writing:'Writing',speaking:'Speaking'};function ok(){return typeof API!=='undefined'&&API.user&&['school','admin'].includes(API.user.role)};const rq=(p,o={})=>apiRequest(p,o);
function plan(x,i){return `<article class="v35-plan"><header><b>${i===0?'🏆 Mejor combinación':'Alternativa '+(i+1)}</b><span>${E(x.confidence)}</span></header><div class="v35-big">+${Number(x.expected_delta||0).toFixed(1)} pts</div><p><b>${E(L[x.skill]||x.skill)}</b> · ${E(x.coverage)} · ${E(x.intensity)}</p><div class="v35-mini"><span><b>${x.hours_week}h</b>/sem</span><span><b>${x.students_covered}</b> alumnos</span><span><b>${Number(x.cost||0).toFixed(0)}</b> costo</span><span><b>${Number((x.range||[0])[0]).toFixed(1)}–${Number((x.range||[0,0])[1]).toFixed(1)}</b> rango</span></div></article>`}
function view(){const m=V35.meta||{},d=m.defaults||{},r=V35.result||{},b=r.best_plan;return `<section class="card v35" id="v35-budget"><div class="section-title"><div><span class="mission-label">V35 · Budget & Resource Optimization</span><h2>💰 Optimización de presupuesto y recursos</h2><p>Busca la mejor combinación factible de intervención dentro de límites reales.</p></div><button class="btn btn-soft" data-v35-refresh>Actualizar</button></div><div class="v35-note"><b>Optimización orientativa, no garantía.</b><span>${E(r.method_note||m.method_note||'')}</span></div><div class="v35-controls"><label>Presupuesto máximo<input data-v35-budget type="number" min="0" step="50" value="${r.constraints?.budget??d.budget??1200}"></label><label>Costo/hora docente<input data-v35-cost type="number" min="1" step="1" value="${r.constraints?.cost_per_hour??d.cost_per_hour??30}"></label><label>Horas máx./sem<input data-v35-hours type="number" min="0" max="40" step="0.5" value="${r.constraints?.max_hours_week??d.max_hours_week??6}"></label><label>Semanas<input data-v35-weeks type="number" min="1" max="24" value="${r.constraints?.weeks??d.weeks??8}"></label><label>Estrategia<select data-v35-strategy><option value="balanced">Equilibrada</option><option value="risk_first">Priorizar riesgo</option><option value="priority_skill">Priorizar habilidad débil</option><option value="max_coverage">Máxima cobertura</option></select></label><label>Habilidad<select data-v35-skill><option value="">Automática</option>${Object.keys(L).map(k=>`<option value="${k}">${L[k]}</option>`).join('')}</select></label><button class="btn btn-primary" data-v35-run>Optimizar</button></div>${b?`<div class="v35-summary"><div><span>Presupuesto usado</span><b>${Number(r.budget_used||0).toFixed(0)}</b></div><div><span>Disponible</span><b>${Number(r.budget_remaining||0).toFixed(0)}</b></div><div><span>Impacto esperado</span><b>+${Number(b.expected_delta||0).toFixed(1)}</b></div><div><span>Cobertura</span><b>${b.students_covered}</b></div></div>`:''}${!b&&V35.result?'<div class="v35-empty">No hay escenarios factibles con estas restricciones. Aumenta presupuesto/horas o cambia la cobertura.</div>':''}<div class="v35-grid">${(r.alternatives||[]).map(plan).join('')}</div></section>`}
function mount(){if(!ok()||!['school','reports','teacher'].includes(state.view))return;const main=document.querySelector('main.container');if(!main)return;const old=main.querySelector('#v35-budget');if(old)old.outerHTML=view();else main.insertAdjacentHTML('beforeend',view());bind()}
async function meta(){if(!API?.token||!ok()||!['school','reports','teacher'].includes(state.view))return;try{V35.meta=await rq('/budget-optimizer');mount()}catch(e){console.warn('V35 meta',e)}}
async function run(){const q=s=>document.querySelector(s);const body={budget:Number(q('[data-v35-budget]')?.value||0),cost_per_hour:Number(q('[data-v35-cost]')?.value||1),max_hours_week:Number(q('[data-v35-hours]')?.value||0),weeks:Number(q('[data-v35-weeks]')?.value||8),strategy:q('[data-v35-strategy]')?.value||'balanced',target_skill:q('[data-v35-skill]')?.value||''};try{V35.result=await rq('/budget-optimizer/run',{method:'POST',body});mount()}catch(e){alert('No se pudo optimizar con estas restricciones.')}}
function bind(){document.querySelector('[data-v35-refresh]')?.addEventListener('click',meta);document.querySelector('[data-v35-run]')?.addEventListener('click',run)}
const css=`.v35{margin-top:16px}.v35-note{padding:12px 14px;background:#eef8ff;border-radius:14px;display:grid;gap:3px}.v35-controls{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;align-items:end;margin:12px 0}.v35-controls label{display:grid;gap:4px;font-size:.82rem}.v35-controls input,.v35-controls select{min-height:42px;border:1px solid #d9d9e5;border-radius:10px;padding:8px;background:#fff}.v35-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.v35-summary>div,.v35-plan{padding:12px;background:#f8f8fc;border-radius:14px}.v35-summary span,.v35-summary b{display:block}.v35-summary b{font-size:1.3rem}.v35-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.v35-plan header{display:flex;justify-content:space-between}.v35-big{font-size:1.8rem;font-weight:800;margin:8px 0}.v35-mini{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.v35-mini span{padding:7px;background:#fff;border-radius:9px;font-size:.78rem}.v35-mini b{display:block}.v35-empty{padding:14px;background:#fff6f3;border-radius:12px}@media(max-width:950px){.v35-controls{grid-template-columns:1fr 1fr 1fr}.v35-grid{grid-template-columns:1fr}}@media(max-width:620px){.v35-controls,.v35-summary{grid-template-columns:1fr 1fr}.v35-mini{grid-template-columns:1fr 1fr}}`;
if(!document.getElementById('v35-css')){const st=document.createElement('style');st.id='v35-css';st.textContent=css;document.head.appendChild(st)}
const oldRender=render;render=function(){oldRender();requestAnimationFrame(()=>{mount();if(API?.token&&ok()&&['school','reports','teacher'].includes(state.view)&&!V35.meta)meta()})};window.PETQUEST_V35={version:'35.0',meta,run};requestAnimationFrame(()=>{mount();if(API?.token&&ok()&&['school','reports','teacher'].includes(state.view)&&!V35.meta)meta()});
})();
