(()=>{
const V36={meta:null,result:null};
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const L={reading:'Reading',listening:'Listening',writing:'Writing',speaking:'Speaking'};
function ok(){return typeof API!=='undefined'&&API.user&&['school','admin'].includes(API.user.role)}
const rq=(p,o={})=>apiRequest(p,o);
function planCard(p,i){return `<article class="v36-plan"><header><div><span>${i===0?'🏆 Portafolio recomendado':'Alternativa '+(i+1)}</span><b>${p.intervention_count} intervenciones</b></div><strong>+${Number(p.institutional_equivalent_gain||0).toFixed(2)} pts eq.</strong></header><div class="v36-kpis"><span><b>${Number(p.budget_used||0).toFixed(0)}</b> presupuesto</span><span><b>${Number(p.hours_week_used||0).toFixed(1)}h</b>/sem</span><span><b>${p.unique_students}</b> alumnos únicos</span><span><b>${p.overlap_events}</b> solapamientos</span></div><div class="v36-lines">${(p.plans||[]).map(x=>`<div><b>${E(L[x.skill]||x.skill)}</b><span>${E(x.coverage)} · ${E(x.intensity)} · ${x.hours_week}h/sem · ${x.students_covered} alumnos · +${Number(x.expected_delta||0).toFixed(1)} pts</span></div>`).join('')}</div><footer><span>Impacto agregado: <b>${Number(p.expected_impact_points||0).toFixed(1)}</b></span><span>Confianza: <b>${E(p.confidence)}</b></span></footer></article>`}
function view(){const m=V36.meta||{},d=m.defaults||{},r=V36.result||{},b=r.best_portfolio;return `<section class="card v36" id="v36-portfolio"><div class="section-title"><div><span class="mission-label">V36 · Portfolio Optimizer</span><h2>🧩 Portafolio de intervenciones</h2><p>Distribuye presupuesto y horas entre varias intervenciones simultáneas sin exceder restricciones.</p></div><button class="btn btn-soft" data-v36-refresh>Actualizar</button></div><div class="v36-note"><b>Simulación de portafolio, no garantía.</b><span>${E(r.method_note||m.method_note||'')}</span></div><div class="v36-controls"><label>Presupuesto<input data-v36-budget type="number" min="0" step="50" value="${r.constraints?.budget??d.budget??1800}"></label><label>Costo/hora<input data-v36-cost type="number" min="1" step="1" value="${r.constraints?.cost_per_hour??d.cost_per_hour??30}"></label><label>Horas máx./sem<input data-v36-hours type="number" min="0" max="40" step="0.5" value="${r.constraints?.max_hours_week??d.max_hours_week??8}"></label><label>Semanas<input data-v36-weeks type="number" min="1" max="24" value="${r.constraints?.weeks??d.weeks??8}"></label><label>Máx. intervenciones<input data-v36-max type="number" min="1" max="4" value="${r.constraints?.max_interventions??d.max_interventions??3}"></label><label>Máx. solapamiento/alumno<input data-v36-overlap type="number" min="1" max="4" value="${r.constraints?.max_student_overlap??d.max_student_overlap??2}"></label><label>Estrategia<select data-v36-strategy><option value="balanced">Equilibrada</option><option value="risk_first">Priorizar riesgo</option><option value="coverage">Máxima cobertura</option><option value="weak_skills">Habilidades débiles</option></select></label><button class="btn btn-primary" data-v36-run>Optimizar portafolio</button></div>${b?`<div class="v36-summary"><div><span>Usado</span><b>${Number(b.budget_used||0).toFixed(0)}</b></div><div><span>Remanente</span><b>${Number(b.budget_remaining||0).toFixed(0)}</b></div><div><span>Impacto eq.</span><b>+${Number(b.institutional_equivalent_gain||0).toFixed(2)}</b></div><div><span>Cobertura única</span><b>${b.unique_students}</b></div><div><span>Riesgo cubierto</span><b>${b.risk_students_covered}</b></div></div>`:''}${!b&&V36.result?'<div class="v36-empty">No existe un portafolio factible con estas restricciones. Aumenta presupuesto/horas o reduce el número de intervenciones.</div>':''}<div class="v36-grid">${(r.alternatives||[]).map(planCard).join('')}</div></section>`}
function mount(){if(!ok()||!['school','reports','teacher'].includes(state.view))return;const main=document.querySelector('main.container');if(!main)return;const old=main.querySelector('#v36-portfolio');if(old)old.outerHTML=view();else main.insertAdjacentHTML('beforeend',view());bind()}
async function meta(){if(!API?.token||!ok()||!['school','reports','teacher'].includes(state.view))return;try{V36.meta=await rq('/portfolio-optimizer');mount()}catch(e){console.warn('V36 meta',e)}}
async function run(){const q=s=>document.querySelector(s);const body={budget:Number(q('[data-v36-budget]')?.value||0),cost_per_hour:Number(q('[data-v36-cost]')?.value||1),max_hours_week:Number(q('[data-v36-hours]')?.value||0),weeks:Number(q('[data-v36-weeks]')?.value||8),max_interventions:Number(q('[data-v36-max]')?.value||3),max_student_overlap:Number(q('[data-v36-overlap]')?.value||2),strategy:q('[data-v36-strategy]')?.value||'balanced'};try{V36.result=await rq('/portfolio-optimizer/run',{method:'POST',body});mount()}catch(e){alert('No se pudo construir un portafolio con estas restricciones.')}}
function bind(){document.querySelector('[data-v36-refresh]')?.addEventListener('click',meta);document.querySelector('[data-v36-run]')?.addEventListener('click',run)}
const css=`.v36{margin-top:16px}.v36-note{padding:12px 14px;background:#f2f8ff;border-radius:14px;display:grid;gap:3px}.v36-controls{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;align-items:end;margin:12px 0}.v36-controls label{display:grid;gap:4px;font-size:.82rem}.v36-controls input,.v36-controls select{min-height:42px;border:1px solid #d9d9e5;border-radius:10px;padding:8px;background:#fff}.v36-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:12px 0}.v36-summary>div{padding:11px;background:#f8f8fc;border-radius:12px}.v36-summary span,.v36-summary b{display:block}.v36-summary b{font-size:1.25rem}.v36-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.v36-plan{padding:13px;background:#f8f8fc;border-radius:15px}.v36-plan header,.v36-plan footer{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v36-plan header div{display:grid;gap:2px}.v36-plan header strong{font-size:1.45rem}.v36-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin:10px 0}.v36-kpis span{background:#fff;border-radius:9px;padding:7px;font-size:.77rem}.v36-kpis b{display:block}.v36-lines{display:grid;gap:6px}.v36-lines>div{display:grid;gap:2px;background:#fff;border-radius:10px;padding:8px}.v36-lines span{font-size:.8rem}.v36-plan footer{margin-top:10px;font-size:.8rem}.v36-empty{padding:14px;background:#fff6f3;border-radius:12px}@media(max-width:950px){.v36-controls{grid-template-columns:1fr 1fr}.v36-grid{grid-template-columns:1fr}.v36-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:620px){.v36-controls,.v36-summary,.v36-kpis{grid-template-columns:1fr 1fr}.v36-plan header,.v36-plan footer{display:grid}}`;
if(!document.getElementById('v36-css')){const st=document.createElement('style');st.id='v36-css';st.textContent=css;document.head.appendChild(st)}
const oldRender=render;render=function(){oldRender();requestAnimationFrame(()=>{mount();if(API?.token&&ok()&&['school','reports','teacher'].includes(state.view)&&!V36.meta)meta()})};window.PETQUEST_V36={version:'36.0',meta,run};requestAnimationFrame(()=>{mount();if(API?.token&&ok()&&['school','reports','teacher'].includes(state.view)&&!V36.meta)meta()});
})();
