(()=>{
const V37={data:null};const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const rq=(p,o={})=>apiRequest(p,o);function ok(){return API?.user&&['school','admin','teacher'].includes(API.user.role)}
const hm=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function view(){const d=V37.data||{};return `<section class="card v37" id="v37-schedule"><div class="section-title"><div><span class="mission-label">V37 · Schedule & Capacity Planner</span><h2>🗓️ Horario y capacidad docente</h2><p>Convierte grupos de refuerzo en sesiones ejecutables y detecta conflictos de disponibilidad.</p></div><button class="btn btn-soft" data-v37-refresh>Actualizar</button></div><div class="v37-cols"><div><h3>Disponibilidad</h3><div class="v37-form"><select data-v37-teacher>${(d.teachers||[]).map(x=>`<option value="${x.id}">${E(x.name)}</option>`).join('')}</select><select data-v37-day>${(d.weekdays||[]).map((x,i)=>`<option value="${i+1}">${x}</option>`).join('')}</select><input data-v37-start type="time" value="15:00"><input data-v37-end type="time" value="17:00"><button class="btn btn-soft" data-v37-add>Guardar franja</button></div><h3>Plan automático</h3><div class="v37-form"><label>Duración<input data-v37-duration type="number" min="20" max="90" value="30"></label><label>Sesiones/grupo<input data-v37-count type="number" min="1" max="4" value="2"></label><button class="btn btn-primary" data-v37-auto>Generar horario</button></div></div><div><h3>Sesiones programadas</h3><div class="v37-list">${(d.sessions||[]).length?(d.sessions||[]).map(x=>`<div><b>${E(x.group_name||x.label||'Sesión')}</b><span>${['','Lun','Mar','Mié','Jue','Vie'][x.weekday]} ${hm(x.start_min)} · ${x.duration_min} min · ${E(x.teacher_name||'')}</span></div>`).join(''):'<p class="muted">Aún no hay sesiones programadas.</p>'}</div></div></div></section>`}
function mount(){if(!ok()||!['school','teacher','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main)return;const old=main.querySelector('#v37-schedule');if(old)old.outerHTML=view();else main.insertAdjacentHTML('beforeend',view());bind()}
async function load(){if(!API?.token||!ok()||!['school','teacher','reports'].includes(state.view))return;try{V37.data=await rq('/schedule-planner');mount()}catch(e){console.warn('V37',e)}}
const tmin=v=>{const [h,m]=String(v||'').split(':').map(Number);return h*60+m};function bind(){document.querySelector('[data-v37-refresh]')?.addEventListener('click',load);document.querySelector('[data-v37-add]')?.addEventListener('click',async()=>{const q=s=>document.querySelector(s);await rq('/teacher-availability',{method:'POST',body:{teacher_id:+q('[data-v37-teacher]').value,weekday:+q('[data-v37-day]').value,start_min:tmin(q('[data-v37-start]').value),end_min:tmin(q('[data-v37-end]').value)}});load()});document.querySelector('[data-v37-auto]')?.addEventListener('click',async()=>{const q=s=>document.querySelector(s);const r=await rq('/schedule-planner/auto',{method:'POST',body:{duration_min:+q('[data-v37-duration]').value,sessions_per_group:+q('[data-v37-count]').value}});if(r.conflicts?.length)alert(`Horario generado con ${r.conflicts.length} conflicto(s) de capacidad.`);load()})}
const css=`.v37{margin-top:16px}.v37-cols{display:grid;grid-template-columns:1fr 1.2fr;gap:16px}.v37-form{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:8px 0 16px}.v37-form input,.v37-form select{min-height:42px;border:1px solid #ddd;border-radius:10px;padding:8px}.v37-form label{display:grid;gap:4px}.v37-list{display:grid;gap:7px}.v37-list>div{display:grid;gap:2px;padding:9px;background:#f7f7fb;border-radius:10px}.v37-list span{font-size:.82rem}@media(max-width:850px){.v37-cols{grid-template-columns:1fr}.v37-form{grid-template-columns:1fr 1fr}}`;
if(!document.getElementById('v37-css')){const st=document.createElement('style');st.id='v37-css';st.textContent=css;document.head.appendChild(st)}const old=render;render=function(){old();requestAnimationFrame(()=>{mount();if(API?.token&&ok()&&['school','teacher','reports'].includes(state.view)&&!V37.data)load()})};window.PETQUEST_V37={version:'37.0',load};requestAnimationFrame(mount);
})();
