/* PET Quest V41 - Academic Fidelity + Error Intelligence. Original practice content. */
(function(){
'use strict';
const KEY='petquest_v41_error_intelligence';
let EI={errors:[],writingReviews:[],speakingReviews:[]};try{EI=Object.assign(EI,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){}
const esc41=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save41(){localStorage.setItem(KEY,JSON.stringify(EI))}
const RULES=[
 {id:'past-go',cat:'Grammar',sub:'Past Simple',severity:'medium',re:/\b(yesterday|last\s+(?:night|week|month|year|monday|tuesday|wednesday|thursday|friday|saturday|sunday))([^.!?]{0,35})\b(i|he|she|we|they)\s+go\b/ig,fix:m=>m[0].replace(/\bgo\b/i,'went'),why:'A finished past-time expression normally needs the past simple: go → went.',lesson:'Past Simple: use the past form for finished actions.',practice:['Yesterday I ___ to the park.','Last Monday she ___ home early.','We ___ to London last summer.'],answers:['went','went','went']},
 {id:'didnt-past',cat:'Grammar',sub:'Past Simple',severity:'high',re:/\bdid(?:n['’]t| not)\s+(went|saw|had|did|made|came|took)\b/ig,fix:m=>m[0].replace(m[1],({went:'go',saw:'see',had:'have',did:'do',made:'make',came:'come',took:'take'})[m[1].toLowerCase()]||m[1]),why:'After did/didn’t, use the base form.',lesson:'did + base verb',practice:['I didn’t ___ there.','Did she ___ the film?'],answers:['go','see']},
 {id:'third-person',cat:'Grammar',sub:'Subject-verb agreement',severity:'medium',re:/\b(he|she|it)\s+(go|do|have)\b/ig,fix:m=>m[1]+' '+({go:'goes',do:'does',have:'has'})[m[2].toLowerCase()],why:'In the present simple, he/she/it needs the third-person form.',lesson:'he/she/it + verb-s',practice:['She ___ to school every day.','He ___ his homework after dinner.'],answers:['goes','does']},
 {id:'be-profession',cat:'Grammar',sub:'Articles',severity:'medium',re:/\b(?:be|become)\s+(engineer|artist|architect|actor|doctor|teacher)\b/ig,fix:m=>m[0].replace(/\s(\w+)$/,' an $1').replace(/ an (doctor|teacher)$/,' a $1'),why:'A singular profession normally needs a/an.',lesson:'Use a/an before a singular job.',practice:['She wants to be ___ engineer.','He is ___ teacher.'],answers:['an','a']},
 {id:'interested-prep',cat:'Grammar',sub:'Prepositions',severity:'medium',re:/\binterested\s+(on|at|about)\b/ig,fix:m=>m[0].replace(m[1],'in'),why:'The usual collocation is interested in.',lesson:'Adjective + preposition: interested in.',practice:['I am interested ___ science.'],answers:['in']},
 {id:'agree',cat:'Grammar',sub:'Verb patterns',severity:'medium',re:/\bI\s+am\s+agree\b/ig,fix:()=> 'I agree',why:'Agree is a verb here: I agree.',lesson:'Use “I agree”, not “I am agree”.',practice:['I ___ with you.'],answers:['agree']},
 {id:'very-fun',cat:'Lexis',sub:'Collocation',severity:'low',re:/\bvery\s+fun\b/ig,fix:()=> 'a lot of fun',why:'“A lot of fun” or “great fun” is more natural here.',lesson:'Natural collocation: a lot of fun.',practice:['The trip was ___ .'],answers:['a lot of fun']},
 {id:'people-is',cat:'Grammar',sub:'Agreement',severity:'high',re:/\bpeople\s+is\b/ig,fix:()=> 'people are',why:'People is plural, so use are.',lesson:'Plural subject + plural verb.',practice:['People ___ friendly here.'],answers:['are']},
 {id:'information-plural',cat:'Lexis',sub:'Countability',severity:'medium',re:/\binformations\b/ig,fix:()=> 'information',why:'Information is uncountable in English.',lesson:'Use information, not informations.',practice:['Can you give me some ___?'],answers:['information']}
];
function detectErrors(text){const out=[];for(const r of RULES){r.re.lastIndex=0;let m;while((m=r.re.exec(text))){const original=m[0],replacement=typeof r.fix==='function'?r.fix(m):r.fix;out.push({rule:r.id,category:r.cat,subcompetence:r.sub,severity:r.severity,original,correction:replacement,explanation:r.why,miniLesson:r.lesson,practice:r.practice,practiceAnswers:r.answers,index:m.index});if(m.index===r.re.lastIndex)r.re.lastIndex++}}return out}
function errorRecurrence(errors){const old=EI.errors;return errors.map(e=>({...e,recurrence:1+old.filter(x=>x.rule===e.rule).length,mastery:Math.max(10,100-(1+old.filter(x=>x.rule===e.rule).length)*18)}))}
function contentCoverage(text,part){const l=text.toLowerCase();if(part===1)return [['club',/club|activity/],['reason',/because|reason|chose|choose/],['invite',/join|come|with me|together/]].filter(x=>x[1].test(l)).length;return Math.min(3,(text.match(/[.!?]/g)||[]).length>=5?3:2)}
function writingEval41(text){const words=text.trim().split(/\s+/).filter(Boolean),n=words.length,low=text.toLowerCase(),errors=errorRecurrence(detectErrors(text));const severe=errors.filter(e=>e.severity==='high').length,med=errors.filter(e=>e.severity==='medium').length;const links=(low.match(/\b(because|but|so|when|although|however|first|then|finally|also|while|after|before)\b/g)||[]).length;const sentences=(text.match(/[.!?]+/g)||[]).length;const coverage=contentCoverage(text,(state.idx||0)+1);const content=Math.max(0,Math.min(5,coverage>=3?5:coverage===2?3:coverage===1?1:0));const comm=Math.max(0,Math.min(5,(n>=80&&n<=130?4:n>=60?3:2)+(coverage>=3?1:0)-(severe?1:0)));const org=Math.max(0,Math.min(5,1+(sentences>=4?1:0)+Math.min(3,links)));let lang=5-Math.min(4,severe*2+med+Math.floor(errors.filter(e=>e.severity==='low').length/2));if(n<40)lang=Math.min(lang,2);lang=Math.max(0,lang);const total=content+comm+org+lang;const rec={date:new Date().toISOString(),part:(state.idx||0)+1,words:n,score:total,text,rubric:{content,communication:comm,organisation:org,language:lang},errors};EI.writingReviews.push(rec);EI.errors.push(...errors.map(e=>({...e,at:rec.date,skill:'writing'})));save41();data.writing.push(rec);data.profile.xp+=Math.max(5,total);save();return rec}
function renderErrors(errors){if(!errors.length)return '<div class="feedback ok"><b>No detecté errores de las reglas locales V41.</b><p>Aun así, un profesor/servicio lingüístico avanzado debe revisar matices que un motor de reglas no puede garantizar.</p></div>';return `<div class="v41-errors"><h3>🔎 Error Intelligence</h3>${errors.map(e=>`<article class="v41-error"><div class="row between"><b>${esc41(e.category)} · ${esc41(e.subcompetence)}</b><span class="badge">${esc41(e.severity)}</span></div><p><del>${esc41(e.original)}</del> → <b>${esc41(e.correction)}</b></p><p>${esc41(e.explanation)}</p><small>Repetición detectada: ${e.recurrence} · mastery proxy: ${e.mastery}%</small><div class="notice"><b>Mini-lección:</b> ${esc41(e.miniLesson)}<br>${e.practice.map((q,i)=>`${esc41(q)} <span class="small">(${esc41(e.practiceAnswers[i])})</span>`).join('<br>')}</div></article>`).join('')}</div>`}
function evalWriting41(text){const out=document.getElementById('writingFeedback');if(!text.trim()){out.innerHTML='<div class="feedback bad">Escribe tu respuesta antes de evaluar.</div>';return}const r=writingEval41(text);state.writingPartsDone=state.writingPartsDone||{};state.writingPartsDone[(state.idx||0)+1]=true;const both=state.writingPartsDone[1]&&state.writingPartsDone[2];out.innerHTML=`<div class="feedback ${r.score>=14?'ok':'bad'}"><b>Writing Review V41: ${r.score}/20</b><div class="rubric"><div class="stat"><b>${r.rubric.content}/5</b><span>Content</span></div><div class="stat"><b>${r.rubric.communication}/5</b><span>Communicative Achievement</span></div><div class="stat"><b>${r.rubric.organisation}/5</b><span>Organisation</span></div><div class="stat"><b>${r.rubric.language}/5</b><span>Language</span></div></div><p class="small">Cambridge-aligned formative rubric; automated result is not an official Cambridge mark.</p></div>${renderErrors(r.errors)}${both?'<div class="row action-row"><button class="btn btn-primary" data-finish-writing>Finalizar Writing y volver al panel</button></div>':''}`;document.querySelector('[data-finish-writing]')?.addEventListener('click',()=>{if(typeof completeLearningSession==='function')completeLearningSession('writing_complete');state.view='dashboard';render()})}
function speakingAuto41(){const ta=document.getElementById('speakingText'),out=document.getElementById('speakingFeedback'),text=(ta?.value||'').trim();if(!text){if(out)out.innerHTML='<div class="feedback bad">Necesito una transcripción para analizar la respuesta.</div>';return}const errors=errorRecurrence(detectErrors(text)),n=text.split(/\s+/).filter(Boolean).length,low=text.toLowerCase(),links=(low.match(/\b(and|but|because|so|also|then|however|although)\b/g)||[]).length;const gv=Math.max(0,Math.min(5,4-Math.min(4,errors.filter(e=>e.severity!=='low').length)+(n>=25?1:0)));const dm=Math.max(0,Math.min(5,1+(n>=20?1:0)+(n>=40?1:0)+(links>=2?1:0)+(links>=4?1:0)));const proxy=Math.round((gv+dm)/10*100);const rec={date:new Date().toISOString(),part:(state.idx||0)+1,transcript:text,grammarVocabulary:gv,discourseManagement:dm,transcriptProxy:proxy,errors};EI.speakingReviews.push(rec);EI.errors.push(...errors.map(e=>({...e,at:rec.date,skill:'speaking'})));save41();if(out)out.innerHTML=`<div class="feedback neutral"><b>Transcript Coach V41: ${proxy}%</b><div class="rubric"><div class="stat"><b>${gv}/5</b><span>Grammar & Vocabulary proxy</span></div><div class="stat"><b>${dm}/5</b><span>Discourse proxy</span></div><div class="stat"><b>—</b><span>Pronunciation</span></div><div class="stat"><b>—</b><span>Interactive Communication</span></div></div><p><b>Pronunciation, rhythm, stress, intonation, intelligibility and true interaction are NOT scored from text.</b> Use the human-review rubric below for these criteria.</p></div>${renderErrors(errors)}`}
// Override automated coaches after all previous layers.
window.evalWriting=evalWriting41;window.evaluateSpeakingText=speakingAuto41;
const priorBind=window.bind;window.bind=function(){priorBind();document.querySelector('[data-eval-writing]')?.addEventListener('click',e=>{e.stopImmediatePropagation();evalWriting41(document.getElementById('writingText')?.value||'')},{capture:true});document.querySelector('[data-eval-speaking]')?.addEventListener('click',e=>{e.stopImmediatePropagation();speakingAuto41()},{capture:true})};
// Part 3 pair simulator: makes/responds to suggestions; still explicitly a simulator.
const pairTurns=[
 {partner:'Why don’t we organise a picnic after school?',prompt:'Respond to the suggestion and give one reason.'},
 {partner:'That could be fun, but what if the weather is bad?',prompt:'Suggest an alternative and respond to the concern.'},
 {partner:'I like that idea. Which option should we choose in the end?',prompt:'Negotiate an agreement and give your final choice.'}
];
function injectPair(){if(state.view!=='speaking'||state.idx!==2||document.querySelector('.v41-pair'))return;const main=document.querySelector('main.container');if(!main)return;main.insertAdjacentHTML('beforeend',`<section class="card v41-pair"><h2>🤝 Part 3 · Interactive pair simulator</h2><p>Practica <b>hacer/responder sugerencias, comparar alternativas y llegar a un acuerdo</b>. Es un simulador; el examen oficial se realiza con otro candidato y examinadores.</p>${pairTurns.map((t,i)=>`<article><div class="notice"><b>Partner:</b> ${esc41(t.partner)}</div><p>${esc41(t.prompt)}</p><textarea class="textarea small-area" data-v41-pair-answer="${i}" placeholder="Your response..."></textarea></article>`).join('')}<button class="btn btn-primary" data-v41-pair-save>Guardar interacción</button></section>`);document.querySelector('[data-v41-pair-save]')?.addEventListener('click',()=>{const answers=[...document.querySelectorAll('[data-v41-pair-answer]')].map(x=>x.value.trim());localStorage.setItem('petquest_v41_pair',JSON.stringify({at:new Date().toISOString(),answers}));window.toast?.('Interacción Part 3 guardada para revisión')})}
const priorRender=window.render;window.render=function(){priorRender();requestAnimationFrame(()=>{injectPair();window.bind?.()})};

// ---- Cambridge-style Writing mock (45 minutes; Part 1 required + one Part 2 choice) ----
const WKEY='petquest_v41_writing_exam';
let WX={active:false,startedAt:null,part1:'',choice:'article',part2:'',finished:[]};try{WX=Object.assign(WX,JSON.parse(localStorage.getItem(WKEY)||'{}'))}catch(_){}
function saveWX(){localStorage.setItem(WKEY,JSON.stringify(WX))}
let wTimer=null;function wClock(ms){const m=String(Math.floor(ms/60000)).padStart(2,'0'),s=String(Math.floor(ms%60000/1000)).padStart(2,'0');return m+':'+s}
function armWTimer(){clearInterval(wTimer);wTimer=setInterval(()=>{const x=document.getElementById('v41WTimer');if(!x){clearInterval(wTimer);return}const left=Math.max(0,45*60*1000-(Date.now()-WX.startedAt));x.textContent=wClock(left);if(left<=0){clearInterval(wTimer);finishWritingExam41()}},1000)}
function startWritingExam41(){WX={active:true,startedAt:Date.now(),part1:'',choice:'article',part2:'',finished:WX.finished||[]};saveWX();state.view='writing';render()}
function writingExam41(){const left=Math.max(0,45*60*1000-(Date.now()-WX.startedAt));if(left<=0)return finishWritingExam41();el(`<div class="app-shell">${topBar()}<main class="container"><div class="mock-top"><div><h1>Writing Exam · V41</h1><p>Part 1 obligatoria + UNA tarea de Part 2 · 45 minutos</p></div><div class="timer" id="v41WTimer">${wClock(left)}</div></div><section class="card"><h2>Part 1 · Email</h2><div class="notice"><b>From: Alex</b><br>I want to join a club at your school. Which club do you think I should choose?<br><br><b>Notes:</b> tell Alex which club · explain why · invite Alex to join you one day</div><textarea id="v41W1" class="textarea" placeholder="Write about 100 words...">${esc41(WX.part1)}</textarea><div class="small"><span id="v41W1c">${WX.part1.trim().split(/\s+/).filter(Boolean).length}</span> words</div></section><section class="card"><h2>Part 2 · Choose ONE</h2><div class="nav-tabs"><button class="tab ${WX.choice==='article'?'active':''}" data-v41-wchoice="article">Article</button><button class="tab ${WX.choice==='story'?'active':''}" data-v41-wchoice="story">Story</button></div><div class="notice">${WX.choice==='article'?'<b>Article:</b> The best way to spend a free afternoon. Write an article for your school website.':'<b>Story:</b> Your story must begin: “When I opened the door, I could not believe what I saw.”'}</div><textarea id="v41W2" class="textarea" placeholder="Write about 100 words...">${esc41(WX.part2)}</textarea><div class="small"><span id="v41W2c">${WX.part2.trim().split(/\s+/).filter(Boolean).length}</span> words</div></section><div class="notice"><b>Exam mode:</b> no hints, model answers or corrections are shown until you finish.</div><button class="btn btn-primary" data-v41-wfinish>Finalizar Writing</button></main></div>`);armWTimer();bindW41()}
function finishWritingExam41(){const oldIdx=state.idx;state.idx=0;const r1=writingEval41(WX.part1);state.idx=1;const r2=writingEval41(WX.part2);state.idx=oldIdx;const rec={at:new Date().toISOString(),part1:r1,part2:r2,score:Math.round((r1.score+r2.score)/2)};WX.finished.push(rec);WX.active=false;saveWX();data.mockAttempts.push({date:rec.at,skill:'writing',score:Math.round(rec.score/20*100),total:2,source:'v41-writing-exam'});save();el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Writing Exam Review · V41','Cambridge-style task interaction')}<section class="card highlight"><div class="label">FORMATIVE RESULT</div><div class="big-number">${rec.score}/20</div><p>Average of the two task reviews. Not an official Cambridge mark.</p></section><section class="card"><h2>Part 1</h2>${renderErrors(r1.errors)}</section><section class="card"><h2>Part 2 · ${esc41(WX.choice)}</h2>${renderErrors(r2.errors)}</section><button class="btn btn-primary" data-v41-wrestart>Repeat Writing</button></main></div>`);bindW41()}
function bindW41(){document.querySelectorAll('[data-v41-wchoice]').forEach(b=>b.onclick=()=>{WX.part1=document.getElementById('v41W1')?.value||WX.part1;WX.part2=document.getElementById('v41W2')?.value||WX.part2;WX.choice=b.dataset.v41Wchoice;saveWX();render()});[['v41W1','part1','v41W1c'],['v41W2','part2','v41W2c']].forEach(([id,k,cid])=>{const t=document.getElementById(id);if(t)t.oninput=()=>{WX[k]=t.value;saveWX();const c=document.getElementById(cid);if(c)c.textContent=t.value.trim().split(/\s+/).filter(Boolean).length}});document.querySelector('[data-v41-wfinish]')?.addEventListener('click',finishWritingExam41);document.querySelector('[data-v41-wrestart]')?.addEventListener('click',startWritingExam41)}

// ---- Speaking Part 3 exam interaction override ----
function speakingPart3Exam41(){const ex=PETQUEST_V17.state.exam;const saved=JSON.parse(localStorage.getItem('petquest_v41_speaking_part3')||'{"turn":0,"answers":[]}');const turn=Math.min(saved.turn||0,pairTurns.length-1),t=pairTurns[turn];el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Speaking Exam Practice','Part 3 · Discussion with simulated candidate')}<section class="card"><div class="notice"><b>Partner:</b> ${esc41(t.partner)}</div><p>${esc41(t.prompt)}</p><textarea id="v41Part3Exam" class="textarea" placeholder="Respond naturally. Make/respond to suggestions and negotiate.">${esc41(saved.answers?.[turn]||'')}</textarea><div class="small">No model answer or hint is shown. This simulates interaction; a live candidate/examiner remains the gold standard.</div><button class="btn btn-primary" data-v41-part3-next>${turn===pairTurns.length-1?'Finish Part 3':'Next partner turn →'}</button></section></main></div>`);document.querySelector('[data-v41-part3-next]')?.addEventListener('click',()=>{saved.answers=saved.answers||[];saved.answers[turn]=document.getElementById('v41Part3Exam').value.trim();if(turn<pairTurns.length-1){saved.turn=turn+1;localStorage.setItem('petquest_v41_speaking_part3',JSON.stringify(saved));render()}else{ex.answers[2]=saved.answers.join(' | ');ex.part=3;localStorage.setItem('petquest_v17_conversation',JSON.stringify(PETQUEST_V17.state));localStorage.removeItem('petquest_v41_speaking_part3');render()}})}
const speakingBefore41=window.speaking;window.speaking=function(){const v17=window.PETQUEST_V17?.state;if(v17?.mode==='exam'&&v17.exam?.active&&v17.exam.part===2)return speakingPart3Exam41();return speakingBefore41()};

// Route Mock buttons into the faithful Writing/Speaking experiences.
const startMockBefore41=window.startMock;window.startMock=function(skill){if(skill==='writing')return startWritingExam41();if(skill==='speaking'&&window.PETQUEST_V17){PETQUEST_V17.state.mode='exam';PETQUEST_V17.state.exam.active=false;localStorage.setItem('petquest_v17_conversation',JSON.stringify(PETQUEST_V17.state));state.view='speaking';render();return}return startMockBefore41(skill)};
const writingBefore41=window.writing;window.writing=function(){if(WX.active)return writingExam41();return writingBefore41()};

window.PETQUEST_V41={version:'41.0',detectErrors,writingEval41,state:EI};
requestAnimationFrame(()=>{injectPair();window.bind?.()});
})();
