/* PET Quest V42 - Exam Content & Assessment Calibration */
(function(){
'use strict';
const K='petquest_v42';let S={errorQueue:[],lastCalibration:null};try{S=Object.assign(S,JSON.parse(localStorage.getItem(K)||'{}'))}catch(_){}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(K,JSON.stringify(S))}
const EXTRA_RULES=[
 {id:'present-perfect-time',cat:'Grammar',sub:'Present perfect vs past simple',severity:'high',re:/\bI have (went|saw|did|made|had)\b/ig,fix:m=>'I have '+({went:'gone',saw:'seen',did:'done',made:'made',had:'had'})[m[1].toLowerCase()],why:'After have/has, use the past participle.',practice:['I have ___ this film before.','She has ___ her homework.'],answers:['seen','done']},
 {id:'much-count',cat:'Grammar',sub:'Quantifiers',severity:'medium',re:/\bmuch (friends|people|books|students|things|ideas)\b/ig,fix:m=>'many '+m[1],why:'Use many with plural countable nouns.',practice:['There are ___ students in the club.'],answers:['many']},
 {id:'fewer-less',cat:'Grammar',sub:'Quantifiers',severity:'low',re:/\bless (students|people|books|cars|questions)\b/ig,fix:m=>'fewer '+m[1],why:'Use fewer with plural countable nouns.',practice:['There were ___ people today.'],answers:['fewer']},
 {id:'enjoy-inf',cat:'Grammar',sub:'Verb patterns',severity:'medium',re:/\benjoy(?:s|ed)? to ([a-z]+)\b/ig,fix:m=>m[0].replace(/to ([a-z]+)/i,m[1]+'ing'),why:'Enjoy is normally followed by -ing.',practice:['I enjoy ___ books.'],answers:['reading']},
 {id:'suggest-inf',cat:'Grammar',sub:'Verb patterns',severity:'medium',re:/\bsuggest(?:ed|s)? to ([a-z]+)\b/ig,fix:m=>m[0].replace(/to ([a-z]+)/i,m[1]+'ing'),why:'Suggest is commonly followed by -ing or a that-clause.',practice:['She suggested ___ by bus.'],answers:['going']},
 {id:'make-homework',cat:'Lexis',sub:'Collocation',severity:'medium',re:/\bmake(?:s|d)? (?:my|your|his|her|our|their)?\s*homework\b/ig,fix:m=>m[0].replace(/^make(?:s|d)?/i,'do'),why:'The usual collocation is do homework.',practice:['I usually ___ my homework at 6.'],answers:['do']},
 {id:'depend-of',cat:'Lexis',sub:'Prepositions',severity:'medium',re:/\bdepend(?:s|ed)? of\b/ig,fix:m=>m[0].replace(/ of$/i,' on'),why:'The usual collocation is depend on.',practice:['It depends ___ the weather.'],answers:['on']},
 {id:'good-in',cat:'Lexis',sub:'Prepositions',severity:'low',re:/\bgood in (maths|english|science|sport|sports)\b/ig,fix:m=>m[0].replace(' in ',' at '),why:'Use good at for ability.',practice:['She is good ___ maths.'],answers:['at']}
];
function extraErrors(text){const out=[];for(const r of EXTRA_RULES){r.re.lastIndex=0;let m;while((m=r.re.exec(text))){out.push({rule:r.id,category:r.cat,subcompetence:r.sub,severity:r.severity,original:m[0],correction:r.fix(m),explanation:r.why,miniLesson:r.why,practice:r.practice,practiceAnswers:r.answers,index:m.index});if(m.index===r.re.lastIndex)r.re.lastIndex++}}return out}
const prevDetect=window.PETQUEST_V41?.detectErrors;
function detect42(text){const base=prevDetect?prevDetect(text):[];const add=extraErrors(text);const seen=new Set();return [...base,...add].filter(e=>{const k=e.rule+'|'+e.index;if(seen.has(k))return false;seen.add(k);return true})}
function mastery(errors){const counts={};errors.forEach(e=>counts[e.rule]=(counts[e.rule]||0)+1);return Object.entries(counts).map(([rule,count])=>({rule,count,mastery:Math.max(10,100-count*15)})).sort((a,b)=>a.mastery-b.mastery)}
function correctiveQueue(errors){const rank={high:0,medium:1,low:2};return errors.slice().sort((a,b)=>(rank[a.severity]??9)-(rank[b.severity]??9)).slice(0,5).map(e=>({rule:e.rule,subcompetence:e.subcompetence,severity:e.severity,lesson:e.miniLesson,practice:e.practice,answers:e.practiceAnswers}))}
async function syncErrors42(errors,skill,part){if(!errors?.length||!window.apiRequest)return;const events=errors.map(e=>({skill,part,competence:e.category,subcompetence:e.subcompetence,error_code:e.rule,severity:e.severity,original_text:e.original,correction:e.correction,mastery_proxy:Math.max(10,100-(e.recurrence||1)*18),occurred_at:new Date().toISOString(),source:'v42-error-intelligence'}));try{await apiRequest('/academic-errors',{method:'POST',body:{events}})}catch(_){}}
function inject42(){
 if(state.view==='writing')requestAnimationFrame(()=>{const main=document.querySelector('main.container');if(!main||main.querySelector('.v42-intel'))return;const text=document.getElementById('writingText')?.value||'';const errs=detect42(text);S.errorQueue=correctiveQueue(errs);save();main.insertAdjacentHTML('beforeend',`<section class="card v42-intel"><h2>🧠 PET Error Intelligence V42</h2><p>Prioriza patrones recurrentes por competencia y genera práctica correctiva. El motor local es formativo y no sustituye revisión lingüística humana.</p>${errs.length?`<div class="v42-patterns">${mastery(errs).map(x=>`<span class="badge">${esc(x.rule)} · mastery ${x.mastery}%</span>`).join(' ')}</div><h3>Práctica correctiva priorizada</h3>${S.errorQueue.map(q=>`<article class="notice"><b>${esc(q.subcompetence)}</b> · ${esc(q.severity)}<br>${q.practice.map((p,i)=>`${esc(p)} <span class="small">→ ${esc(q.answers[i])}</span>`).join('<br>')}</article>`).join('')}`:'<div class="feedback ok">No hay patrones V42 detectados en el texto actual.</div>'}</section>`)});
 if(['teacher','school','reports'].includes(state.view))requestAnimationFrame(()=>calibrationPanel42());
}
async function calibrationPanel42(){const main=document.querySelector('main.container');if(!main||main.querySelector('.v42-calibration'))return;let cal=null;try{cal=await apiRequest('/academic-calibration')}catch(_){};if(!cal)return;S.lastCalibration=cal;save();const label={insufficient:'Evidencia insuficiente',provisional:'Calibración provisional','evidence-building':'Evidencia amplia; requiere validación externa'}[cal.status]||cal.status;main.insertAdjacentHTML('beforeend',`<section class="card v42-calibration"><h2>📐 PET Readiness · Calibration Lab</h2><div class="rubric"><div class="stat"><b>${cal.sample_size}</b><span>Resultados reales vinculados</span></div><div class="stat"><b>${cal.classification_accuracy??'—'}${cal.classification_accuracy!=null?'%':''}</b><span>Acierto de clasificación</span></div><div class="stat"><b>${esc(label)}</b><span>Estado</span></div><div class="stat"><b>OFF</b><span>Probabilidad de aprobar</span></div></div><div class="notice"><b>No falsa precisión:</b> ${esc(cal.threshold_note)}</div></section>`)}
const prevRender=window.render;window.render=function(){prevRender();inject42()};
const prevWriting=window.PETQUEST_V41?.writingEval41;if(prevWriting){window.PETQUEST_V41.writingEval41=function(text){const r=prevWriting(text);const more=extraErrors(text);if(more.length){r.errors=[...(r.errors||[]),...more];S.errorQueue=correctiveQueue(r.errors);save();syncErrors42(r.errors,'writing',r.part||1)}return r}}
const prevEvalWriting42=window.evalWriting;window.evalWriting=function(text){const result=prevEvalWriting42?prevEvalWriting42(text):null;const errs=detect42(text||'');S.errorQueue=correctiveQueue(errs);save();syncErrors42(errs,'writing',(state.idx||0)+1);requestAnimationFrame(()=>{const out=document.getElementById('writingFeedback');if(out&&errs.length){out.insertAdjacentHTML('beforeend',`<div class="notice"><b>V42 · ${errs.length} patrón(es) detectado(s)</b><br>${S.errorQueue.map(q=>`${esc(q.subcompetence)} (${esc(q.severity)})`).join(' · ')}</div>`)}});return result};
window.PETQUEST_V42={version:'42.0',detectErrors:detect42,extraErrors,correctiveQueue,state:S};
requestAnimationFrame(inject42);
})();
