/* PET Quest V43 - Full Mock Bank & Error Remediation Engine
   Original PET Quest content only. Listening packs remain gated until studio audio is signed off. */
(function(){
'use strict';
const BASE_KEY='petquest_v4626_mock_bank';
const examProfile=()=>{try{return data?.profile?.examProfile==='adult'?'adult':'schools'}catch(_){return'schools'}};
const stateKey=()=>`${BASE_KEY}_${examProfile()}_u_${window.API?.user?.id||'anon'}`;
let V={selected:null,pack:null,active:false,part:1,answers:{},startedAt:null,finished:[],lastResult:null};
try{V=Object.assign(V,JSON.parse(localStorage.getItem(stateKey())||'{}'))}catch(_){}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().toLowerCase().replace(/^[\s.,;:!?]+|[\s.,;:!?]+$/g,'');
function save(){localStorage.setItem(stateKey(),JSON.stringify(V))}
function root(){return document.querySelector('main.container')}
async function loadPack(id){try{if(typeof apiRequest==='function'&&API?.token)return await apiRequest('/content/exam-pack/'+encodeURIComponent(id))}catch(e){console.warn('PostgreSQL exam pack fallback',e)}const r=await fetch(`exam_packs/${encodeURIComponent(id)}.json`,{cache:'no-store'});if(!r.ok)throw new Error('pack_load_failed');return r.json()}
async function loadIndex(){try{if(typeof apiRequest==='function'&&API?.token)return await apiRequest('/content/exam-index?profile='+encodeURIComponent(examProfile()))}catch(e){console.warn('PostgreSQL exam index fallback',e)}const src=examProfile()==='adult'?'exam_packs/adult_index.json':'exam_packs/index.json';const r=await fetch(src,{cache:'no-store'});if(!r.ok)throw new Error('index_load_failed');return r.json()}
function itemCount(part){return {1:5,2:5,3:5,4:5,5:6,6:6}[part]||0}
function answered(part){if(!V.pack)return 0;return V.pack.reading.filter(x=>x.part===part).filter(x=>{
 const a=V.answers[x.id]; return a!==undefined&&String(a).trim()!=='';
}).length}
function score(){let c=0;for(const q of (V.pack?.reading||[])){const a=V.answers[q.id];if(q.interaction==='open_cloze'){if(norm(a)===norm(q.answer))c++}else if(q.interaction==='multiple_choice'||q.interaction==='multiple_choice_cloze'){if(Number(a)===Number(q.answer))c++}else{if(String(a||'')===String(q.answer))c++}}return {correct:c,total:32,pct:Math.round(c/32*100)}}
function timerText(){if(!V.startedAt)return '45:00';const rem=Math.max(0,45*60*1000-(Date.now()-V.startedAt)),m=String(Math.floor(rem/60000)).padStart(2,'0'),s=String(Math.floor((rem%60000)/1000)).padStart(2,'0');return `${m}:${s}`}
function nav(){return `<div class="v43-partnav">${[1,2,3,4,5,6].map(p=>`<button data-v43-part="${p}" class="${V.part===p?'active':''}">Part ${p}<small>${answered(p)}/${itemCount(p)}</small></button>`).join('')}</div>`}
function options(q){return (q.options||[]).map((o,i)=>`<button class="option ${Number(V.answers[q.id])===i?'selected':''}" data-v43-mc="${esc(q.id)}:${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}
function keyedOptions(q){return `<select data-v43-key="${esc(q.id)}"><option value="">—</option>${(q.options||[]).map(o=>`<option value="${esc(o.key)}" ${V.answers[q.id]===o.key?'selected':''}>${esc(o.key)} · ${esc(o.title||o.text)}</option>`).join('')}</select>`}
function partHtml(){const qs=(V.pack?.reading||[]).filter(x=>x.part===V.part);if(!qs.length)return '<div class="notice">Parte no disponible.</div>';
 if(V.part===1)return `<h2>Part 1 · Multiple choice</h2>${qs.map(q=>`<article class="v43-task"><div class="v43-source"><b>${esc(q.source_label||'Notice')}</b><br>${esc(q.source_text||'')}</div><b>${esc(q.prompt)}</b><div class="options">${options(q)}</div></article>`).join('')}`;
 if(V.part===2){const bank=qs[0].options||[];return `<h2>Part 2 · Matching</h2><p>Match five people with eight activities. Three options are extra.</p><div class="v43-optionbank">${bank.map(o=>`<div><b>${esc(o.key)}. ${esc(o.title)}</b><span>${esc(o.text)}</span></div>`).join('')}</div>${qs.map((q,i)=>`<article class="v43-task"><b>${i+1}. ${esc(q.prompt)}</b>${keyedOptions(q)}</article>`).join('')}`}
 if(V.part===3){return `<h2>Part 3 · Multiple choice</h2><div class="v43-passage">${esc(qs[0].passage||'')}</div>${qs.map((q,i)=>`<article class="v43-task"><b>${i+1}. ${esc(q.prompt)}</b><div class="options">${options(q)}</div></article>`).join('')}`}
 if(V.part===4){const bank=qs[0].options||[];return `<h2>Part 4 · Gapped text</h2><div class="v43-passage">${esc(qs[0].passage||'')}</div><div class="v43-optionbank">${bank.map(o=>`<div><b>${esc(o.key)}.</b><span>${esc(o.text)}</span></div>`).join('')}</div>${qs.map((q,i)=>`<article class="v43-task"><b>Gap ${i+1}</b>${keyedOptions(q)}</article>`).join('')}`}
 if(V.part===5)return `<h2>Part 5 · Multiple-choice cloze</h2>${qs.map((q,i)=>`<article class="v43-task"><b>${i+1}. ${esc(q.prompt)}</b><div class="options">${options(q)}</div></article>`).join('')}`;
 return `<h2>Part 6 · Open cloze</h2><div class="notice"><b>Una palabra por espacio.</b> No hay opciones.</div>${qs.map((q,i)=>`<article class="v43-task"><label><b>${i+1}. ${esc(q.prompt)}</b><input data-v43-text="${esc(q.id)}" value="${esc(V.answers[q.id]||'')}" autocomplete="off" spellcheck="false" placeholder="escribe una palabra"></label></article>`).join('')}`
}
function renderExam(){const app=document.querySelector('.app-shell')||document.body;app.innerHTML=`<div class="app-shell">${typeof topBar==='function'?topBar():''}<main class="container"><div class="mock-top"><div><h1>${esc(V.pack.title)} · Reading</h1><p>Full Mock Reading original PET Quest · 32 questions</p></div><div><div class="timer" id="v43Timer">${timerText()}</div><button class="btn btn-ghost" data-v43-exit>Salir</button></div></div>${nav()}<section class="card question-card">${partHtml()}<div class="row action-row"><button class="btn btn-soft" data-v43-prev ${V.part===1?'disabled':''}>← Anterior</button><button class="btn btn-primary" data-v43-next>${V.part===6?'Finalizar Reading':'Guardar y seguir →'}</button></div></section><div class="notice">No se muestran respuestas ni pistas durante el mock. Este formulario tiene QA estructural interno; revisión académica externa aún pendiente.</div></main></div>`;bindExam();armTimer()}
let timer=null;function armTimer(){clearInterval(timer);timer=setInterval(()=>{const el=document.getElementById('v43Timer');if(!el){clearInterval(timer);return}el.textContent=timerText();if(el.textContent==='00:00'){clearInterval(timer);finish()}},1000)}
function bindExam(){document.querySelectorAll('[data-v43-part]').forEach(b=>b.onclick=()=>{V.part=+b.dataset.v43Part;save();renderExam()});document.querySelectorAll('[data-v43-mc]').forEach(b=>b.onclick=()=>{const p=b.dataset.v43Mc.lastIndexOf(':'),id=b.dataset.v43Mc.slice(0,p),v=+b.dataset.v43Mc.slice(p+1);V.answers[id]=v;save();renderExam()});document.querySelectorAll('[data-v43-key]').forEach(s=>s.onchange=()=>{V.answers[s.dataset.v43Key]=s.value;save()});document.querySelectorAll('[data-v43-text]').forEach(i=>i.oninput=()=>{V.answers[i.dataset.v43Text]=i.value;save()});document.querySelector('[data-v43-prev]')?.addEventListener('click',()=>{V.part=Math.max(1,V.part-1);save();renderExam()});document.querySelector('[data-v43-next]')?.addEventListener('click',()=>{if(V.part<6){V.part++;save();renderExam()}else finish()});document.querySelector('[data-v43-exit]')?.addEventListener('click',()=>{V.active=false;save();location.reload()})}
function finish(){clearInterval(timer);const s=score(),rec={pack_id:V.pack.pack_id,title:V.pack.title,at:new Date().toISOString(),correct:s.correct,total:s.total,pct:s.pct};const itemRows=(V.pack.reading||[]).map(q=>{const a=V.answers[q.id],isOpen=q.interaction==='open_cloze',isNum=['multiple_choice','multiple_choice_cloze'].includes(q.interaction),ok=isOpen?norm(a)===norm(q.answer):String(a??'')===String(q.answer);return {item_id:q.id,part:q.part,answer_text:isOpen?String(a||''):null,answer_option:isNum&&Number.isInteger(Number(a))?Number(a):null,is_correct:ok,response_ms:0}});try{window.apiRequest?.('/mock-attempts',{method:'POST',body:{pack_id:V.pack.pack_id,skill:'reading',started_at:new Date(V.startedAt).toISOString(),items:itemRows,source:'v44-full-mock'}})}catch(_){};V.finished=[...(V.finished||[]),rec].slice(-20);V.lastResult=rec;V.active=false;save();try{data.history.push({date:rec.at,qid:`${rec.pack_id}-reading-full`,skill:'reading',level:'B1',focus:'full-mock',correct:s.pct>=70,score:s.pct,source:'v43-full-mock-bank'})}catch(_){};const app=document.querySelector('.app-shell')||document.body;app.innerHTML=`<div class="app-shell">${typeof topBar==='function'?topBar():''}<main class="container"><section class="card hero"><h1>${esc(rec.title)} · Resultado Reading</h1><div class="stat"><b>${rec.correct}/32</b><span>${rec.pct}%</span></div><p>Resultado formativo PET Quest. No es una Cambridge English Scale oficial.</p><div class="row"><button class="btn btn-primary" data-v43-home>Volver</button><button class="btn btn-soft" data-v43-retry>Repetir formulario</button></div></section></main></div>`;document.querySelector('[data-v43-home]').onclick=()=>location.reload();document.querySelector('[data-v43-retry]').onclick=()=>startPack(rec.pack_id,true)}
async function startPack(id,restart=false){try{V.pack=await loadPack(id);if(V.pack?.audit_v46_28?.production_gate?.allowed===false){window.toast?.('Mock bloqueado: contiene items REJECTED_FOR_REVISION');V.active=false;save();return;}V.selected=id;V.active=true;V.part=1;if(restart||!V.startedAt){V.answers={};V.startedAt=Date.now()}save();renderExam()}catch(e){window.toast?.('No se pudo cargar el mock') }}
async function injectBank(){if(V.active&&V.selected){try{V.pack=V.pack||await loadPack(V.selected);return renderExam()}catch(_){V.active=false;save()}}
 const main=root();if(!main||main.querySelector('.v43-bank'))return;let idx;try{idx=await loadIndex()}catch(_){return}
 const canShow=state?.view==='reading'||['teacher','school','reports','home'].includes(state?.view);if(!canShow)return;
 main.insertAdjacentHTML('beforeend',`<section class="card v43-bank"><h2>🎓 ${examProfile()==='adult'?'B1 Preliminary – Adult':'B1 Preliminary for Schools'} · 20 Full Mocks</h2><p><b>20 formularios completos</b>: 32 Reading + 25 Listening + 2 Writing + 4 Speaking por mock. Total: 640 Reading, 500 Listening, 40 Writing y 80 Speaking parts. Contenido estructural completo; equivalencia psicométrica externa sigue pendiente.</p><div class="v43-packgrid">${idx.packs.map(p=>`<article data-v43-pack="${esc(p.pack_id)}"><h3>${esc(p.title)}</h3><p>${esc(p.theme||'')} · Reading ${p.reading_items}/32 · Listening ${p.listening_items}/25 · Writing ${p.writing_tasks||2}/2 · Speaking ${p.speaking_parts||4}/4</p>${p.item_audit_v46_28?.production_allowed===false?`<span class="badge warn">REJECTED_FOR_REVISION · ${p.item_audit_v46_28.rejected} items/tasks</span>`:`<span class="badge">4-skill content complete</span>`}<span class="badge warn">External equivalence pending</span><button class="btn btn-primary" data-v43-start="${esc(p.pack_id)}" ${p.item_audit_v46_28?.production_allowed===false?'disabled':''}>Reading · 32</button><button class="btn btn-primary" data-v4611-start-listening="${esc(p.pack_id)}" ${p.item_audit_v46_28?.production_allowed===false?'disabled':''}>Iniciar Listening Mock · 25</button><button class="btn btn-soft" data-v4620-writing="${esc(p.pack_id)}" ${p.item_audit_v46_28?.production_allowed===false?'disabled':''}>Writing · 2</button><button class="btn btn-soft" data-v4620-speaking="${esc(p.pack_id)}" ${p.item_audit_v46_28?.production_allowed===false?'disabled':''}>Speaking · 4</button></article>`).join('')}</div>${V.lastResult?`<div class="notice">Último resultado: <b>${esc(V.lastResult.title)}</b> · ${V.lastResult.correct}/32 (${V.lastResult.pct}%)</div>`:''}</section>`);document.querySelectorAll('[data-v43-start]').forEach(b=>b.onclick=()=>startPack(b.dataset.v43Start,true))}
async function injectRemediation(){
 if(state?.view!=='writing'||!window.apiRequest)return;const main=root();if(!main||main.querySelector('.v43-remediation'))return;
 const queue=window.PETQUEST_V42?.state?.errorQueue||[];if(!queue.length)return;let progress=null;try{progress=await apiRequest('/academic-remediation')}catch(_){}
 const pm={};(progress?.patterns||[]).forEach(x=>pm[x.error_code]=x);
 main.insertAdjacentHTML('beforeend',`<section class="card v43-remediation"><h2>🎯 Remediation to Mastery V43</h2><p>Practica el error prioritario y registra evidencia correctiva. Un patrón se considera dominado solo tras al menos 3 intentos recientes correctos.</p>${queue.slice(0,3).map((q,idx)=>{const pr=q.practice?.[0]||'',ans=q.answers?.[0]||'',m=pm[q.rule];return `<article class="v43-task"><b>${esc(q.subcompetence)}</b> · ${esc(q.severity)} ${m?.mastered?'<span class="badge">Dominado</span>':''}<p>${esc(pr)}</p><input data-v43-rem-input="${idx}" autocomplete="off" spellcheck="false" placeholder="escribe tu respuesta"><button class="btn btn-primary" data-v43-rem-check="${idx}">Comprobar</button><div id="v43RemFb${idx}" class="small">${m?`${m.practice_attempts} intentos · ${m.practice_accuracy??'—'}% correctos`:''}</div><span data-v43-rem-answer="${idx}" hidden>${esc(ans)}</span></article>`}).join('')}</section>`);
 document.querySelectorAll('[data-v43-rem-check]').forEach(b=>b.onclick=async()=>{const i=+b.dataset.v43RemCheck,q=queue[i],inp=document.querySelector(`[data-v43-rem-input="${i}"]`),answer=q.answers?.[0]||'',correct=norm(inp?.value)===norm(answer),fb=document.getElementById(`v43RemFb${i}`);if(fb)fb.innerHTML=correct?'<b>✅ Correcto.</b> Intento registrado.':`<b>❌ Revisa.</b> Respuesta esperada: ${esc(answer)}`;try{await apiRequest('/academic-remediation',{method:'POST',body:{error_code:q.rule,prompt:q.practice?.[0]||'',answer:inp?.value||'',correct,source:'v43-remediation-ui'}})}catch(_){};});
}
const prevRender=window.render;window.render=function(){prevRender();requestAnimationFrame(()=>{injectBank();injectRemediation()})};
const style=document.createElement('style');style.textContent=`.v43-packgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px}.v43-packgrid article,.v43-task{border:1px solid var(--line,#dbe2ea);border-radius:14px;padding:14px;margin:10px 0}.v43-packgrid .btn{width:100%;margin-top:8px}.v43-partnav{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;margin:12px 0}.v43-partnav button{padding:9px;border:1px solid #d9e0e8;border-radius:10px;background:white}.v43-partnav button.active{font-weight:800;outline:2px solid currentColor}.v43-partnav small{display:block}.v43-optionbank{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:8px;margin:12px 0}.v43-optionbank div{border:1px solid #e2e8f0;border-radius:10px;padding:9px}.v43-optionbank span{display:block}.v43-passage,.v43-source{padding:14px;border-radius:12px;background:#f7f9fc;margin:10px 0;line-height:1.55}.v43-task input,.v43-task select{width:100%;max-width:520px;padding:10px;margin-top:8px}@media(max-width:700px){.v43-partnav{grid-template-columns:repeat(3,1fr)}}`;
document.head.appendChild(style);
window.PETQUEST_V43={version:'43.0',startPack,score,state:V};requestAnimationFrame(()=>{injectBank();injectRemediation()});
})();
