/* PET Quest V46.23 — Child Learning Experience 100
   Functional child UX layer for ages 9–14: short goals, Learn→Practice→Master→Mock,
   prominent "No entiendo", mastery-based rewards, break hygiene, mood check-in,
   per-user persistence and pedagogical event tracing. */
(function(){'use strict';
const VERSION='46.23';
const DEFAULT={mood:'ready',sessionStart:Date.now(),answersSinceBreak:0,lastBreakAt:0,breaks:0,routeVisits:{learn:0,practice:0,master:0,mock:0},masteryCelebrated:[],lastGoalDate:'',goalChoice:'auto'};
const S={...DEFAULT};
function kid(){try{return typeof uxMode==='function'&&uxMode()==='kid'&&(!API?.user||API.user.role==='student')&&data?.profile?.examProfile!=='adult'}catch(_){return false}}
function uid(){try{return API?.user?.id||data?.profile?.name||'guest'}catch(_){return'guest'}}
function storeKey(){return 'petquest_v4623_child_u_'+uid()}
function load(){try{Object.assign(S,DEFAULT,JSON.parse(localStorage.getItem(storeKey())||'{}'));if(!Number.isFinite(S.sessionStart))S.sessionStart=Date.now()}catch(_){Object.assign(S,DEFAULT)}}
function saveLocal(){try{localStorage.setItem(storeKey(),JSON.stringify(S))}catch(_){}}
function E(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function event(type,meta={}){try{if(typeof apiRequest==='function'&&API?.token)await apiRequest('/events',{method:'POST',body:{event_type:type,skill:meta.skill||'learning_experience',item_id:meta.item_id||null,success:meta.success??null,minutes:meta.minutes||0,meta:{source:'v46.23-child-experience',age_band:ageBand(),mood:S.mood,...meta}}})}catch(_){}}
function ageBand(){try{const b=V12?.ageBand||'10-12';return b==='7-9'?'9':b==='13+'?'13-14':'10-12'}catch(_){return'10-12'}}
function today(){return new Date().toISOString().slice(0,10)}
function todayAttempts(){try{return (data.history||[]).filter(x=>(x.date||'').slice(0,10)===today()).length}catch(_){return 0}}
function todayCorrect(){try{return (data.history||[]).filter(x=>(x.date||'').slice(0,10)===today()&&x.correct).length}catch(_){return 0}}
function diagnostic(){try{return window.PETQuestPracticeBank?.diagnosis?.()||null}catch(_){return null}}
function practiceState(){try{return window.PETQuestPracticeBank?.state||null}catch(_){return null}}
function masterySignals(){const p=practiceState(),out=[];if(p?.stats)Object.entries(p.stats).forEach(([k,v])=>{if(k.startsWith('skill:'))return;const n=Number(v?.n||0),ok=Number(v?.ok||0),acc=n?ok/n:0;if(n>=5&&acc>=.8)out.push({type:'competency',name:k,n,accuracy:Math.round(acc*100)})});if(p?.patternStats)Object.entries(p.patternStats).forEach(([k,v])=>{const n=Number(v?.n||0),ok=Number(v?.ok||0),acc=n?ok/n:0;if(n>=5&&acc>=.8)out.push({type:'pattern',name:k,n,accuracy:Math.round(acc*100)})});return out.sort((a,b)=>b.accuracy-a.accuracy||b.n-a.n)}
function masteredCount(){return masterySignals().length}
function route(){const ps=practiceState();const practiceAttempts=ps?.stats?Object.entries(ps.stats).filter(([k])=>k.startsWith('skill:')).reduce((n,[,v])=>n+Number(v?.n||0),0):0;const attempts=(data.history||[]).length+practiceAttempts;let helpUsed=false;try{helpUsed=typeof V14!=='undefined'&&Object.values(V14.helpCounts||{}).some(n=>n>0)}catch(_){}const d=diagnostic(),rem=ps?.remediation;return {learn:attempts>=3||helpUsed,practice:attempts>=10,master:masteredCount()>0||!!rem?.complete,mock:(data.mockAttempts||[]).length>0,diagnostic:d}}
function ageCopy(){const a=ageBand();if(a==='9')return {goal:3,minutes:6,headline:'Una misión pequeña. Un paso a la vez.',helper:'Milo te explica con frases cortas y puedes pedir ayuda cuando quieras.'};if(a==='13-14')return {goal:8,minutes:12,headline:'Entrena con autonomía y mide tu dominio.',helper:'Primero inténtalo solo; usa ayuda cuando realmente la necesites.'};return {goal:5,minutes:8,headline:'Aprende, practica y domina sin apuro.',helper:'Tú decides cuándo pedir una pista y cuándo repetir.'}}
function stageIcon(ok,active){return ok?'✅':active?'▶️':'○'}
function recommendedStage(){const r=route();if(!r.learn)return'learn';if(!r.practice)return'practice';if(!r.master)return'master';return'mock'}
function progressPct(){const r=route();return ['learn','practice','master','mock'].filter(k=>r[k]).length*25}
function weakText(){const d=diagnostic(),p=d?.primary_issue;return p?`${p.pattern}: ${p.accuracy}% (${p.n||p.attempts||0} intentos)`:'Aún estamos reuniendo evidencia para detectar tu patrón más débil.'}
function childDashboard(){if(!kid()||state.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('#pqChildJourney'))return;const c=ageCopy(),rec=recommendedStage(),r=route(),pct=progressPct(),daily=Math.min(100,Math.round(todayAttempts()/c.goal*100)),mastery=masteredCount();const anchor=main.querySelector('.v12-hero-scene')?.parentElement||main.firstElementChild;
 const html=`<section class="card pq-child-journey" id="pqChildJourney"><div class="pq-child-head"><div><span class="mission-label">V46.23 · PET QUEST PARA 9–14 AÑOS</span><h2>🌈 ${E(c.headline)}</h2><p>${E(c.helper)} <b>No compites con nadie:</b> avanzas cuando demuestras dominio.</p></div><div class="pq-child-ring" aria-label="Ruta completada ${pct}%"><b>${pct}%</b><small>ruta</small></div></div><div class="pq-mini-goal"><div><b>🎯 Meta de hoy: ${c.goal} actividades</b><span>${todayAttempts()}/${c.goal} realizadas · ${todayCorrect()} correctas</span></div><div class="pq-bar"><i style="width:${daily}%"></i></div></div><div class="pq-route" role="list"><button data-pq23-stage="learn" class="${rec==='learn'?'recommended':''}"><span>${stageIcon(r.learn,rec==='learn')}</span><b>1. APRENDER</b><small>Explicación + ejemplo + “No entiendo”</small></button><button data-pq23-stage="practice" class="${rec==='practice'?'recommended':''}"><span>${stageIcon(r.practice,rec==='practice')}</span><b>2. PRACTICAR</b><small>Banco adaptativo + corrección inmediata</small></button><button data-pq23-stage="master" class="${rec==='master'?'recommended':''}"><span>${stageIcon(r.master,rec==='master')}</span><b>3. DOMINAR</b><small>10 ejercicios del patrón más débil</small></button><button data-pq23-stage="mock" class="${rec==='mock'?'recommended':''}"><span>${stageIcon(r.mock,rec==='mock')}</span><b>4. SIMULAR</b><small>20 Full Mocks cuando estés preparado</small></button></div><div class="pq-child-grid"><div class="notice"><b>🧠 Lo que PET Quest está aprendiendo sobre ti</b><br>${E(weakText())}</div><div class="notice"><b>💎 Dominio real</b><br>${mastery} patrones/competencias con ≥80% y evidencia suficiente.</div></div><div class="pq-mood"><b>¿Cómo te sientes para estudiar hoy?</b><button data-pq23-mood="ready" class="${S.mood==='ready'?'active':''}">😄 Listo</button><button data-pq23-mood="ok" class="${S.mood==='ok'?'active':''}">🙂 Más o menos</button><button data-pq23-mood="stuck" class="${S.mood==='stuck'?'active':''}">😓 Necesito ayuda</button></div></section>`;
 anchor?.insertAdjacentHTML('afterend',html);bindDashboard();celebrateMastery();}
function gotoStage(stage){S.routeVisits[stage]=(S.routeVisits[stage]||0)+1;saveLocal();event('kid_route_stage_open',{stage});if(stage==='mock'){state.view='mock';render();return}const target=(diagnostic()?.primary_issue?.skill)||'reading';startSkill(target==='writing'||target==='speaking'?'reading':target,1);setTimeout(()=>{const p=window.PETQuestPracticeBank?.state;if(!p)return;if(stage==='learn'){p.open=true;p.adaptive=false}else if(stage==='practice'){p.open=true;p.adaptive=true}else if(stage==='master'){p.open=true;p.adaptive=true;const pat=diagnostic()?.primary_issue?.pattern;if(pat)window.PETQuestPracticeBank?.startRemediation?.(pat)}render()},180)}
function bindDashboard(){document.querySelectorAll('[data-pq23-stage]').forEach(b=>b.onclick=()=>gotoStage(b.dataset.pq23Stage));document.querySelectorAll('[data-pq23-mood]').forEach(b=>b.onclick=()=>{S.mood=b.dataset.pq23Mood;saveLocal();event('kid_mood_checkin',{mood:S.mood});render();if(S.mood==='stuck')setTimeout(()=>showHelp('home'),80)})}
function helpButton(){if(!kid()||!['practice','writing','speaking'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('[data-pq23-help]'))return;const wrap=document.createElement('div');wrap.className='pq23-floating-actions';wrap.innerHTML='<button class="btn btn-primary" data-pq23-help>🤔 No entiendo</button><button class="btn btn-soft" data-pq23-break>🌿 Necesito una pausa</button>';main.appendChild(wrap);wrap.querySelector('[data-pq23-help]').onclick=()=>showHelp(state.view);wrap.querySelector('[data-pq23-break]').onclick=()=>showBreak(true)}
function showHelp(view){event('kid_help_requested',{view,skill:state.skill||view});if(view==='practice'&&typeof v14Show==='function'){v14Show('understand');document.querySelector('.v14-tutor-panel')?.scrollIntoView({behavior:'smooth',block:'center'});return}const copy=view==='writing'?['Lee solo la tarea.','Marca los puntos que debes responder.','Escribe 3 ideas cortas.','Convierte cada idea en una oración.','Al final revisa conectores y tiempo verbal.']:view==='speaking'?['Escucha la pregunta completa.','Responde primero con una idea corta.','Añade una razón usando because.','Añade un ejemplo o detalle.','Si es Part 3, responde también a la idea de tu compañero.']:['Elige una misión pequeña.','Puedes empezar por Reading o Listening.','Cuando te atasques, pide una pista.'];modal('🤔 No entiendo',`<p>No pasa nada si necesitas otra explicación. Haz solo esto:</p><ol>${copy.map(x=>`<li>${E(x)}</li>`).join('')}</ol><button class="btn btn-primary" data-pq23-close>Entendido, pruebo otra vez</button>`)}
function modal(title,body){document.querySelector('.pq23-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="pq23-modal" role="dialog" aria-modal="true"><div class="pq23-modal-card"><h2>${title}</h2>${body}</div></div>`);document.querySelector('[data-pq23-close]')?.addEventListener('click',()=>document.querySelector('.pq23-modal')?.remove())}
function showBreak(manual=false){const now=Date.now();S.lastBreakAt=now;S.sessionStart=now;S.answersSinceBreak=0;S.breaks++;saveLocal();event('kid_break',{manual,break_number:S.breaks});modal('🌿 Pausa de 60 segundos',`<p>Descansa los ojos, mueve los hombros y respira normalmente. Tu progreso está guardado.</p><div class="pq23-break-count"><b>60</b><span>segundos opcionales</span></div><button class="btn btn-primary" data-pq23-close>Estoy listo para continuar</button>`);let n=60;const el=document.querySelector('.pq23-break-count b');const t=setInterval(()=>{if(!document.body.contains(el)){clearInterval(t);return}n--;if(el)el.textContent=String(Math.max(0,n));if(n<=0)clearInterval(t)},1000)}
function breakDue(){const mins=(Date.now()-Number(S.sessionStart||Date.now()))/60000;return S.answersSinceBreak>=6||mins>=Math.max(8,ageCopy().minutes)}
function bindAnswerTracking(){if(!kid())return;['[data-check]','[data-pqb-check]','[data-eval-writing]','[data-eval-speaking]'].forEach(sel=>document.querySelectorAll(sel).forEach(b=>{if(b.dataset.pq23Tracked)return;b.dataset.pq23Tracked='1';b.addEventListener('click',()=>{S.answersSinceBreak++;saveLocal();setTimeout(()=>{if(breakDue()&&!document.querySelector('.pq23-modal'))showBreak(false)},450)},true)}))}
function celebrateMastery(){const m=masterySignals();const fresh=m.find(x=>!S.masteryCelebrated.includes(x.type+':'+x.name));if(!fresh)return;S.masteryCelebrated.push(fresh.type+':'+fresh.name);saveLocal();event('kid_mastery_earned',{mastery_type:fresh.type,mastery_name:fresh.name,accuracy:fresh.accuracy,attempts:fresh.n,success:true});setTimeout(()=>modal('💎 ¡Dominio conseguido!',`<p><b>${E(fresh.name)}</b> ya tiene ${fresh.accuracy}% con ${fresh.n} intentos.</p><p>Esta recompensa se gana por demostrar aprendizaje estable, no por acertar una sola vez.</p><button class="btn btn-primary" data-pq23-close>Seguir mi aventura</button>`),350)}
function practiceGoal(){if(!kid()||state.view!=='practice')return;const q=document.querySelector('.question-card');if(!q||q.querySelector('.pq23-practice-goal'))return;const c=ageCopy();q.insertAdjacentHTML('afterbegin',`<div class="pq23-practice-goal"><b>🎯 Solo esta misión</b><span>Haz ${c.goal} actividades. Si te atascas, usa <strong>🤔 No entiendo</strong>. Después puedes parar con éxito.</span></div>`)}
function safeFeedback(){if(!kid())return;document.querySelectorAll('.feedback.bad').forEach(x=>{if(x.dataset.pq23Safe)return;x.dataset.pq23Safe='1';x.insertAdjacentHTML('beforeend','<p class="pq23-retry">🔁 Este error ya se convirtió en una pista para tu siguiente ejercicio. Puedes volver a intentarlo.</p>')})}
function style(){if(document.getElementById('pq23-style'))return;const s=document.createElement('style');s.id='pq23-style';s.textContent=`.pq-child-journey{border:2px solid #d7e8ff}.pq-child-head{display:flex;justify-content:space-between;gap:16px;align-items:center}.pq-child-ring{min-width:82px;height:82px;border-radius:50%;display:grid;place-content:center;text-align:center;background:#eef6ff;border:7px solid #9dc8ff}.pq-child-ring b{font-size:1.35rem}.pq-child-ring small{display:block}.pq-mini-goal{margin:14px 0}.pq-mini-goal>div:first-child{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.pq-bar{height:10px;background:#e9eef5;border-radius:999px;overflow:hidden;margin-top:7px}.pq-bar i{display:block;height:100%;background:#4f8cff}.pq-route{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.pq-route button{border:1px solid #dce5ef;background:white;border-radius:14px;padding:12px;text-align:left;min-height:92px}.pq-route button.recommended{outline:3px solid #a9d0ff;background:#f4f9ff}.pq-route button span{font-size:1.2rem}.pq-route button b,.pq-route button small{display:block;margin-top:4px}.pq-child-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.pq-mood{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.pq-mood button{border:1px solid #dce5ef;background:white;border-radius:999px;padding:8px 12px}.pq-mood button.active{outline:2px solid #70a9ff}.pq23-floating-actions{position:sticky;bottom:12px;z-index:20;display:flex;justify-content:center;gap:8px;margin:16px auto;pointer-events:none}.pq23-floating-actions button{pointer-events:auto;box-shadow:0 4px 16px rgba(0,0,0,.12)}.pq23-modal{position:fixed;inset:0;background:rgba(20,35,55,.48);z-index:99999;display:grid;place-items:center;padding:20px}.pq23-modal-card{background:white;max-width:560px;width:100%;border-radius:20px;padding:22px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.pq23-modal-card li{margin:9px 0}.pq23-break-count{text-align:center;margin:18px}.pq23-break-count b{font-size:2.4rem;display:block}.pq23-practice-goal{background:#f2f8ff;border:1px solid #cfe3ff;border-radius:14px;padding:10px 12px;margin-bottom:12px}.pq23-practice-goal b,.pq23-practice-goal span{display:block}.pq23-retry{margin-top:8px;font-weight:600}@media(max-width:760px){.pq-route{grid-template-columns:1fr 1fr}.pq-child-grid{grid-template-columns:1fr}.pq-child-head{align-items:flex-start}.pq-child-ring{min-width:70px;height:70px}.pq23-floating-actions{flex-wrap:wrap}}`;
document.head.appendChild(s)}
function enhance(){load();style();if(!kid())return;document.documentElement.dataset.childExperience='v46.23';childDashboard();practiceGoal();helpButton();bindAnswerTracking();safeFeedback();celebrateMastery()}
const base=typeof render==='function'?render:null;if(base){window.render=function(){const r=base.apply(this,arguments);requestAnimationFrame(enhance);return r}}
setTimeout(enhance,400);window.PETQuestChildExperience={version:VERSION,state:S,route,masterySignals,recommendedStage,showHelp,showBreak};
})();
