/* PET Quest V46.24 — Error DNA™
   Per-student error map built from persisted academic errors, remediation,
   B1 matrix practice evidence, Writing rubric and Speaking practice metrics. */
(function(){'use strict';
const V='46.24';
const S={report:null,loading:false,error:null,lastFetch:0,selected:null};
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function isStudent(){try{return !API?.user||API.user.role==='student'}catch(_){return true}}
async function load(force=false){if(S.loading)return S.report;if(!force&&S.report&&Date.now()-S.lastFetch<15000)return S.report;S.loading=true;S.error=null;try{S.report=await apiRequest('/error-dna');S.lastFetch=Date.now()}catch(e){S.error=e?.message||String(e)}finally{S.loading=false}return S.report}
function statusClass(s){return s==='critical'?'dna-critical':s==='progress'?'dna-progress':s==='mastered'?'dna-mastered':'dna-insufficient'}
function pct(n){return n===null||n===undefined?'—':`${Math.round(Number(n)*10)/10}%`}
function domainCard(d){return `<article class="dna-domain"><h3>${E(d.domain)}</h3><div class="dna-nodes">${d.nodes.map(n=>`<button class="dna-node ${statusClass(n.status)}" data-dna-key="${E(n.key)}" title="${E(n.cause||n.label)}"><span class="dna-light">${E(n.icon)}</span><span><b>${E(n.label)}</b><small>${n.status==='insufficient'?'evidencia insuficiente':pct(n.score)} · ${n.evidence_count} evid.</small></span></button>`).join('')}</div></article>`}
function mainIssue(r){const p=r?.primary_issue;if(!p)return `<div class="notice"><b>🧬 Todavía estamos leyendo tu Error DNA™.</b><br>Necesitamos al menos ${r?.minimum_evidence||3} evidencias por patrón antes de poner un color diagnóstico.</div>`;return `<div class="feedback ${p.status==='critical'?'bad':'neutral'} dna-primary"><h3>🎯 Problema prioritario</h3><p><b>${E(p.domain)} · ${E(p.label)}: ${pct(p.score)}</b></p><p>${E(p.cause)}</p><button class="btn btn-primary" data-dna-train="${E(p.key)}">⚡ Entrenar 10 ejercicios de este patrón</button></div>`}
function panel(){const r=S.report;if(S.loading&&!r)return `<section class="card" id="pqErrorDNA"><h2>🧬 Error DNA™</h2><p>Cargando tu mapa de aprendizaje…</p></section>`;if(S.error&&!r)return `<section class="card" id="pqErrorDNA"><h2>🧬 Error DNA™</h2><p>No se pudo cargar el mapa todavía.</p></section>`;if(!r)return'';return `<section class="card pq-error-dna" id="pqErrorDNA"><div class="row between dna-head"><div><span class="mission-label">V46.24 · MAPA INDIVIDUAL DE ERROR</span><h2>🧬 Error DNA™</h2><p>No dice solo cuánto sabes. Muestra <b>qué patrón falla, cuánta evidencia existe y qué debes entrenar después.</b></p></div><div class="dna-score"><b>${r.dna_score===null?'—':pct(r.dna_score)}</b><small>dominio observado</small><span>${pct(r.diagnostic_coverage_pct)} cobertura</span></div></div>${mainIssue(r)}<div class="dna-grid">${r.domains.map(domainCard).join('')}</div><div class="dna-legend"><span>🔴 crítico &lt;60%</span><span>🟠 en progreso 60–79.9%</span><span>🟢 dominio ≥80%</span><span>⚪ evidencia insuficiente</span></div><p class="small">El verde exige al menos ${r.minimum_evidence} evidencias. Pronunciation es una medida automática de práctica y no sustituye el juicio de un examinador humano.</p></section>`}
function findNode(key){for(const d of S.report?.domains||[]){const n=d.nodes.find(x=>x.key===key);if(n)return {...n,domain:d.domain}}return null}
function openNode(key){const n=findNode(key);if(!n)return;S.selected=n;document.querySelector('.dna-modal')?.remove();const body=`<div class="dna-modal" role="dialog" aria-modal="true"><div class="dna-modal-card"><button class="dna-x" data-dna-close aria-label="Cerrar">×</button><div class="dna-big-light">${E(n.icon)}</div><h2>${E(n.domain)} · ${E(n.label)}</h2><p><b>${n.status==='insufficient'?'Evidencia insuficiente':pct(n.score)}</b> · ${n.evidence_count} evidencias</p><p>${E(n.cause||'PET Quest seguirá reuniendo evidencia para explicar este patrón.')}</p><div class="notice"><b>Fuentes:</b> ${E((n.sources||[]).join(', ')||'todavía sin datos suficientes')}<br><b>Estado:</b> ${E(n.status)}</div>${n.practice_match?`<button class="btn btn-primary" data-dna-modal-train>🎯 Crear plan de 10 ejercicios</button>`:''}<button class="btn btn-soft" data-dna-close>Cerrar</button></div></div>`;document.body.insertAdjacentHTML('beforeend',body);document.querySelectorAll('[data-dna-close]').forEach(b=>b.onclick=()=>document.querySelector('.dna-modal')?.remove());document.querySelector('[data-dna-modal-train]')?.addEventListener('click',()=>train(n))}
async function train(node){if(typeof node==='string')node=findNode(node);if(!node?.practice_match)return toast?.('Aún no hay una ruta automática para este patrón.');document.querySelector('.dna-modal')?.remove();try{const P=window.PETQuestPracticeBank;if(!P?.startMatrixRemediation)throw Error('Practice Bank no disponible');await P.startMatrixRemediation(node.practice_match.field,node.practice_match.value,node.label);if(typeof state!=='undefined')state.view='practice';render();setTimeout(()=>document.getElementById('pqPracticeBank')?.scrollIntoView({behavior:'smooth',block:'start'}),250)}catch(e){toast?.('No se pudo abrir el plan correctivo: '+e.message)}}
function bind(){document.querySelectorAll('[data-dna-key]').forEach(b=>b.onclick=()=>openNode(b.dataset.dnaKey));document.querySelectorAll('[data-dna-train]').forEach(b=>b.onclick=()=>train(b.dataset.dnaTrain))}
function mount(){if(!isStudent()||typeof state==='undefined'||state.view!=='home')return;const main=document.querySelector('main.container');if(!main||document.getElementById('pqErrorDNA'))return;const anchor=document.getElementById('pqChildJourney')||main.firstElementChild;if(anchor)anchor.insertAdjacentHTML('afterend',panel());else main.insertAdjacentHTML('afterbegin',panel());bind()}
function repaint(){const old=document.getElementById('pqErrorDNA');if(old){old.outerHTML=panel();bind()}else mount()}
async function refresh(){await load(true);repaint()}
function style(){if(document.getElementById('dna24-style'))return;const s=document.createElement('style');s.id='dna24-style';s.textContent=`.pq-error-dna{border:2px solid #dce8ff}.dna-head{align-items:center;gap:16px}.dna-score{min-width:150px;text-align:center;background:#f3f8ff;border:1px solid #cfe0fb;border-radius:18px;padding:12px}.dna-score b,.dna-score small,.dna-score span{display:block}.dna-score b{font-size:1.55rem}.dna-score span{font-size:.78rem;margin-top:4px}.dna-primary{margin:12px 0}.dna-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(215px,1fr));gap:10px}.dna-domain{border:1px solid #e2e8f0;border-radius:16px;padding:12px;background:white}.dna-domain h3{margin:0 0 8px}.dna-nodes{display:grid;gap:7px}.dna-node{display:flex;align-items:center;gap:9px;text-align:left;border:1px solid #e5e7eb;border-radius:12px;background:white;padding:9px 10px;cursor:pointer}.dna-node:hover{transform:translateY(-1px);box-shadow:0 4px 12px rgba(30,65,110,.08)}.dna-node small{display:block;margin-top:2px;color:#5f6b7a}.dna-light{font-size:1.35rem}.dna-critical{background:#fff5f5;border-color:#ffd0d0}.dna-progress{background:#fff9ed;border-color:#ffdca0}.dna-mastered{background:#f1fff6;border-color:#bceaca}.dna-insufficient{background:#f8fafc}.dna-legend{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0 6px;font-size:.82rem}.dna-modal{position:fixed;inset:0;background:rgba(14,28,48,.5);z-index:100000;display:grid;place-items:center;padding:18px}.dna-modal-card{position:relative;background:white;border-radius:20px;padding:22px;max-width:570px;width:100%;box-shadow:0 24px 70px rgba(0,0,0,.25)}.dna-x{position:absolute;right:13px;top:10px;border:0;background:transparent;font-size:1.6rem;cursor:pointer}.dna-big-light{font-size:2rem}.dna-modal-card .btn{margin:6px 6px 0 0}@media(max-width:700px){.dna-head{align-items:flex-start}.dna-score{min-width:110px}.dna-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
const base=typeof render==='function'?render:null;if(base){window.render=function(){const out=base.apply(this,arguments);requestAnimationFrame(()=>{style();mount();if(isStudent()&&state?.view==='home'&&!S.report&&!S.loading){load().then(repaint)}});return out}}
style();setTimeout(()=>{mount();if(isStudent()&&typeof state!=='undefined'&&state.view==='home')load().then(repaint)},550);
window.PETQuestErrorDNA={version:V,state:S,load,refresh,findNode,train};
})();
