/* PET Quest V46.12 - Full Mock Listening Audio Engine
   Functional generated audio for For Schools A–T and Adult A–T. Exact mock playback is limited to two starts per recording.
   Generated audio is synthetic reference audio, not human studio sign-off. */
(()=>{
'use strict';
const BASE_KEY='petquest_v4626_listening_mock';
const examProfile=()=>{try{return data?.profile?.examProfile==='adult'?'adult':'schools'}catch(_){return'schools'}};
const MOCK_LISTENING_LABEL='Iniciar Listening Mock';
let ownerId=null;
const stateKey=()=>`${BASE_KEY}_${examProfile()}_u_${window.API?.user?.id||'anon'}`;
let S={active:false,packId:null,pack:null,part:1,answers:{},plays:{},strict:false,volume:0.72,startedAt:null,lastResult:null};
function ensureOwner(){const uid=window.API?.user?.id||'anon';if(ownerId===uid)return;ownerId=uid;const blank={active:false,packId:null,pack:null,part:1,answers:{},plays:{},strict:false,volume:0.72,startedAt:null,lastResult:null};S=blank;try{S=Object.assign(S,JSON.parse(localStorage.getItem(stateKey())||'{}'))}catch(_){ }}
let currentAudio=null,currentAudioId=null,timer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().toLowerCase().replace(/^[\s.,;:!?]+|[\s.,;:!?]+$/g,'');
const save=()=>{ensureOwner();localStorage.setItem(stateKey(),JSON.stringify({...S,pack:null}))};
async function loadPack(id){try{if(typeof apiRequest==='function'&&API?.token)return await apiRequest('/content/exam-pack/'+encodeURIComponent(id))}catch(e){console.warn('PostgreSQL exam pack fallback',e)}const r=await fetch(`exam_packs/${encodeURIComponent(id)}.json`,{cache:'no-store'});if(!r.ok)throw new Error('pack_load_failed');return r.json()}
function questions(part){return (S.pack?.listening||[]).filter(x=>Number(x.part)===Number(part))}
function answered(part){return questions(part).filter(q=>String(S.answers[q.id]??'').trim()!=='').length}
function totalForPart(part){return ({1:7,2:6,3:6,4:6})[part]||0}
function timerText(){if(!S.startedAt)return '30:00';const rem=Math.max(0,30*60*1000-(Date.now()-S.startedAt)),m=String(Math.floor(rem/60000)).padStart(2,'0'),s=String(Math.floor(rem%60000/1000)).padStart(2,'0');return `${m}:${s}`}
function stopAudio(){try{currentAudio?.pause()}catch(_){ } currentAudio=null;currentAudioId=null}
function audioControl(item){const id=item.audio_id,file=item.audio_file||'';const n=Number(S.plays[id]||0),blocked=S.strict&&n>=2;return `<div class="v4611-player"><button class="btn btn-primary" data-v4611-play="${esc(id)}" data-file="${esc(file)}" ${blocked?'disabled':''}>🔊 ${blocked?'2/2 escuchas usadas':S.strict?`Escuchar · ${n}/2`:`Escuchar / repetir · ${n} ♾`}</button><button class="btn btn-soft" data-v4612-pause>⏸ Pausa</button><button class="btn btn-soft" data-v4612-restart>↺ Reiniciar</button><label class="small">Volumen <input type="range" min="0" max="0.85" step="0.05" value="${Math.min(.85,Number(S.volume??0.72))}" data-v4612-volume></label><span class="small">${S.strict?(blocked?'Límite estricto alcanzado':'Simulación estricta: máximo 2 inicios.'):'Práctica: repeticiones ilimitadas.'} · voz sintética multivoz masterizada 48 kHz</span></div>`}
function options(q){return (q.options||[]).map((o,i)=>`<button class="option ${Number(S.answers[q.id])===i?'selected':''}" data-v4611-mc="${esc(q.id)}:${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}
function partHtml(){const qs=questions(S.part);if(!qs.length)return '<div class="notice">Parte no disponible.</div>';
 if(S.part===1||S.part===2)return `<h2>Listening Part ${S.part}</h2><p>${S.part===1?'Seven short recordings. Choose the correct answer.':'Six short recordings. Choose the correct answer.'}</p>${qs.map((q,i)=>`<article class="v43-task"><b>${i+1}. ${esc(q.prompt)}</b>${audioControl(q)}<div class="options">${options(q)}</div></article>`).join('')}`;
 if(S.part===3){const a=qs[0];return `<h2>Listening Part 3 · Gap fill</h2><p>Listen to one monologue and complete the six gaps.</p>${audioControl(a)}${qs.map((q,i)=>`<article class="v43-task"><label><b>${i+1}. ${esc(q.prompt)}</b><input data-v4611-text="${esc(q.id)}" value="${esc(S.answers[q.id]||'')}" autocomplete="off" spellcheck="false"></label></article>`).join('')}`}
 const a=qs[0];return `<h2>Listening Part 4</h2><p>Listen to one interview and answer six multiple-choice questions.</p>${audioControl(a)}${qs.map((q,i)=>`<article class="v43-task"><b>${i+1}. ${esc(q.prompt)}</b><div class="options">${options(q)}</div></article>`).join('')}`;
}
function nav(){return `<div class="v4611-nav">${[1,2,3,4].map(p=>`<button data-v4611-part="${p}" class="${S.part===p?'active':''}">Part ${p}<small>${answered(p)}/${totalForPart(p)}</small></button>`).join('')}</div>`}
function renderExam(){stopAudio();const app=document.querySelector('.app-shell')||document.body;app.innerHTML=`<div class="app-shell">${typeof topBar==='function'?topBar():''}<main class="container"><div class="mock-top"><div><h1>${esc(S.pack.title)} · Listening</h1><p>25 questions · 4 parts · audio funcional completo</p><button class="btn btn-soft" data-v4611-strict>${S.strict?'✓ Simulación estricta · 2 escuchas':'♾ Práctica · repeticiones ilimitadas'}</button></div><div><div class="timer" id="v4611Timer">${timerText()}</div><button class="btn btn-ghost" data-v4611-exit>Salir</button></div></div>${nav()}<section class="card question-card">${partHtml()}<div class="row action-row"><button class="btn btn-soft nav-back" data-v4611-prev ${S.part===1?'disabled':''}>← Anterior</button><button class="btn btn-primary" data-v4611-next>${S.part===4?'Finalizar Listening':'Guardar y seguir →'}</button></div></section><div class="notice"><b>${S.strict?'Simulación estricta':'Modo práctica'}:</b> ${S.strict?'máximo dos inicios por grabación':'repeticiones ilimitadas'}. El audio generado cubre funcionalmente las preguntas de este formulario, pero no se presenta como grabación humana de estudio ni como sign-off académico externo.</div></main></div>`;bindExam();armTimer()}
function bindExam(){
 document.querySelectorAll('[data-v4611-part]').forEach(b=>b.onclick=()=>{S.part=+b.dataset.v4611Part;save();renderExam()});
 document.querySelectorAll('[data-v4611-mc]').forEach(b=>b.onclick=()=>{const p=b.dataset.v4611Mc.lastIndexOf(':'),id=b.dataset.v4611Mc.slice(0,p),v=+b.dataset.v4611Mc.slice(p+1);S.answers[id]=v;save();renderExam()});
 document.querySelectorAll('[data-v4611-text]').forEach(i=>i.oninput=()=>{S.answers[i.dataset.v4611Text]=i.value;save()});
 document.querySelectorAll('[data-v4611-play]').forEach(b=>b.onclick=()=>playRecording(b.dataset.v4611Play,b.dataset.file));document.querySelectorAll('[data-v4612-pause]').forEach(b=>b.onclick=()=>{try{currentAudio?.pause()}catch(_){}});document.querySelectorAll('[data-v4612-restart]').forEach(b=>b.onclick=()=>{if(currentAudio){currentAudio.currentTime=0;currentAudio.play().catch(()=>{})}});document.querySelectorAll('[data-v4612-volume]').forEach(r=>r.oninput=()=>{S.volume=window.PETAudioSafe?PETAudioSafe.volumeValue(r.value):Math.max(0,Math.min(.85,Number(r.value)));if(currentAudio){if(window.PETAudioSafe)PETAudioSafe.setVolume(currentAudio,S.volume);else currentAudio.volume=S.volume}save()});document.querySelector('[data-v4611-strict]')?.addEventListener('click',()=>{stopAudio();S.strict=!S.strict;S.plays={};save();renderExam()});
 document.querySelector('[data-v4611-prev]')?.addEventListener('click',()=>{S.part=Math.max(1,S.part-1);save();renderExam()});
 document.querySelector('[data-v4611-next]')?.addEventListener('click',()=>{if(S.part<4){S.part++;save();renderExam()}else finish()});
 document.querySelector('[data-v4611-exit]')?.addEventListener('click',()=>{stopAudio();S.active=false;save();location.reload()});
}
function playRecording(id,file){if(!file)return;const used=Number(S.plays[id]||0);if(S.strict&&used>=2){window.toast?.('Ya usaste las 2 escuchas de este audio en simulación estricta.');return}stopAudio();S.plays[id]=used+1;save();const a=new Audio(file);if(window.PETAudioSafe)PETAudioSafe.configure(a,{rate:1,volume:Number(S.volume??0.72)});else{a.preload='auto';a.playbackRate=1;a.volume=Math.max(0,Math.min(.85,Number(S.volume??0.72)))}currentAudio=a;currentAudioId=id;a.addEventListener('ended',()=>{currentAudio=null;currentAudioId=null;renderExam()},{once:true});a.addEventListener('error',()=>window.toast?.('No se pudo reproducir el audio.'),{once:true});a.play().then(()=>{document.querySelector(`[data-v4611-play="${CSS.escape(id)}"]`)?.replaceChildren(document.createTextNode(`🔊 Reproduciendo · ${S.plays[id]}/2`))}).catch(()=>window.toast?.('Pulsa de nuevo para reproducir el audio.'))}
function score(){let c=0;for(const q of (S.pack?.listening||[])){const a=S.answers[q.id];if(Number(q.part)===3){const accepted=(q.accepted_answers||[q.answer]).map(norm);if(accepted.includes(norm(a)))c++}else if(Number(a)===Number(q.answer))c++}return {correct:c,total:25,pct:Math.round(c/25*100)}}
async function finish(){stopAudio();clearInterval(timer);const sc=score(),at=new Date().toISOString(),rows=(S.pack.listening||[]).map(q=>({item_id:q.id,part:q.part,answer_text:Number(q.part)===3?String(S.answers[q.id]||''):null,answer_option:Number(q.part)!==3&&Number.isInteger(Number(S.answers[q.id]))?Number(S.answers[q.id]):null,is_correct:Number(q.part)===3?(q.accepted_answers||[q.answer]).map(norm).includes(norm(S.answers[q.id])):Number(S.answers[q.id])===Number(q.answer),response_ms:0}));
 try{await window.apiRequest?.('/mock-attempts',{method:'POST',body:{pack_id:S.pack.pack_id,skill:'listening',started_at:new Date(S.startedAt).toISOString(),items:rows,source:'v46.12-full-listening-mock'}})}catch(_){ }
 S.lastResult={pack_id:S.pack.pack_id,title:S.pack.title,at,correct:sc.correct,total:25,pct:sc.pct};S.active=false;save();try{data.history.push({date:at,qid:`${S.pack.pack_id}-listening-full`,skill:'listening',level:'B1',focus:'full-mock',correct:sc.pct>=70,score:sc.pct,source:'v46.12-full-listening-mock'});window.save?.()}catch(_){ }
 const app=document.querySelector('.app-shell')||document.body;app.innerHTML=`<div class="app-shell">${typeof topBar==='function'?topBar():''}<main class="container"><section class="card hero"><h1>${esc(S.pack.title)} · Listening</h1><div class="stat"><b>${sc.correct}/25</b><span>${sc.pct}%</span></div><p>Resultado formativo PET Quest. No es Cambridge English Scale oficial.</p><div class="row"><button class="btn btn-primary" data-v4611-home>Volver</button><button class="btn btn-soft" data-v4611-retry>Repetir Listening</button></div></section></main></div>`;document.querySelector('[data-v4611-home]').onclick=()=>location.reload();document.querySelector('[data-v4611-retry]').onclick=()=>startListening(S.lastResult.pack_id,true)}
function armTimer(){clearInterval(timer);timer=setInterval(()=>{const e=document.getElementById('v4611Timer');if(!e){clearInterval(timer);return}e.textContent=timerText();if(e.textContent==='00:00'){clearInterval(timer);finish()}},1000)}
async function startListening(id,restart=true){ensureOwner();try{S.pack=await loadPack(id);if(S.pack?.audit_v46_28?.production_gate?.allowed===false){window.toast?.('Mock bloqueado: Listening contiene items REJECTED_FOR_REVISION');S.active=false;save();return;}S.packId=id;S.active=true;S.part=1;if(restart){S.answers={};S.plays={};S.startedAt=Date.now()}save();renderExam()}catch(_){window.toast?.('No se pudo cargar el Listening Mock')}}
function injectButtons(){ensureOwner();if(S.active&&S.packId){loadPack(S.packId).then(p=>{S.pack=p;renderExam()}).catch(()=>{}) ;return}document.querySelectorAll('[data-v4611-start-listening]').forEach(btn=>{btn.disabled=false;btn.onclick=()=>startListening(btn.dataset.v4611StartListening,true)});const bank=document.querySelector('.v43-bank>p');if(bank&&/20 Full Mocks/.test(document.querySelector('.v43-bank h2')?.textContent||''))bank.innerHTML='<b>20 formularios completos</b>: Reading, Listening, Writing y Speaking disponibles. Listening usa audio sintético multivoz del PET Audio Bank; la grabación humana de estudio y la equivalencia psicométrica externa siguen pendientes.'}
const prev=window.render;window.render=function(){prev();requestAnimationFrame(injectButtons)};
const style=document.createElement('style');style.textContent=`.v4611-nav{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}.v4611-nav button{padding:10px;border:1px solid #d9e0e8;border-radius:10px;background:#fff}.v4611-nav button.active{font-weight:800;outline:2px solid currentColor}.v4611-nav small{display:block}.v4611-player{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:10px 0}.v4611-player .small{opacity:.75}@media(max-width:700px){.v4611-nav{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(style);
window.PETQUEST_V4611={version:'46.26',startListening,state:S,score};requestAnimationFrame(injectButtons);
})();
