/* PET Quest V46.14 - Speaking AI Examiner
   Automatic formative practice only. Not an official Cambridge score. */
(function(){
'use strict';
const VERSION='46.14';
const S={stream:null,rec:null,chunks:[],ctx:null,analyser:null,timer:null,startedAt:0,rms:[],pitch:[],silenceStart:null,pauses:[],recognizer:null,transcript:'',interim:'',confidence:0,lastBlob:null,lastAudioKey:null,lastMetrics:null,lastRubric:null};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(+n)?+n:0));
const words=t=>String(t||'').trim().match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g)||[];
const EXAMINER_PROMPTS={1:'Tell me about your school or studies and something you enjoy doing in your free time.',2:'Describe what you can see in the picture. Say what the people are doing and how they might feel.',3:'Why don’t we organise a picnic after school? Respond, make another suggestion and try to reach an agreement.',4:'Do you think young people should spend more free time outdoors? Why or why not?'};
function activeExaminerPrompt(){return window.PETQUEST_V4620?.currentSpeakingPrompt?.()||EXAMINER_PROMPTS[currentPart()]||EXAMINER_PROMPTS[1]}
function speakExaminer(){const text=activeExaminerPrompt();if(!('speechSynthesis' in window))return window.toast?.('La voz del examinador no está disponible en este navegador.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.92;u.pitch=1;u.volume=.78;if(window.PETAudioSafe)PETAudioSafe.safeUtterance(u,{rate:.92,volume:.78});speechSynthesis.speak(u)}
const currentPart=()=>{const ex=window.PETQUEST_V17?.state?.exam;if(ex?.active)return Math.max(1,Math.min(4,(ex.part||0)+1));return Math.max(1,Math.min(4,(window.state?.idx||0)+1))};
const currentMode=()=>window.PETQUEST_V17?.state?.mode||'learn';
function score5(x){return Math.max(0,Math.min(5,Math.round(clamp(x)/20)))}
function rateScore(wpm){if(!wpm)return 0;if(wpm<45)return clamp(wpm/45*50);if(wpm<80)return 50+(wpm-45)/35*30;if(wpm<=155)return 80+Math.min(20,(wpm-80)/75*20);if(wpm<=190)return 100-(wpm-155)/35*25;return Math.max(35,75-(wpm-190)*.8)}
function estimatePitch(buf,sr){let rms=0;for(let i=0;i<buf.length;i++)rms+=buf[i]*buf[i];rms=Math.sqrt(rms/buf.length);if(rms<.018)return 0;let best=0,bestLag=0,min=Math.floor(sr/350),max=Math.min(Math.floor(sr/70),buf.length-2);for(let lag=min;lag<=max;lag+=2){let c=0;for(let i=0;i<buf.length-lag;i+=2)c+=buf[i]*buf[i+lag];if(c>best){best=c;bestLag=lag}}return bestLag?sr/bestLag:0}
function acousticTick(){if(!S.analyser)return;const a=new Float32Array(S.analyser.fftSize);S.analyser.getFloatTimeDomainData(a);let sum=0;for(const x of a)sum+=x*x;const rms=Math.sqrt(sum/a.length);S.rms.push(rms);const now=performance.now();if(rms<.022){if(S.silenceStart==null)S.silenceStart=now}else if(S.silenceStart!=null){const d=now-S.silenceStart;if(d>=250)S.pauses.push(d);S.silenceStart=null}const p=estimatePitch(a,S.ctx.sampleRate);if(p>=70&&p<=350)S.pitch.push(p);updateLive(rms)}
function updateLive(rms){const t=document.getElementById('v4614Live');if(t&&S.startedAt){const sec=(performance.now()-S.startedAt)/1000;t.textContent=`Grabando · ${sec.toFixed(1)} s`}const m=document.getElementById('v4614Meter');if(m)m.style.width=`${Math.round(clamp(rms*900))}%`}
function setupRecognition(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return null;const r=new R();r.lang='en-GB';r.continuous=true;r.interimResults=true;r.maxAlternatives=1;r.onresult=e=>{let final='';let interim='';let conf=[];for(let i=e.resultIndex;i<e.results.length;i++){const res=e.results[i],txt=res[0]?.transcript||'';if(res.isFinal){final+=txt+' ';if(Number.isFinite(res[0]?.confidence))conf.push(res[0].confidence)}else interim+=txt}if(final)S.transcript=(S.transcript+' '+final).trim();S.interim=interim;if(conf.length)S.confidence=conf.reduce((a,b)=>a+b,0)/conf.length;const ta=document.getElementById('v4614Transcript');if(ta)ta.value=(S.transcript+' '+S.interim).trim()};r.onerror=()=>{};try{r.start()}catch(_){}return r}
async function startRecording(){if(S.rec&&S.rec.state==='recording')return;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){window.toast?.('Este navegador no permite grabación directa. Puedes escribir una transcripción y usar el análisis textual.');return;}try{S.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}catch(e){window.toast?.('No se pudo acceder al micrófono. Revisa el permiso del navegador.');return}S.chunks=[];S.rms=[];S.pitch=[];S.pauses=[];S.silenceStart=null;S.transcript='';S.interim='';S.confidence=0;S.lastBlob=null;S.lastAudioKey=null;S.startedAt=performance.now();S.ctx=new (window.AudioContext||window.webkitAudioContext)();const src=S.ctx.createMediaStreamSource(S.stream);S.analyser=S.ctx.createAnalyser();S.analyser.fftSize=2048;src.connect(S.analyser);S.timer=setInterval(acousticTick,120);let opts={};if(window.MediaRecorder?.isTypeSupported?.('audio/webm;codecs=opus'))opts={mimeType:'audio/webm;codecs=opus',audioBitsPerSecond:64000};S.rec=new MediaRecorder(S.stream,opts);S.rec.ondataavailable=e=>{if(e.data?.size)S.chunks.push(e.data)};S.rec.onstop=()=>{S.lastBlob=new Blob(S.chunks,{type:S.rec.mimeType||'audio/webm'});const p=document.getElementById('v4614Playback');if(p){p.src=URL.createObjectURL(S.lastBlob);p.hidden=false}};S.rec.start(250);S.recognizer=setupRecognition();setRecordingUI(true)}
async function stopRecording(){if(!S.rec||S.rec.state!=='recording')return;S.rec.stop();clearInterval(S.timer);if(S.silenceStart!=null){const d=performance.now()-S.silenceStart;if(d>=250)S.pauses.push(d);S.silenceStart=null}try{S.recognizer?.stop()}catch(_){}S.stream?.getTracks().forEach(t=>t.stop());try{await S.ctx?.close()}catch(_){}setRecordingUI(false);const ta=document.getElementById('v4614Transcript');if(ta&&S.transcript&&!ta.value.trim())ta.value=S.transcript}
function setRecordingUI(on){document.querySelector('[data-v4614-start]')?.toggleAttribute('disabled',on);document.querySelector('[data-v4614-stop]')?.toggleAttribute('disabled',!on);const live=document.getElementById('v4614Live');if(live)live.textContent=on?'Grabando · 0.0 s':'Listo para analizar'}
function detectRestarts(txt){const t=String(txt||'').toLowerCase();let n=0;n+=(t.match(/\b(\w+)\s+\1\b/g)||[]).length;n+=(t.match(/\b(i mean|sorry|no,|let me start|actually, no)\b/g)||[]).length;return n}
function languageMetrics(txt,dur){const ws=words(txt),low=String(txt||'').toLowerCase(),n=ws.length,uniq=new Set(ws.map(x=>x.toLowerCase())).size;const hes=(low.match(/\b(um+|uh+|er+|erm+|hmm+)\b/g)||[]).length;const fillers=(low.match(/\b(well|actually|let me think|i mean|you know|to be honest|in my opinion)\b/g)||[]).length;const discourse=(low.match(/\b(first|firstly|then|next|because|so|but|however|although|also|for example|for instance|finally|on the other hand|in my opinion|i think)\b/g)||[]).length;const interaction=(low.match(/\b(i agree|i disagree|what about|how about|why don't|we could|we should|could we|shall we|let's|do you think|that's a good idea|maybe|perhaps|instead|which one|in the end)\b/g)||[]).length;const wpm=dur>1?n/(dur/60):0;const ttr=n?uniq/n:0;let grammar=70;const bad=[/\bi am agree\b/,/\bhe go\b/,/\bshe go\b/,/\bi go yesterday\b/,/\bdidn't went\b/,/\bpeople is\b/,/\bthere is many\b/];grammar-=bad.filter(r=>r.test(low)).length*12;if(n<10)grammar-=20;grammar=clamp(grammar+Math.min(15,discourse*2));const vocab=clamp(35+ttr*55+Math.min(15,(low.match(/\b(although|however|instead|probably|especially|prefer|suggest|advantage|disadvantage|experience|opportunity)\b/g)||[]).length*4));return{word_count:n,wpm:+wpm.toFixed(1),hesitations:hes,appropriate_fillers:fillers,restarts:detectRestarts(txt),discourse_markers:discourse,interaction_markers:interaction,grammar:Math.round(grammar),vocabulary_range:Math.round(vocab),type_token_ratio:+ttr.toFixed(2)}}
function acousticMetrics(duration){const long=S.pauses.filter(x=>x>=700),totalPause=S.pauses.reduce((a,b)=>a+b,0)/1000,maxPause=S.pauses.length?Math.max(...S.pauses)/1000:0,meanR=S.rms.length?S.rms.reduce((a,b)=>a+b,0)/S.rms.length:0,sdR=S.rms.length?Math.sqrt(S.rms.reduce((a,b)=>a+(b-meanR)**2,0)/S.rms.length):0;const pm=S.pitch.length?S.pitch.reduce((a,b)=>a+b,0)/S.pitch.length:0,ps=S.pitch.length?Math.sqrt(S.pitch.reduce((a,b)=>a+(b-pm)**2,0)/S.pitch.length):0;const stress=clamp(35+(meanR?sdR/meanR*90:0));const intonation=clamp(25+(pm?ps/pm*260:0));return{long_pauses:long.length,total_pause_seconds:+totalPause.toFixed(1),max_pause_seconds:+maxPause.toFixed(1),stress_variation:Math.round(stress),intonation_variation:Math.round(intonation),mean_pitch_hz:pm?+pm.toFixed(1):0,pitch_sd_hz:ps?+ps.toFixed(1):0,mean_rms:+meanR.toFixed(4),asr_confidence:Math.round(clamp(S.confidence*100))}}
function analyse(txt,duration){const L=languageMetrics(txt,duration),A=acousticMetrics(duration);const pausePenalty=Math.min(45,A.long_pauses*8+A.total_pause_seconds/Math.max(duration,1)*35),hesPenalty=Math.min(30,L.hesitations*4+L.restarts*5);const fluency=clamp(rateScore(L.wpm)-pausePenalty-hesPenalty+Math.min(8,L.appropriate_fillers*2));const intelligibility=A.asr_confidence?clamp(A.asr_confidence*.75+rateScore(L.wpm)*.25):clamp(45+rateScore(L.wpm)*.35-A.long_pauses*4);const responseLength=clamp(L.word_count/45*100);const interaction=currentPart()===3?clamp(30+L.interaction_markers*12+L.discourse_markers*3):currentPart()===4?clamp(35+L.interaction_markers*6+L.discourse_markers*4):clamp(45+L.discourse_markers*4+Math.min(20,responseLength*.2));const pronunciation=clamp(intelligibility*.55+A.stress_variation*.2+A.intonation_variation*.25);const metrics={duration_seconds:+duration.toFixed(1),...L,...A,fluency:Math.round(fluency),intelligibility:Math.round(intelligibility),pronunciation_proxy:Math.round(pronunciation),response_length:Math.round(responseLength),interaction:Math.round(interaction)};const rubric={grammar_vocabulary:score5(L.grammar*.55+L.vocabulary_range*.45),discourse_management:score5(fluency*.55+clamp(L.discourse_markers*15)*.25+responseLength*.2),pronunciation:score5(pronunciation),interactive_communication:score5(interaction),global_achievement:0};rubric.global_achievement=score5((rubric.grammar_vocabulary+rubric.discourse_management+rubric.pronunciation+rubric.interactive_communication)/20*100);const total=Object.values(rubric).reduce((a,b)=>a+b,0),scorePct=Math.round(total/25*100);return{metrics,rubric,total,scorePct}}
function weaknesses(a){const m=a.metrics,r=a.rubric,out=[];if(m.fluency<70)out.push(`Fluency: reduce pausas largas (${m.long_pauses}) y hesitaciones (${m.hesitations}).`);if(m.wpm<80)out.push(`Speech rate: sube gradualmente desde ${m.wpm} WPM hacia un ritmo conversacional estable.`);if(r.grammar_vocabulary<4)out.push('Grammar & Vocabulary: amplía estructuras y evita errores repetidos.');if(r.discourse_management<4)out.push('Discourse Management: desarrolla ideas con conectores y ejemplos.');if(r.pronunciation<4)out.push('Pronunciation/Intelligibility: practica claridad, stress y entonación; esta medida es un proxy automático.');if(r.interactive_communication<4)out.push('Interactive Communication: responde, propone, compara y negocia más explícitamente.');if(m.response_length<65)out.push('Response length: desarrolla más la respuesta con razón + ejemplo.');return out.slice(0,4)}
function renderResults(a){const m=a.metrics,r=a.rubric,w=weaknesses(a);return `<section class="card v4614-results"><div class="row between"><div><div class="label">PET SPEAKING AI EXAMINER</div><h2>${a.scorePct}% · práctica automática</h2></div><div class="v4614-orb">${a.total}/25</div></div><div class="notice"><b>Importante:</b> evaluación automática de práctica; no equivale a una calificación oficial Cambridge. Pronunciation, stress, intonation e intelligibility son proxies acústicos.</div><div class="v4614-metrics">${[['Fluency',m.fluency+'%'],['WPM',m.wpm],['Long pauses',m.long_pauses],['Hesitations',m.hesitations],['Restarts',m.restarts],['Fillers apropiados',m.appropriate_fillers],['Grammar',m.grammar+'%'],['Vocabulary',m.vocabulary_range+'%'],['Discourse markers',m.discourse_markers],['Pronunciation proxy',m.pronunciation_proxy+'%'],['Intelligibility',m.intelligibility+'%'],['Stress variation',m.stress_variation+'%'],['Intonation variation',m.intonation_variation+'%'],['Response length',m.response_length+'%'],['Interaction',m.interaction+'%']].map(x=>`<div><b>${E(x[1])}</b><span>${E(x[0])}</span></div>`).join('')}</div><h3>Rúbrica de práctica 0–5</h3><div class="v4614-rubric">${[['Grammar & Vocabulary',r.grammar_vocabulary],['Discourse Management',r.discourse_management],['Pronunciation',r.pronunciation],['Interactive Communication',r.interactive_communication],['Global Achievement',r.global_achievement]].map(x=>`<div><span>${E(x[0])}</span><b>${x[1]}/5</b></div>`).join('')}</div><h3>Para subir tu resultado</h3><ol>${(w.length?w:['Mantén este nivel y repite con una respuesta nueva para comprobar estabilidad.']).map(x=>`<li>${E(x)}</li>`).join('')}</ol><div class="row"><button class="btn btn-primary" data-v4614-retry>🔁 Reintentar</button><button class="btn btn-soft" data-v4614-history>📈 Ver historial</button></div></section>`}
function examinerHtml(){return `<section class="card v4614-examiner"><div class="row between"><div><span class="mission-label">🎙️ PET Speaking AI Examiner</span><h2>Parte ${currentPart()} · analiza tu voz</h2></div><span class="badge">V${VERSION}</span></div><p>Mide fluency, WPM, pausas, hesitaciones, reinicios, grammar, vocabulary, discourse markers, pronunciation/intelligibility proxy, stress, intonation, longitud e interacción.</p><div class="notice"><b>Examiner:</b> ${E(activeExaminerPrompt())}<br><button class="btn btn-soft mini" data-v4614-hear>🔊 Escuchar examinador</button></div><div class="notice"><b>Automático ≠ oficial:</b> úsalo para practicar y mejorar. Una evaluación oficial requiere examinadores humanos.</div><div class="v4614-rec-row"><button class="btn btn-primary" data-v4614-start>● Grabar</button><button class="btn btn-soft" data-v4614-stop disabled>■ Detener</button><span id="v4614Live" class="small">Listo para grabar</span></div><div class="v4614-meter"><i id="v4614Meter"></i></div><audio id="v4614Playback" controls hidden></audio><label><span>Transcripción</span><textarea id="v4614Transcript" class="textarea" placeholder="La voz reconocida aparecerá aquí. Si el navegador no transcribe, puedes escribir lo que dijiste."></textarea></label><div class="row"><button class="btn btn-primary" data-v4614-analyse>✨ Analizar y guardar</button><button class="btn btn-soft" data-v4614-history>📈 Mi historial</button></div><div id="v4614Result" aria-live="polite"></div></section>`}
function inject(){if(window.state?.view!=='speaking'||document.querySelector('.v4614-examiner'))return;const main=document.querySelector('main.container');if(!main)return;main.insertAdjacentHTML('beforeend',examinerHtml());bindExaminer()}
function bindExaminer(){document.querySelector('[data-v4614-hear]')?.addEventListener('click',speakExaminer);document.querySelector('[data-v4614-start]')?.addEventListener('click',startRecording);document.querySelector('[data-v4614-stop]')?.addEventListener('click',stopRecording);document.querySelector('[data-v4614-analyse]')?.addEventListener('click',analyseAndSave);document.querySelectorAll('[data-v4614-history]').forEach(b=>b.addEventListener('click',showHistory));document.querySelector('[data-v4614-retry]')?.addEventListener('click',()=>{const r=document.getElementById('v4614Result');if(r)r.innerHTML='';const t=document.getElementById('v4614Transcript');if(t)t.value='';const p=document.getElementById('v4614Playback');if(p){p.pause();p.removeAttribute('src');p.hidden=true}S.lastMetrics=S.lastRubric=null;S.lastBlob=null;S.lastAudioKey=null;S.startedAt=0;S.transcript='';S.interim=''})}
function openAudioDb(){return new Promise((res,rej)=>{const q=indexedDB.open('petquestSpeakingAudioV4614',1);q.onupgradeneeded=()=>q.result.createObjectStore('audio');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function saveAudioLocal(blob,key){if(!blob||!window.indexedDB)return false;try{const db=await openAudioDb();await new Promise((res,rej)=>{const tx=db.transaction('audio','readwrite');tx.objectStore('audio').put(blob,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();return true}catch(_){return false}}
async function analyseAndSave(){const ta=document.getElementById('v4614Transcript'),txt=(ta?.value||'').trim();let dur=S.startedAt?Math.max(.5,(performance.now()-S.startedAt)/1000):Math.max(5,words(txt).length/2);if(S.rec?.state==='recording'){await stopRecording();dur=Math.max(.5,(performance.now()-S.startedAt)/1000)}if(!txt&&(!S.lastBlob||S.lastBlob.size<200)){window.toast?.('Graba una respuesta o escribe la transcripción antes de analizar.');return}const a=analyse(txt,dur);S.lastMetrics=a.metrics;S.lastRubric=a.rubric;const key=`u${window.API?.user?.id||'local'}-p${currentPart()}-${Date.now()}`;let localSaved=false;if(S.lastBlob)localSaved=await saveAudioLocal(S.lastBlob,key);S.lastAudioKey=localSaved?key:'';try{const out=await window.apiRequest('/speaking-attempts',{method:'POST',body:{part:currentPart(),mode:currentMode(),transcript:txt,duration_ms:Math.round(dur*1000),metrics:a.metrics,rubric:a.rubric,score_pct:a.scorePct,audio_local_key:S.lastAudioKey,source:'v46.14-speaking-ai'}});if(window.data){data.speaking=data.speaking||[];data.speaking.push({date:new Date().toISOString(),part:currentPart(),score:a.scorePct/5,score_pct:a.scorePct,metrics:a.metrics,rubric:a.rubric,source:'v46.14-speaking-ai',server_id:out.id});window.save?.()}const r=document.getElementById('v4614Result');if(r)r.innerHTML=renderResults(a)+(localSaved?'<p class="small">🔒 El audio quedó guardado solo en este dispositivo y asociado a tu usuario. El servidor guarda métricas y transcripción.</p>':'<p class="small">El servidor guardó métricas y transcripción. El audio no se almacenó.</p>');bindExaminer();window.toast?.('Speaking analizado y guardado')}catch(e){window.toast?.('No se pudo guardar el intento: '+e.message)}}
async function showHistory(){const r=document.getElementById('v4614Result');if(!r)return;try{const j=await window.apiRequest('/speaking-attempts');const xs=j.attempts||[];r.innerHTML=`<section class="card"><h3>📈 Historial Speaking</h3>${xs.length?xs.slice(0,12).map(x=>`<div class="v4614-history"><span>${E(new Date(x.created_at).toLocaleString())} · Parte ${x.part}</span><b>${Math.round(x.score_pct)}%</b><small>${x.metrics?.wpm||0} WPM · ${x.metrics?.long_pauses||0} pausas largas · ${x.metrics?.hesitations||0} hesitaciones</small></div>`).join(''):'<p>Aún no hay intentos guardados.</p>'}</section>`}catch(e){r.innerHTML='<div class="feedback bad">No pude cargar el historial.</div>'}}
const prevRender=window.render;window.render=function(){const out=prevRender.apply(this,arguments);requestAnimationFrame(inject);return out};
requestAnimationFrame(inject);
window.PETQUEST_V46_14={version:VERSION,analyseTextAndAudio:analyse,state:S};
})();
