/* PET Quest V46.17 - Anonymous Cambridge Scale Calibration */
(function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={fail_a2:'Fail/A2 (<140)',pass_b1:'Pass B1 (140–152)',merit_b1:'Grade B / Merit (153–159)',distinction_b2:'Grade A / B2 (160–170)'};
function gateList(g){return Object.entries(g||{}).map(([k,v])=>`<div class="small">${v?'✅':'⏳'} ${esc(k.replaceAll('_',' '))}</div>`).join('')}
async function refresh47(root){let r;try{r=await apiRequest('/calibration/scale-equivalence')}catch(_){return}const d=r.distribution||{},p=r.progress||{};root.querySelector('.v4617-body').innerHTML=`<div class="rubric"><div class="stat"><b>${r.sample_size}</b><span>Candidatos anónimos</span></div><div class="stat"><b>${p.to_300||0}%</b><span>Meta mínima 300</span></div><div class="stat"><b>${p.to_500||0}%</b><span>Meta robusta 500</span></div><div class="stat"><b>${p.to_1000||0}%</b><span>Meta madura 1.000+</span></div></div><h3>Distribución de resultados reales</h3>${Object.keys(labels).map(k=>`<span class="badge">${labels[k]}: ${d[k]||0}</span>`).join(' ')}<div class="notice"><b>Equivalencia PET Quest ↔ Cambridge Scale:</b> ${r.scale_equivalence_enabled?'ACTIVA (validada externamente)':'OFF'}<br>${esc(r.note||'')}</div><div class="grid2"><div><h3>Holdout</h3><div class="small">n=${r.holdout_size} · MAE=${r.holdout_metrics?.mae??'—'} · RMSE=${r.holdout_metrics?.rmse??'—'} · R²=${r.holdout_metrics?.r2??'—'}</div></div><div><h3>Gates</h3>${gateList(r.gates)}</div></div>`}
async function saveOne47(root){const q=x=>root.querySelector(x);const body={anon_id:q('[name=anon]')?.value||'',predicted_readiness:Number(q('[name=readiness]')?.value),actual_scale_score:Number(q('[name=scale]')?.value),source:q('[name=source]')?.value||'official_exam',exam_date:q('[name=examdate]')?.value||'',cohort_label:q('[name=cohort]')?.value||''};const msg=q('.v4617-msg');try{const r=await apiRequest('/calibration/anonymous-candidates',{method:'POST',body});msg.textContent=`✅ Guardado ${r.anon_id} · ${r.cambridge_band}`;await refresh47(root)}catch(e){msg.textContent='❌ No se pudo guardar. Revisa readiness 0–100 y Cambridge Scale 102–170.'}}
function mount47(){if(!['teacher','school','reports'].includes(state.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('.v4617-scale'))return;main.insertAdjacentHTML('beforeend',`<section class="card v4617-scale"><h2>📊 PET Quest ↔ Cambridge English Scale · Cohorte anónima</h2><p>Base sin nombre, correo ni teléfono. Registra únicamente un ID anónimo, PET Quest Readiness y resultado externo verificable.</p><div class="grid2"><label>ID anónimo (opcional)<input name="anon" placeholder="Student-000001"></label><label>PET Quest Readiness<input name="readiness" type="number" min="0" max="100" step="0.1"></label><label>Cambridge English Scale<input name="scale" type="number" min="102" max="170" step="1"></label><label>Fuente<select name="source"><option value="official_exam">Official exam</option><option value="external_mock">External validated mock</option></select></label><label>Fecha examen<input name="examdate" type="date"></label><label>Cohorte<input name="cohort" placeholder="2026-Q4 / School pilot"></label></div><button id="v4617Save" class="primary v4617-save">Guardar resultado anónimo</button> <a class="button" href="ANONYMOUS_CALIBRATION_TEMPLATE_V46_17.csv" download>Plantilla CSV</a><div class="v4617-msg small"></div><hr><div class="v4617-body">Cargando calibración…</div></section>`);const root=main.querySelector('.v4617-scale');root.querySelector('#v4617Save').onclick=()=>saveOne47(root);refresh47(root)}
const prev=window.render;window.render=function(){prev();requestAnimationFrame(mount47)};requestAnimationFrame(mount47);
window.PETQUEST_V4617={version:'46.17',mount:mount47};
})();
