(()=>{
const V={summary:null,loading:false,promise:null,error:null};
const esc8=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v){const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(1)}
function gradeClass(v){return v>=75?'ok':v>=60?'warn':'bad'}
function publishProgress(summary){if(!summary)return;try{window.dispatchEvent(new CustomEvent('petquest:progress-updated',{detail:{summary}}))}catch(_){}}
async function load(force=false){
 if(!API?.token)return V.summary;if(V.promise)return V.promise;if(V.summary&&!force)return V.summary;
 V.loading=true;V.error=null;V.promise=(async()=>{try{V.summary=await apiRequest('/my-preparation');publishProgress(V.summary);return V.summary}catch(error){V.error=error;console.warn('No se pudo cargar el progreso unificado',error);return V.summary}})();
 try{return await V.promise}finally{V.loading=false;V.promise=null}
}
function syncVisibleProgress(s){if(!s)return;const a=s.activity||{},p=s.preparation||{},sk=s.skills||{};const set=(sel,value)=>{const el=document.querySelector(sel);if(el)el.textContent=value};set('[data-progress-readiness]',fmt(p.score)+'%');set('[data-progress-accuracy]',fmt(a.accuracy)+'%');set('[data-progress-attempts]',fmt(a.attempts));['reading','writing','listening','speaking'].forEach(k=>{set(`[data-progress-skill="${k}"]`,fmt(sk[k])+'%');const bar=document.querySelector(`[data-progress-bar="${k}"]`);if(bar)bar.style.width=Math.max(0,Math.min(100,Number(sk[k]||0)))+'%'});set('.pill.xp','⭐ '+fmt(a.xp)+' XP')}
function card(s){if(!s)return '<section class="card"><p>Cargando registro individual…</p></section>';const a=s.activity||{},e=s.errors||{},p=s.preparation||{},sk=s.skills||{},ex=s.exams||[];return `<section class="card v468-progress"><div class="row between"><div><div class="kicker">REGISTRO INDIVIDUAL</div><h2>${esc8(s.student?.name||'Alumno')} · Preparación PET</h2><p class="small">Datos guardados exclusivamente en la cuenta autenticada.</p></div><div class="big-number">${fmt(p.score)}%</div></div><div class="dashboard-grid four"><div class="card"><div class="label">Avance</div><div class="big-number">${fmt(p.score)}%</div><div class="progress"><span style="width:${Math.min(100,p.score||0)}%"></span></div></div><div class="card"><div class="label">Errores</div><div class="big-number">${e.total_error_targets||0}</div><p>${e.pending||0} pendientes</p></div><div class="card"><div class="label">Correcciones</div><div class="big-number">${e.corrected||0}</div><p>${fmt(e.correction_rate)}% reparados</p></div><div class="card"><div class="label">Falta</div><div class="big-number">${fmt(p.remaining)}%</div><p>para completar el índice interno</p></div></div><div class="dashboard-grid four"><div class="card"><div class="label">Reading</div><b>${fmt(sk.reading)}%</b></div><div class="card"><div class="label">Writing</div><b>${fmt(sk.writing)}%</b></div><div class="card"><div class="label">Listening</div><b>${fmt(sk.listening)}%</b></div><div class="card"><div class="label">Speaking</div><b>${fmt(sk.speaking)}%</b></div></div><div class="notice"><b>Calificación final de preparación:</b> ${fmt(p.score)}% · ${esc8(p.band||'')}<br><span class="small">${esc8(s.note||'')}</span></div><h3>Preparación por examen</h3>${ex.length?`<div class="table-wrap"><table><thead><tr><th>Examen</th><th>Habilidad</th><th>Calificación</th><th>Falta</th><th>Fecha</th></tr></thead><tbody>${ex.map(x=>`<tr><td>${esc8(x.exam)}</td><td>${esc8(x.skill)}</td><td><b>${fmt(x.score)}%</b></td><td>${fmt(x.remaining)}%</td><td>${x.date?new Date(x.date).toLocaleDateString():'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Aún no hay simulacros terminados. Al finalizar un examen aparecerá aquí su calificación.</div>'}<div class="small">Respuestas: ${a.attempts||0} · correctas ${a.correct_answers||0} · incorrectas ${a.wrong_answers||0} · precisión ${fmt(a.accuracy)}%</div></section>`}

function mountBadge(s){if(API?.user?.role!=='student'||!s)return;const host=document.querySelector('.topbar .top-actions')||document.querySelector('.topbar');if(!host)return;let b=host.querySelector('#v4612ProgressBadge');if(!b){b=document.createElement('button');b.id='v4612ProgressBadge';b.className='role-pill';b.type='button';b.onclick=()=>{state.view='dashboard';render()};host.prepend(b)}const p=s.preparation||{};b.textContent=`Avance ${fmt(p.score)}%`;b.title=`PET Quest Preparation Score · falta ${fmt(p.remaining)}%`;}
async function mount(){if(!API?.token)return;const main=document.querySelector('main.container');if(!main)return;const s=await load();mountBadge(s);syncVisibleProgress(s);let box=main.querySelector('#v468UserProgress');if(state?.view==='dashboard'){box?.remove();return}if(!box){box=document.createElement('div');box.id='v468UserProgress';main.appendChild(box)}if(document.body.contains(box))box.innerHTML=card(s)}
const oldRender=window.render||render;window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{if(API?.token&&API?.user?.role==='student'){if(state?.view==='dashboard'||state?.view==='home')mount();else load(true).then(mountBadge)}} ,0);return r};
let refreshTimer=null;function scheduleProgressRefresh(delay=650){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>load(true).then(s=>{mountBadge(s);syncVisibleProgress(s);const box=document.querySelector('#v468UserProgress');if(box&&s&&state?.view!=='dashboard')box.innerHTML=card(s)}),delay)}window.addEventListener('petquest:data-saved',()=>scheduleProgressRefresh(900));window.addEventListener('petquest:server-mutated',()=>scheduleProgressRefresh(500));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&API?.user?.role==='student')scheduleProgressRefresh(100)});window.PETQUEST_V468={version:'46.35-progress-sync4',load,mount,state:V,refresh:scheduleProgressRefresh,syncVisibleProgress};
setTimeout(()=>{if(API?.token&&(state?.view==='dashboard'||state?.view==='home'))mount()},300);
})();
