/* PET Quest V46.26 — Dual Exam Profile: B1 Preliminary for Schools / B1 Preliminary Adult */
(function(){'use strict';
const VERSION='46.26';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const topics=['work','travel','banking','housing','shopping','transport','appointments','technology','everyday healthcare','restaurants','relationships','community','holidays','services','employment'];
function current(){try{return data?.profile?.examProfile==='adult'?'adult':'schools'}catch(_){return'schools'}}
function isStudent(){try{return !API?.user||API.user.role==='student'}catch(_){return true}}
function apply(){const p=current();document.documentElement.dataset.examProfile=p;document.documentElement.classList.toggle('exam-profile-adult',p==='adult');document.documentElement.classList.toggle('exam-profile-schools',p==='schools');document.title=p==='adult'?'PET Quest — B1 Preliminary Adult':'PET Quest — B1 Preliminary for Schools';}
function cleanupAdult(){if(current()!=='adult')return;['#pqChildJourney','.pq23-floating-actions','.v11-status','.v11-world','.v12-hero-scene','.v12-kid-dashboard','.v13-kid','.v15-kid-home'].forEach(sel=>document.querySelectorAll(sel).forEach(x=>x.remove()))}
async function setProfile(p){p=p==='adult'?'adult':'schools';data.profile=data.profile||{};data.profile.examProfile=p;try{save()}catch(_){};try{await apiRequest?.('/events',{method:'POST',body:{event_type:'exam_profile_changed',skill:'profile',success:true,meta:{exam_profile:p,source:'v46.26-dual-profile'}}})}catch(_){};try{localStorage.setItem('petquest_exam_profile_u_'+(API?.user?.id||'guest'),p)}catch(_){};location.reload()}
function topBadge(){const bar=document.querySelector('.topbar-inner');if(!bar||bar.querySelector('[data-exam-profile-badge]'))return;const b=document.createElement('button');b.className='pill';b.dataset.examProfileBadge='1';b.textContent=current()==='adult'?'🧑 B1 Adult':'🎓 B1 For Schools';b.title='Cambiar perfil de examen';b.onclick=()=>openChooser();const xp=bar.querySelector('.pill.xp');bar.insertBefore(b,xp||bar.lastElementChild)}
function openChooser(){document.querySelector('.pq26-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="pq26-modal"><div class="pq26-card"><h2>Elige tu perfil B1</h2><p>Ambos preparan el mismo nivel B1. Cambia el contexto de práctica y mocks.</p><div class="pq26-choice"><button data-pq26-set="schools" class="${current()==='schools'?'active':''}"><b>🎓 B1 Preliminary for Schools</b><span>Contenido pensado para candidatos en edad escolar.</span></button><button data-pq26-set="adult" class="${current()==='adult'?'active':''}"><b>🧑 B1 Preliminary – Adult</b><span>Trabajo, viajes, vivienda, banca, servicios, empleo y vida cotidiana.</span></button></div><button class="btn btn-soft" data-pq26-close>Cerrar</button></div></div>`);document.querySelectorAll('[data-pq26-set]').forEach(b=>b.onclick=()=>setProfile(b.dataset.pq26Set));document.querySelector('[data-pq26-close]')?.addEventListener('click',()=>document.querySelector('.pq26-modal')?.remove())}
function homeCard(){if(state?.view!=='home')return;const main=document.querySelector('main.container');if(!main||main.querySelector('#pq26Profile'))return;const adult=current()==='adult';main.insertAdjacentHTML('afterbegin',`<section class="card pq26-profile" id="pq26Profile"><div><span class="mission-label">V46.26 · PERFIL DE EXAMEN</span><h2>${adult?'🧑 B1 PRELIMINARY – ADULT':'🎓 B1 PRELIMINARY FOR SCHOOLS'}</h2><p>${adult?'Ruta B1 con contextos adultos reales de vida cotidiana.':'Ruta B1 con contenido adaptado a candidatos en edad escolar.'}</p></div><div class="pq26-profile-side"><b>${adult?'20 Adult Full Mocks · 3.000 actividades adultas':'20 For Schools Full Mocks · 5.000 actividades'}</b><button class="btn btn-soft" data-pq26-choose>Cambiar perfil</button></div>${adult?`<div class="pq26-topics">${topics.map(x=>`<span>${E(x)}</span>`).join('')}</div>`:''}</section>`);document.querySelector('[data-pq26-choose]')?.addEventListener('click',openChooser)}
function accountCard(){if(!['account','settings'].includes(state?.view))return;const main=document.querySelector('main.container');if(!main||main.querySelector('#pq26AccountProfile'))return;main.insertAdjacentHTML('beforeend',`<section class="card" id="pq26AccountProfile"><h2>Perfil B1</h2><p>Seleccionado: <b>${current()==='adult'?'B1 Preliminary – Adult':'B1 Preliminary for Schools'}</b></p><button class="btn btn-primary" data-pq26-choose>Cambiar perfil de examen</button></section>`);document.querySelector('#pq26AccountProfile [data-pq26-choose]')?.addEventListener('click',openChooser)}
function adultNote(){if(current()!=='adult'||!isStudent())return;const main=document.querySelector('main.container');if(!main||main.querySelector('.pq26-adult-note')||state?.view==='home')return;main.insertAdjacentHTML('afterbegin',`<div class="notice pq26-adult-note"><b>🧑 Perfil Adult activo.</b> Los Full Mocks y Practice Bank usan contextos adultos; tu progreso y Error DNA™ siguen siendo individuales.</div>`)}
function enhance(){apply();cleanupAdult();topBadge();homeCard();accountCard();adultNote()}
const prior=window.render;if(typeof prior==='function'){window.render=function(){const r=prior.apply(this,arguments);requestAnimationFrame(enhance);return r}}
const style=document.createElement('style');style.textContent=`.pq26-profile{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;border:2px solid #cadcf6}.pq26-profile-side{display:grid;gap:8px;text-align:right}.pq26-topics{grid-column:1/-1;display:flex;gap:6px;flex-wrap:wrap}.pq26-topics span{padding:5px 9px;border-radius:999px;background:#f2f6fb;font-size:.82rem}.pq26-modal{position:fixed;inset:0;background:rgba(13,24,40,.55);z-index:100000;display:grid;place-items:center;padding:20px}.pq26-card{background:#fff;border-radius:20px;padding:22px;max-width:720px;width:100%}.pq26-choice{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.pq26-choice button{padding:18px;border:1px solid #d8e2ef;border-radius:16px;background:#fff;text-align:left}.pq26-choice button.active{outline:3px solid #9dc8ff;background:#f4f9ff}.pq26-choice b,.pq26-choice span{display:block}.pq26-choice span{margin-top:6px}.exam-profile-adult .pq-child-journey,.exam-profile-adult .pq23-floating-actions{display:none!important}@media(max-width:700px){.pq26-profile{grid-template-columns:1fr}.pq26-profile-side{text-align:left}.pq26-choice{grid-template-columns:1fr}}`;document.head.appendChild(style);
setTimeout(enhance,300);window.PETQUEST_V4626={version:VERSION,current,setProfile,topics,openChooser};
})();
