(()=>{
const V={summary:null,loading:false};
const esc8=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function fmt(v){const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(1)}
function gradeClass(v){return v>=75?'ok':v>=60?'warn':'bad'}
async function load(force=false){if(!window.API?.token||V.loading)return V.summary;if(V.summary&&!force)return V.summary;V.loading=true;try{V.summary=await apiRequest('/my-preparation');return V.summary}catch(_){return V.summary}finally{V.loading=false}}
function card(s){if(!s)return '<section class="card"><p>Cargando registro individual…</p></section>';const a=s.activity||{},e=s.errors||{},p=s.preparation||{},sk=s.skills||{},ex=s.exams||[];return `<section class="card v468-progress"><div class="row between"><div><div class="kicker">REGISTRO INDIVIDUAL</div><h2>${esc8(s.student?.name||'Alumno')} · Preparación PET</h2><p class="small">Datos guardados exclusivamente en la cuenta autenticada.</p></div><div class="big-number">${fmt(p.score)}%</div></div><div class="dashboard-grid four"><div class="card"><div class="label">Avance</div><div class="big-number">${fmt(p.score)}%</div><div class="progress"><span style="width:${Math.min(100,p.score||0)}%"></span></div></div><div class="card"><div class="label">Errores</div><div class="big-number">${e.total_error_targets||0}</div><p>${e.pending||0} pendientes</p></div><div class="card"><div class="label">Correcciones</div><div class="big-number">${e.corrected||0}</div><p>${fmt(e.correction_rate)}% reparados</p></div><div class="card"><div class="label">Falta</div><div class="big-number">${fmt(p.remaining)}%</div><p>para completar el índice interno</p></div></div><div class="dashboard-grid four"><div class="card"><div class="label">Reading</div><b>${fmt(sk.reading)}%</b></div><div class="card"><div class="label">Writing</div><b>${fmt(sk.writing)}%</b></div><div class="card"><div class="label">Listening</div><b>${fmt(sk.listening)}%</b></div><div class="card"><div class="label">Speaking</div><b>${fmt(sk.speaking)}%</b></div></div><div class="notice"><b>Calificación final de preparación:</b> ${fmt(p.score)}% · ${esc8(p.band||'')}<br><span class="small">${esc8(s.note||'')}</span></div><h3>Preparación por examen</h3>${ex.length?`<div class="table-wrap"><table><thead><tr><th>Examen</th><th>Habilidad</th><th>Calificación</th><th>Falta</th><th>Fecha</th></tr></thead><tbody>${ex.map(x=>`<tr><td>${esc8(x.exam)}</td><td>${esc8(x.skill)}</td><td><b>${fmt(x.score)}%</b></td><td>${fmt(x.remaining)}%</td><td>${x.date?new Date(x.date).toLocaleDateString():'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Aún no hay simulacros terminados. Al finalizar un examen aparecerá aquí su calificación.</div>'}<div class="small">Respuestas: ${a.attempts||0} · correctas ${a.correct_answers||0} · incorrectas ${a.wrong_answers||0} · precisión ${fmt(a.accuracy)}%</div></section>`}

function mountBadge(s){if(window.API?.user?.role!=='student'||!s)return;const host=document.querySelector('.topbar .top-actions')||document.querySelector('.topbar');if(!host)return;let b=host.querySelector('#v4612ProgressBadge');if(!b){b=document.createElement('button');b.id='v4612ProgressBadge';b.className='role-pill';b.type='button';b.onclick=()=>{state.view='dashboard';render()};host.prepend(b)}const p=s.preparation||{};b.textContent=`Avance ${fmt(p.score)}%`;b.title=`PET Quest Preparation Score · falta ${fmt(p.remaining)}%`;}
async function mount(){if(!window.API?.token)return;const main=document.querySelector('main.container');if(!main)return;let box=main.querySelector('#v468UserProgress');if(!box){box=document.createElement('div');box.id='v468UserProgress';main.appendChild(box)}box.innerHTML='<section class="card"><p>Cargando registro individual…</p></section>';const s=await load();mountBadge(s);if(document.body.contains(box))box.innerHTML=card(s)}
const oldRender=window.render||render;window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(()=>{if(window.API?.token&&window.API?.user?.role==='student'){if(window.state?.view==='dashboard'||window.state?.view==='home')mount();else load(true).then(mountBadge)}} ,0);return r};
let refreshTimer=null;function scheduleProgressRefresh(delay=650){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>load(true).then(s=>{mountBadge(s);const box=document.querySelector('#v468UserProgress');if(box&&s)box.innerHTML=card(s)}),delay)}window.addEventListener('petquest:data-saved',()=>scheduleProgressRefresh(900));window.addEventListener('petquest:server-mutated',()=>scheduleProgressRefresh(500));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&window.API?.user?.role==='student')scheduleProgressRefresh(100)});window.PETQUEST_V468={version:'46.25',load,mount,state:V,refresh:scheduleProgressRefresh};
setTimeout(()=>{if(window.API?.token&&(window.state?.view==='dashboard'||window.state?.view==='home'))mount()},300);
})();
