/* PET Quest V46.20 - 20 Full Mock Mastery Bank
   20 complete four-skill forms. Structural/content completeness != external psychometric equivalence. */
(()=>{'use strict';
const VERSION='46.20';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activePack=null, activeSpeakingPart=1, writingStartedAt=0, writingTimer=null;
const userKey=(pid)=>`petquest_v4620_fullmock_writing_u_${window.API?.user?.id||'anon'}_${pid}`;
async function loadPack(id){try{if(typeof apiRequest==='function'&&API?.token)return await apiRequest('/content/exam-pack/'+encodeURIComponent(id))}catch(e){console.warn('PostgreSQL exam pack fallback',e)}const r=await fetch(`exam_packs/${encodeURIComponent(id)}.json`,{cache:'no-store'});if(!r.ok)throw new Error('pack_load_failed');return r.json()}
function mockTopBar4620(){return typeof topBar==='function'?topBar():''}
function wordCount(s){return (String(s||'').trim().match(/\b[\w’'-]+\b/g)||[]).length}
function writingTime(){if(!writingStartedAt)return '45:00';const rem=Math.max(0,45*60*1000-(Date.now()-writingStartedAt));return `${String(Math.floor(rem/60000)).padStart(2,'0')}:${String(Math.floor((rem%60000)/1000)).padStart(2,'0')}`}
function getSaved(pid){try{return JSON.parse(localStorage.getItem(userKey(pid))||'{}')}catch(_){return {}}}
function saveWriting(){if(!activePack)return;const rec={part1:document.getElementById('v4620w1')?.value||'',part2choice:document.querySelector('input[name=v4620choice]:checked')?.value||'article',part2:document.getElementById('v4620w2')?.value||'',started_at:writingStartedAt,updated_at:Date.now()};localStorage.setItem(userKey(activePack.pack_id),JSON.stringify(rec));updateCounts()}
function updateCounts(){const a=document.getElementById('v4620wc1'),b=document.getElementById('v4620wc2');if(a)a.textContent=`${wordCount(document.getElementById('v4620w1')?.value||'')} palabras`;if(b)b.textContent=`${wordCount(document.getElementById('v4620w2')?.value||'')} palabras`}
function renderWriting(pack){activePack=pack;const saved=getSaved(pack.pack_id),w=pack.writing||[],p2=w[1]||{},opts=p2.options||[];writingStartedAt=saved.started_at||Date.now();const app=document.querySelector('.app-shell')||document.body;app.innerHTML=`<div class="app-shell">${mockTopBar4620()}<main class="container"><div class="mock-top"><div><div class="label">FULL MOCK ${esc(pack.pack_id.toUpperCase())}</div><h1>${esc(pack.title)} · Writing</h1><p>45 minutes · 2 tasks · about 100 words each</p></div><div><div class="timer" id="v4620WTimer">${writingTime()}</div><button class="btn btn-ghost" data-v4620-home>Salir</button></div></div><section class="card"><h2>Part 1 · Email</h2><p>${esc(w[0]?.prompt||'')}</p><textarea id="v4620w1" class="textarea" rows="10" placeholder="Write your email here...">${esc(saved.part1||'')}</textarea><div id="v4620wc1" class="small"></div></section><section class="card"><h2>Part 2 · Choose ONE</h2>${opts.map(o=>`<label class="v4620-choice"><input type="radio" name="v4620choice" value="${esc(o.type)}" ${(saved.part2choice||'article')===o.type?'checked':''}><b>${esc(o.type)}</b> · ${esc(o.prompt)}</label>`).join('')}<textarea id="v4620w2" class="textarea" rows="10" placeholder="Write your chosen task here...">${esc(saved.part2||'')}</textarea><div id="v4620wc2" class="small"></div></section><div class="row action-row"><button class="btn btn-soft" data-v4620-save>Guardar</button><button class="btn btn-primary" data-v4620-finish-writing>Finalizar Writing</button></div><div class="notice">Se guarda por usuario. La producción puede evaluarse después con Writing Mastery 0–20. No es una calificación oficial Cambridge.</div></main></div>`;updateCounts();bindWriting();clearInterval(writingTimer);writingTimer=setInterval(()=>{const e=document.getElementById('v4620WTimer');if(!e){clearInterval(writingTimer);return}e.textContent=writingTime()},1000)}
function bindWriting(){document.querySelectorAll('#v4620w1,#v4620w2,input[name=v4620choice]').forEach(e=>e.addEventListener('input',()=>{saveWriting();updateCounts()}));document.querySelector('[data-v4620-save]')?.addEventListener('click',()=>{saveWriting();window.toast?.('Writing guardado')});document.querySelector('[data-v4620-home]')?.addEventListener('click',()=>{saveWriting();clearInterval(writingTimer);location.reload()});document.querySelector('[data-v4620-finish-writing]')?.addEventListener('click',()=>{saveWriting();const s=getSaved(activePack.pack_id),at=new Date().toISOString();try{if(window.data){data.writing=data.writing||[];data.writing.push({date:at,part:1,text:s.part1||'',words:wordCount(s.part1),score:null,source:'v46.20-full-mock',pack_id:activePack.pack_id});data.writing.push({date:at,part:2,taskVariant:s.part2choice||'article',text:s.part2||'',words:wordCount(s.part2),score:null,source:'v46.20-full-mock',pack_id:activePack.pack_id});window.save?.()}}catch(_){};window.apiRequest?.('/events',{method:'POST',body:{event_type:'full_mock_writing_complete',payload:{pack_id:activePack.pack_id,part1_words:wordCount(s.part1),part2_words:wordCount(s.part2),part2_choice:s.part2choice||'article'}}}).catch(()=>{});clearInterval(writingTimer);window.toast?.('Writing del mock guardado');location.reload()})}
function speakingPrompt(part){if(!activePack)return '';const p=(activePack.speaking?.parts||[]).find(x=>Number(x.part)===Number(part));if(!p)return '';if(p.prompt)return p.prompt;if(p.prompts)return p.prompts.join(' ');return ''}
function renderSpeaking(pack){activePack=pack;const parts=pack.speaking?.parts||[];const app=document.querySelector('.app-shell')||document.body;app.innerHTML=`<div class="app-shell">${mockTopBar4620()}<main class="container"><div class="mock-top"><div><div class="label">FULL MOCK ${esc(pack.pack_id.toUpperCase())}</div><h1>${esc(pack.title)} · Speaking</h1><p>4 parts · use Speaking AI Examiner for practice evidence</p></div><button class="btn btn-ghost" data-v4620-home>Salir</button></div><div class="v4620-speaking-grid">${parts.map(p=>`<section class="card"><h2>Part ${p.part} · ${esc(p.type||'')}</h2><p>${esc(p.prompt||(p.prompts||[]).join(' '))}</p>${p.photo_asset_required?'<div class="notice">Photo stimulus required for strict Part 2 fidelity; use this prompt for practice until a reviewed image stimulus is attached.</div>':''}<button class="btn btn-primary" data-v4620-practice-speaking="${p.part}">Practicar Part ${p.part} con Speaking AI</button></section>`).join('')}</div><div class="notice">Speaking automático = práctica formativa. Pronunciation, interaction y Global Achievement no equivalen a una nota oficial de Cambridge.</div></main></div>`;document.querySelector('[data-v4620-home]')?.addEventListener('click',()=>location.reload());document.querySelectorAll('[data-v4620-practice-speaking]').forEach(b=>b.onclick=()=>{activeSpeakingPart=Number(b.dataset.v4620PracticeSpeaking);try{state.view='speaking';state.idx=activeSpeakingPart-1;render()}catch(_){location.reload()}})}
async function openWriting(id){try{const p=await loadPack(id);if(p?.audit_v46_28?.production_gate?.allowed===false){window.toast?.('Mock bloqueado: contiene tareas REJECTED_FOR_REVISION');return;}renderWriting(p)}catch(_){window.toast?.('No se pudo abrir Writing')}}
async function openSpeaking(id){try{const p=await loadPack(id);if(p?.audit_v46_28?.production_gate?.allowed===false){window.toast?.('Mock bloqueado: contiene sets REJECTED_FOR_REVISION');return;}renderSpeaking(p)}catch(_){window.toast?.('No se pudo abrir Speaking')}}
function bindBank(){document.querySelectorAll('[data-v4620-writing]').forEach(b=>{if(b.dataset.bound4620)return;b.dataset.bound4620='1';b.onclick=()=>openWriting(b.dataset.v4620Writing)});document.querySelectorAll('[data-v4620-speaking]').forEach(b=>{if(b.dataset.bound4620)return;b.dataset.bound4620='1';b.onclick=()=>openSpeaking(b.dataset.v4620Speaking)})}
const prev=window.render;window.render=function(){prev();requestAnimationFrame(bindBank)};
const style=document.createElement('style');style.textContent=`.v4620-choice{display:block;border:1px solid var(--line,#dbe2ea);border-radius:12px;padding:12px;margin:8px 0}.v4620-speaking-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.v4620-speaking-grid .card{margin:0}.v43-packgrid{grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}`;document.head.appendChild(style);
window.PETQUEST_V4620={version:VERSION,openWriting,openSpeaking,currentSpeakingPrompt:()=>speakingPrompt(activeSpeakingPart),get activePack(){return activePack}};
requestAnimationFrame(bindBank);
})();
