/* PET Quest V46.15 - Speaking Part 3 AI Candidate
   Interactive formative practice. Not an official Cambridge score. */
(function(){
'use strict';
const VERSION='46.15';
const S={active:false,scenario:null,turns:[],userTurns:0,recognizer:null,listening:false};
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scenarios=[
 {id:'free_afternoon',title:'Plan a free afternoon',options:['go to the cinema','have a picnic','play sport','visit a museum'],opening:"I think going to the cinema could be a good idea. What do you think?"},
 {id:'class_trip',title:'Choose a class trip',options:['science museum','zoo','castle','adventure park'],opening:"How about going to the science museum? It could be interesting. What do you think?"},
 {id:'birthday',title:'Plan a birthday activity',options:['bowling','picnic','cinema','games at home'],opening:"Why don't we go bowling for the birthday? Do you think everyone would enjoy that?"}
];
const low=t=>String(t||'').toLowerCase();
function functions(t){const x=low(t);return{
 suggestion:/\b(how about|what about|why don't|we could|we should|let's|maybe we can|perhaps we can|i suggest)\b/.test(x),
 agreement:/\b(i agree|yes[, ]|that's true|good idea|sounds good|i think so|you're right|that works)\b/.test(x),
 disagreement:/\b(i disagree|i don't agree|but|however|not sure|i'm not sure|maybe not|i don't think|too expensive|too difficult)\b/.test(x),
 justification:/\b(because|so that|as |since |the reason|that's why|it would|it could)\b/.test(x),
 final_decision:/\b(let's choose|we agree|we've decided|final decision|so let's|then let's|i think we should choose|we should choose)\b/.test(x)
}}
function speak(text){if(!('speechSynthesis' in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.93;u.pitch=1.02;speechSynthesis.speak(u)}
function aiReply(text){const f=functions(text),n=S.userTurns,sc=S.scenario;let r='';
 if(n===1){if(f.disagreement)r="That's a fair point. How about having a picnic instead? It would be cheaper. What do you think?";else if(f.agreement)r="Great. But the cinema might be expensive. What about a picnic instead?";else r="I see. Another possibility is having a picnic. Would that be better?"}
 else if(n===2){if(f.suggestion)r="That could work. I like that you suggested another option. Which is better for everyone, and why?";else r="We need another idea too. Could you suggest an alternative and explain why?"}
 else if(n===3){r=f.justification?"Good reason. I partly agree, but we should think about the weather and cost. Can we compare the two best options?":"Tell me why you prefer that option. Then let's compare it with one alternative."}
 else if(n===4){r="We're nearly there. Shall we make a final decision together? Tell me what we should choose and why."}
 else {r=f.final_decision?"Great, we have an agreement. I think that decision works well.":"Let's make a final decision now. Which option do we both agree on?"}
 return r}
function addTurn(role,text){S.turns.push({role,text:String(text||'').trim(),at:new Date().toISOString(),functions:role==='student'?functions(text):{}});renderConversation()}
function cumulative(){const us=S.turns.filter(t=>t.role==='student'),cov={suggestion:false,agreement:false,disagreement:false,justification:false,turn_taking:us.length>=3,negotiation:false,final_decision:false};us.forEach(t=>Object.keys(t.functions||{}).forEach(k=>{if(t.functions[k])cov[k]=true}));cov.negotiation=us.length>=3&&cov.suggestion&&(cov.agreement||cov.disagreement)&&cov.justification;const count=Object.values(cov).filter(Boolean).length;const score=Math.round(count/7*100);return{coverage:cov,score,interactive_communication:Math.max(0,Math.min(5,Math.round(score/20))),student_turns:us.length,ai_turns:S.turns.filter(t=>t.role==='ai').length}}
function feedback(m){const c=m.coverage,miss=[];if(!c.suggestion)miss.push('make a suggestion');if(!c.agreement)miss.push('show agreement');if(!c.disagreement)miss.push('disagree politely');if(!c.justification)miss.push('justify an idea');if(!c.turn_taking)miss.push('sustain at least 3 turns');if(!c.negotiation)miss.push('compare and negotiate alternatives');if(!c.final_decision)miss.push('reach a final decision');return miss}
function panel(){return `<section class="card v4615-ai-candidate"><div class="row between"><div><span class="mission-label">🤝 PET Speaking Part 3 · AI Candidate</span><h2>Conversación real por turnos</h2></div><span class="badge">V${VERSION}</span></div><p>Practica sugerir, responder, comparar alternativas, negociar y llegar a un acuerdo con otro candidato simulado.</p><div class="notice"><b>Evaluación automática de práctica:</b> no equivale a una calificación oficial Cambridge.</div><label><span>Escenario</span><select id="v4615Scenario" class="select">${scenarios.map(s=>`<option value="${s.id}">${E(s.title)}</option>`).join('')}</select></label><div class="row"><button class="btn btn-primary" data-v4615-start>▶ Iniciar conversación</button><button class="btn btn-soft" data-v4615-hear>🔊 Repetir último turno IA</button></div><div id="v4615Chat" class="v4615-chat"><p class="small">Inicia para conversar con el candidato IA.</p></div><label><span>Tu turno</span><textarea id="v4615Input" class="textarea" placeholder="Speak or type your response..."></textarea></label><div class="row"><button class="btn btn-soft" data-v4615-mic>🎙️ Dictar</button><button class="btn btn-primary" data-v4615-send>Enviar turno</button><button class="btn btn-soft" data-v4615-finish>Finalizar y evaluar</button></div><div id="v4615Result" aria-live="polite"></div></section>`}
function renderConversation(){const box=document.getElementById('v4615Chat');if(!box)return;box.innerHTML=S.turns.map(t=>`<div class="v4615-turn ${t.role}"><b>${t.role==='ai'?'AI Candidate':'You'}</b><p>${E(t.text)}</p></div>`).join('')||'<p class="small">Sin turnos.</p>';box.scrollTop=box.scrollHeight}
function start(){const id=document.getElementById('v4615Scenario')?.value||scenarios[0].id;S.scenario=scenarios.find(x=>x.id===id)||scenarios[0];S.turns=[];S.userTurns=0;S.active=true;addTurn('ai',S.scenario.opening);speak(S.scenario.opening);document.getElementById('v4615Result').innerHTML=''}
function send(){if(!S.active)start();const ta=document.getElementById('v4615Input'),txt=(ta?.value||'').trim();if(!txt)return window.toast?.('Escribe o dicta tu respuesta.');addTurn('student',txt);S.userTurns++;if(ta)ta.value='';const r=aiReply(txt);addTurn('ai',r);speak(r);const m=cumulative();if(m.coverage.final_decision&&S.userTurns>=4)finish()}
function mic(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return window.toast?.('El reconocimiento de voz no está disponible en este navegador.');if(S.listening)return;const r=new R();S.recognizer=r;r.lang='en-GB';r.interimResults=true;r.continuous=false;S.listening=true;const ta=document.getElementById('v4615Input');r.onresult=e=>{let x='';for(let i=0;i<e.results.length;i++)x+=e.results[i][0].transcript+' ';if(ta)ta.value=x.trim()};r.onend=()=>{S.listening=false};r.onerror=()=>{S.listening=false};try{r.start()}catch(_){S.listening=false}}
async function finish(){if(!S.active||S.userTurns<1)return window.toast?.('Completa al menos un turno antes de evaluar.');const m=cumulative(),missing=feedback(m);const transcript=S.turns.map(t=>`${t.role==='ai'?'AI':'Student'}: ${t.text}`).join('\n');const rubric={suggestion:m.coverage.suggestion?5:2,agreement:m.coverage.agreement?5:2,disagreement:m.coverage.disagreement?5:2,justification:m.coverage.justification?5:2,turn_taking:m.coverage.turn_taking?5:2,negotiation:m.coverage.negotiation?5:2,final_decision:m.coverage.final_decision?5:2,interactive_communication:m.interactive_communication};try{const out=await window.apiRequest('/speaking-interactions',{method:'POST',body:{scenario_id:S.scenario?.id||'part3',scenario_title:S.scenario?.title||'Part 3',turns:S.turns,metrics:m,rubric,score_pct:m.score,source:'v46.15-part3-ai-candidate'}});const r=document.getElementById('v4615Result');if(r)r.innerHTML=`<section class="card"><h3>Part 3 Interaction · ${m.score}%</h3><div class="v4614-rubric">${[['Suggestion',m.coverage.suggestion],['Agreement',m.coverage.agreement],['Disagreement',m.coverage.disagreement],['Justification',m.coverage.justification],['Turn-taking',m.coverage.turn_taking],['Negotiation',m.coverage.negotiation],['Final decision',m.coverage.final_decision]].map(x=>`<div><span>${x[0]}</span><b>${x[1]?'✓':'Pendiente'}</b></div>`).join('')}</div><p><b>Interactive Communication:</b> ${m.interactive_communication}/5</p>${missing.length?`<h4>Para llegar al 100%</h4><ol>${missing.map(x=>`<li>${E(x)}</li>`).join('')}</ol>`:'<p class="feedback good">Has cubierto las 7 funciones de interacción de esta práctica.</p>'}<p class="small">Sesión #${E(out.id)} guardada por usuario. Evaluación automática de práctica.</p></section>`;window.toast?.('Conversación evaluada y guardada')}catch(e){window.toast?.('No se pudo guardar la conversación: '+e.message)}}
function bind(){document.querySelector('[data-v4615-start]')?.addEventListener('click',start);document.querySelector('[data-v4615-send]')?.addEventListener('click',send);document.querySelector('[data-v4615-mic]')?.addEventListener('click',mic);document.querySelector('[data-v4615-finish]')?.addEventListener('click',finish);document.querySelector('[data-v4615-hear]')?.addEventListener('click',()=>{const x=[...S.turns].reverse().find(t=>t.role==='ai');if(x)speak(x.text)});document.getElementById('v4615Input')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}})}
function inject(){if(window.state?.view!=='speaking'||document.querySelector('.v4615-ai-candidate'))return;const main=document.querySelector('main.container');if(!main)return;main.insertAdjacentHTML('beforeend',panel());bind()}
const prev=window.render;window.render=function(){const out=prev.apply(this,arguments);requestAnimationFrame(inject);return out};requestAnimationFrame(inject);window.PETQUEST_V46_15={version:VERSION,state:S,functions,cumulative};
})();
