// PET Quest V5 enhancement layer. Keeps V4 compatible while extending content and evaluation.
const V5_READING=[
{id:'r401',part:1,level:1,focus:'notices',notice:'MUSIC ROOM: Piano lesson moved from 3:30 to 4:00 today.',q:'What has changed?',opts:['The place','The time','The teacher'],a:1,why:'The notice says the lesson moved from 3:30 to 4:00.',tip:'Busca exactamente qué dato cambió.'},
{id:'r402',part:1,level:1,focus:'instructions',notice:'CAFÉ: Please order hot food before 2 p.m. Drinks are available all afternoon.',q:'What can customers do after 2 p.m.?',opts:['Order hot food','Buy drinks','Get free food'],a:1,why:'Hot food stops at 2 p.m., but drinks remain available.',tip:'Distingue la regla general de la excepción.'},
{id:'r403',part:2,level:1,focus:'matching',notice:'Omar wants a cheap indoor activity after school. He enjoys making things with his hands.',q:'Which activity is best?',opts:['Free craft club at 4 p.m.','Weekend football training','Evening cinema tickets'],a:0,why:'It is after school, indoors, free and creative.',tip:'Comprueba cada condición del perfil.'},
{id:'r404',part:2,level:2,focus:'matching',notice:'Sara wants to practise English with other teenagers online twice a week and cannot study on Fridays.',q:'Which course is best?',opts:['Tuesday and Thursday online conversation club','Friday grammar workshop','Saturday face-to-face reading class'],a:0,why:'It is online, twice weekly, with conversation and avoids Friday.',tip:'Elimina opciones que fallen aunque sea en una condición clave.'},
{id:'r405',part:3,level:2,focus:'detail',notice:'Our school eco-team began by collecting paper, but students soon asked for bins for plastic too. This term, the team also started a monthly repair café where families fix broken objects instead of throwing them away.',q:'What new activity happens monthly?',opts:['Paper collection','Plastic recycling','Repairing broken objects'],a:2,why:'The text says the repair café happens monthly.',tip:'Relaciona la frecuencia con la actividad.'},
{id:'r406',part:3,level:3,focus:'purpose',notice:'When I joined the drama club, I expected to learn acting. I did, but I also learned to listen carefully to others and speak more confidently in class. That surprised me most.',q:'Why does the writer mention class?',opts:['To explain an unexpected benefit','To complain about school','To compare two teachers'],a:0,why:'Confidence from drama helped in class, which the writer did not expect.',tip:'Pregunta qué función cumple ese detalle dentro del texto.'},
{id:'r407',part:3,level:3,focus:'attitude',notice:'The campsite looked basic when we arrived, and there was no Wi-Fi. By the second day, nobody cared because we were kayaking, cooking outdoors and laughing together.',q:'How did the group feel later?',opts:['They enjoyed being disconnected','They wanted to leave early','They were bored'],a:0,why:'Activities and time together made the lack of Wi-Fi unimportant.',tip:'Busca cambios entre la primera impresión y la final.'},
{id:'r408',part:4,level:2,focus:'cohesion',notice:'Nina had never travelled alone before. ____. Still, she checked the platform number twice before boarding.',q:'Which sentence fits best?',opts:['Her parents had explained the journey carefully.','She dislikes all forms of transport.','The station closed last year.'],a:0,why:'Careful preparation explains why she could travel while still feeling cautious.',tip:'La frase debe conectar ambas ideas.'},
{id:'r409',part:4,level:3,focus:'reference',notice:'The team tested three designs for the school poster. The first was colourful but difficult to read. ____. This made the final choice easy.',q:'Which sentence best completes the text?',opts:['The third design was clear and attractive.','Nobody knew where the school was.','The printer needed more paper.'],a:0,why:'A strong third design explains why the final decision became easy.',tip:'“This” debe referirse lógicamente a la idea anterior.'},
{id:'r410',part:4,level:3,focus:'sequence',notice:'We planned to interview the chef at noon. ____. As a result, we used the extra hour to prepare better questions.',q:'Which sentence fits?',opts:['The interview was delayed until one o’clock.','The chef never cooks lunch.','Our questions were already perfect.'],a:0,why:'A delay creates the extra hour mentioned next.',tip:'Busca relaciones de tiempo y consecuencia.'},
{id:'r411',part:5,level:1,focus:'collocations',notice:'Can you ___ me a favour and close the window?',q:'Choose the best word.',opts:['do','make','take'],a:0,why:'The fixed expression is “do someone a favour”.',tip:'Aprende collocations como bloques.'},
{id:'r412',part:5,level:2,focus:'grammar',notice:'If it ___ tomorrow, we will play indoors.',q:'Choose the correct form.',opts:['rains','will rain','rained'],a:0,why:'In the first conditional, use present simple after “if”.',tip:'If + present, will + verb.'},
{id:'r413',part:5,level:3,focus:'vocabulary',notice:'The instructions were so ___ that everyone completed the task correctly.',q:'Choose the best word.',opts:['clear','empty','private'],a:0,why:'Clear instructions help people understand what to do.',tip:'Usa el contexto para comprobar significado y lógica.'},
{id:'r414',part:6,level:1,focus:'articles',notice:'My sister wants to be ___ engineer when she grows up.',q:'Choose the missing word.',opts:['an','a','the'],a:0,why:'“Engineer” begins with a vowel sound, so use “an”.',tip:'Elige a/an por el sonido inicial.'},
{id:'r415',part:6,level:2,focus:'quantifiers',notice:'There aren’t ___ apples left, so let’s buy some.',q:'Choose the missing word.',opts:['many','much','little'],a:0,why:'“Apples” is plural countable, so “many” is correct.',tip:'Many + contables; much + incontables.'},
{id:'r416',part:6,level:3,focus:'relative-clauses',notice:'The girl ___ won the science prize is in my class.',q:'Choose the missing word.',opts:['who','where','which'],a:0,why:'Use “who” for a person in a relative clause.',tip:'Who = persona; which = cosa; where = lugar.'}
];
const V5_LISTENING=[
{id:'l401',part:1,level:1,focus:'time',audio:'The bus leaves at twenty past eight. Please be at the stop ten minutes earlier.',q:'What time does the bus leave?',opts:['8:10','8:20','8:30'],a:1,why:'“Twenty past eight” is 8:20.',tip:'No confundas la hora de llegada con la salida.'},
{id:'l402',part:1,level:1,focus:'places',audio:'We planned to meet outside the cinema, but it is raining, so wait for me inside the café next door.',q:'Where should they meet?',opts:['Outside the cinema','Inside the café','At home'],a:1,why:'The speaker changes the plan to the café.',tip:'Escucha conectores de cambio: but, so, instead.'},
{id:'l403',part:1,level:1,focus:'numbers',audio:'There are fourteen students in my art class and sixteen in the music class.',q:'How many students are in the music class?',opts:['14','16','30'],a:1,why:'The music class has sixteen students.',tip:'Asocia cada número con su sustantivo.'},
{id:'l404',part:1,level:2,focus:'objects',audio:'I forgot my water bottle, but I remembered my lunch box and my blue cap.',q:'What did the speaker forget?',opts:['A bottle','A lunch box','A cap'],a:0,why:'The speaker directly says the water bottle was forgotten.',tip:'Diferencia “forgot” de “remembered”.'},
{id:'l405',part:2,level:2,focus:'reason',audio:'We chose the earlier train because the later one arrives after the museum closes.',q:'Why are they taking the earlier train?',opts:['It is cheaper','It arrives before closing time','It has more seats'],a:1,why:'They need to arrive before the museum closes.',tip:'Escucha la causa después de “because”.'},
{id:'l406',part:2,level:2,focus:'opinion',audio:'The book started slowly, but after chapter three I could not stop reading.',q:'What is the speaker’s opinion?',opts:['It improved','It stayed boring','It was too short'],a:0,why:'The speaker changed from a slow start to strong interest.',tip:'“But” suele introducir la opinión importante.'},
{id:'l407',part:2,level:3,focus:'attitude',audio:'I was nervous about performing, yet once the music began I forgot about the audience and really enjoyed it.',q:'How did the speaker feel during the performance?',opts:['More relaxed','More frightened','Disappointed'],a:0,why:'The speaker forgot the audience and enjoyed performing.',tip:'Distingue cómo se sentía antes y durante.'},
{id:'l408',part:2,level:3,focus:'purpose',audio:'I keep a small notebook beside my bed so I can write down new story ideas before I forget them.',q:'Why is the notebook beside the bed?',opts:['To practise handwriting','To record ideas quickly','To read before sleeping'],a:1,why:'The speaker wants to record ideas before forgetting them.',tip:'“So I can...” suele expresar propósito.'},
{id:'l409',part:3,level:2,focus:'detail',audio:'For tomorrow’s trip, wear comfortable shoes and bring a light jacket. Lunch is included, so you do not need to bring food.',q:'What should students bring?',opts:['Lunch','A jacket','Sports equipment'],a:1,why:'A light jacket is requested; lunch is provided.',tip:'Escucha qué deben traer y qué ya está incluido.'},
{id:'l410',part:3,level:2,focus:'dates',audio:'The photography competition closes on the twenty-second of May, and winners will be announced on the thirtieth.',q:'When is the closing date?',opts:['22 May','30 May','2 May'],a:0,why:'The deadline is the twenty-second.',tip:'Separa fecha límite de fecha de resultados.'},
{id:'l411',part:3,level:3,focus:'detail',audio:'The workshop begins in the main hall, then groups move upstairs to rooms four and five for practical activities.',q:'Where does the workshop begin?',opts:['Room 4','Room 5','The main hall'],a:2,why:'It starts in the main hall before groups move upstairs.',tip:'Atiende al orden de los lugares.'},
{id:'l412',part:3,level:3,focus:'numbers',audio:'Tickets cost eight pounds online or ten pounds at the door. Children under five enter free.',q:'How much is a ticket bought online?',opts:['£5','£8','£10'],a:1,why:'Online tickets cost eight pounds.',tip:'Relaciona precio con método de compra.'},
{id:'l413',part:4,level:3,focus:'inference',audio:'I checked the weather three times and packed sunscreen, but I left my umbrella at home. Of course, it rained all afternoon.',q:'How does the speaker probably feel?',opts:['Annoyed with themself','Proud','Confused about the forecast'],a:0,why:'They prepared carefully but forgot the item they needed.',tip:'La emoción se deduce de la situación completa.'},
{id:'l414',part:4,level:3,focus:'opinion',audio:'The new app has more features, but I still prefer the old version because I can find everything faster.',q:'Why does the speaker prefer the old app?',opts:['It has more features','It is easier to navigate','It is newer'],a:1,why:'The speaker can find things faster in the old version.',tip:'La preferencia aparece después de “because”.'},
{id:'l415',part:4,level:3,focus:'agreement',audio:'Ava thinks the class should visit the science museum. I agree it would be useful, although the journey is quite long.',q:'What does the speaker agree about?',opts:['The trip would be useful','The journey is short','The museum is nearby'],a:0,why:'The speaker agrees the visit would be useful.',tip:'Separa acuerdo principal de una desventaja adicional.'},
{id:'l416',part:4,level:3,focus:'change',audio:'I used to study late at night, but now I start after dinner and finish earlier. I feel much less tired at school.',q:'What changed?',opts:['The speaker studies earlier','The speaker stopped studying','School starts later'],a:0,why:'The speaker now starts and finishes study earlier.',tip:'“Used to... but now...” señala un cambio claro.'}
];
BANK.reading.push(...V5_READING); BANK.listening.push(...V5_LISTENING);

function avgWriting(){return data.writing.length?Math.round(data.writing.reduce((s,x)=>s+(x.score||0),0)/data.writing.length*5):0}
function avgSpeaking(){return data.speaking.length?Math.round(data.speaking.reduce((s,x)=>s+(x.score||0),0)/data.speaking.length*5):0}
readiness=function(){const r=pct('reading'),l=pct('listening'),w=avgWriting(),s=avgSpeaking(),practice=Math.min(100,data.history.length*2);return Math.round(r*.25+l*.25+w*.20+s*.20+practice*.10)};

evalWriting=function(text){
 const words=text.trim()?text.trim().split(/\s+/):[],n=words.length,lower=text.toLowerCase();
 const sent=(text.match(/[.!?]+/g)||[]).length, paras=text.split(/\n\s*\n/).filter(x=>x.trim()).length;
 const connectors=['because','but','so','when','although','however','first','then','finally','also','while','after','before'].filter(x=>new RegExp('\\b'+x+'\\b','i').test(text)).length;
 const taskWords=state.idx===0?['thank','friend','weekend','hope','write','see']:['think','feel','because','example','story','article'];
 const relevance=taskWords.filter(x=>lower.includes(x)).length;
 const clean=words.map(w=>w.toLowerCase().replace(/[^a-z']/g,'')).filter(Boolean), uniq=new Set(clean).size;
 const diversity=uniq/Math.max(1,clean.length), repeats=clean.length-uniq;
 const content=Math.max(1,Math.min(5,Math.round((n>=80?2:1)+(relevance>=2?2:1)+(sent>=4?1:0))));
 const communication=Math.max(1,Math.min(5,Math.round((n>=80&&n<=130?3:n>=60?2:1)+(relevance>=2?1:0)+(sent>=3?1:0))));
 const organisation=Math.max(1,Math.min(5,1+Math.min(3,connectors)+(paras>=2?1:0)));
 const language=Math.max(1,Math.min(5,Math.round(1+diversity*4+(n>=80&&repeats<n*.55?1:0))));
 const total=content+communication+organisation+language;
 const tips=[]; if(n<80)tips.push('Amplía el texto hacia unas 100 palabras.'); if(n>130)tips.push('Hazlo más directo y elimina repeticiones.'); if(connectors<3)tips.push('Usa al menos 3 conectores distintos.'); if(sent<4)tips.push('Desarrolla las ideas en más oraciones completas.'); if(diversity<.55)tips.push('Varía más el vocabulario.'); if(!tips.length)tips.push('Buen equilibrio: revisa tiempos verbales, ortografía y precisión antes de finalizar.');
 data.writing.push({date:new Date().toISOString(),part:state.idx+1,words:n,score:total,text,rubric:{content,communication,organisation,language},tips});data.profile.xp+=Math.max(5,total);save();
 document.getElementById('writingFeedback').innerHTML=`<div class="feedback ${total>=14?'ok':'bad'}"><b>Coach de Writing: ${total}/20</b><div class="rubric"><div class="stat"><b>${content}/5</b><span>Contenido</span></div><div class="stat"><b>${communication}/5</b><span>Comunicación</span></div><div class="stat"><b>${organisation}/5</b><span>Organización</span></div><div class="stat"><b>${language}/5</b><span>Lenguaje</span></div></div><ul class="coach-tips">${tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="small">Evaluación automática orientativa de práctica; no sustituye la calificación oficial de Cambridge.</div></div>`;
};

speaking=function(){const tasks=[['Entrevista','Tell me about your school day. What subject do you enjoy most and why?',30],['Foto','Imagine a photo of two friends preparing food together in a kitchen. Describe what you can see and what may be happening.',60],['Discusión','A class wants to celebrate the end of term. Suggest activities, compare them and choose the best one.',90],['Conversación','Do you prefer spending free time with friends or family? Why? What makes a day memorable?',60]];const t=tasks[state.idx%4];el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Speaking Studio',`Parte ${state.idx+1} de 4 · práctica individual`)}<div class="exercise-layout"><section class="card question-card"><span class="badge">${t[0]}</span><div class="prompt">${esc(t[1])}</div><div class="notice"><b>Coach:</b> responde, da una razón y amplía con un ejemplo o detalle.</div><div class="row"><button class="btn btn-primary" data-record>🎙️ Grabar</button><button class="btn btn-soft" data-speech-text>🗣 Dictar respuesta</button><button class="btn btn-soft" data-countdown="${t[2]}">⏱ ${t[2]} s</button></div><div id="recordStatus" class="feedback neutral">Puedes grabarte y/o dictar tu respuesta para recibir feedback.</div><label><span>Transcripción / respuesta</span><textarea id="speakingText" class="textarea" placeholder="Speak with the microphone button or type what you said..."></textarea></label><button class="btn btn-primary" data-eval-speaking>Evaluar Speaking</button><div id="speakingFeedback"></div><div class="row action-row"><button class="btn btn-ghost" data-speaking-prev ${state.idx===0?'disabled':''}>← Anterior</button><button class="btn btn-primary" data-speaking-next>${state.idx===3?'Finalizar':'Siguiente →'}</button></div></section><aside class="card side"><h3>Checklist</h3><p>✓ Respuesta completa</p><p>✓ Razón</p><p>✓ Ejemplo/detalle</p><p>✓ Vocabulario variado</p><p>✓ Conectores naturales</p></aside></div></main></div>`)};

function evaluateSpeakingText(){const ta=document.getElementById('speakingText'),out=document.getElementById('speakingFeedback');const text=(ta?.value||'').trim();if(!text){out.innerHTML='<div class="feedback bad">Necesito una transcripción para evaluar la respuesta.</div>';return}const words=text.split(/\s+/),n=words.length,low=text.toLowerCase();const reasons=(low.match(/\b(because|so|as)\b/g)||[]).length,examples=(low.match(/\b(for example|for instance|such as)\b/g)||[]).length,linkers=(low.match(/\b(and|but|because|so|also|then|however|although)\b/g)||[]).length,uniq=new Set(words.map(x=>x.toLowerCase().replace(/[^a-z']/g,''))).size;const grammar=Math.min(5,Math.max(1,Math.round(2+(n>=25?1:0)+(linkers>=2?1:0)+(reasons?1:0))));const discourse=Math.min(5,Math.max(1,1+(n>=20?1:0)+(n>=40?1:0)+(linkers>=2?1:0)+(examples?1:0)));const vocabulary=Math.min(5,Math.max(1,Math.round(1+(uniq/Math.max(n,1))*4+(n>=30?1:0))));const interactive=Math.min(5,Math.max(1,2+(reasons?1:0)+(examples?1:0)+(n>=35?1:0)));const total=grammar+discourse+vocabulary+interactive;const tips=[];if(n<25)tips.push('Amplía la respuesta con más detalles.');if(!reasons)tips.push('Añade una razón usando because/so.');if(!examples)tips.push('Incluye un ejemplo concreto.');if(linkers<2)tips.push('Conecta ideas con and, but, because, so, also.');if(!tips.length)tips.push('Buena estructura. Ahora concéntrate en pronunciación, ritmo y naturalidad al decirla.');data.speaking.push({date:new Date().toISOString(),part:state.idx+1,score:total,words:n,text,rubric:{grammar,discourse,vocabulary,interactive},tips});data.profile.xp+=Math.max(5,total);save();out.innerHTML=`<div class="feedback ${total>=14?'ok':'bad'}"><b>Coach de Speaking: ${total}/20</b><div class="rubric"><div class="stat"><b>${grammar}/5</b><span>Gramática</span></div><div class="stat"><b>${discourse}/5</b><span>Discurso</span></div><div class="stat"><b>${vocabulary}/5</b><span>Vocabulario</span></div><div class="stat"><b>${interactive}/5</b><span>Desarrollo</span></div></div><ul class="coach-tips">${tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="small">La transcripción no mide pronunciación con precisión. Es feedback orientativo de práctica.</div></div>`}
function speechToText(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('El reconocimiento de voz no está disponible en este navegador');const r=new R();r.lang='en-GB';r.interimResults=true;const ta=document.getElementById('speakingText');r.onresult=e=>{ta.value=Array.from(e.results).map(x=>x[0].transcript).join(' ')};r.onerror=()=>toast('No se pudo reconocer la voz');r.start()}

const oldBind=bind; bind=function(){oldBind();const es=document.querySelector('[data-eval-speaking]');if(es)es.onclick=evaluateSpeakingText;const st=document.querySelector('[data-speech-text]');if(st)st.onclick=speechToText;const ex=document.querySelector('[data-export-report]');if(ex)ex.onclick=async()=>{try{const r=await fetch('/api/report.csv',{headers:{Authorization:'Bearer '+API.token}});if(!r.ok)throw new Error();const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='petquest_report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast('No se pudo exportar el reporte')}}};

const oldReports=reports; reports=function(){const rows=API.report||[];el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Reportes académicos','Seguimiento conectado al backend V5.')}<div class="dashboard-grid"><div class="card"><div class="label">Estudiantes</div><div class="big-number">${rows.length}</div></div><div class="card"><div class="label">Readiness promedio</div><div class="big-number">${rows.length?Math.round(rows.reduce((s,x)=>s+(x.readiness||0),0)/rows.length):0}%</div></div><div class="card"><div class="label">Precisión promedio</div><div class="big-number">${rows.length?Math.round(rows.reduce((s,x)=>s+(x.accuracy||0),0)/rows.length):0}%</div></div></div><div class="card"><div class="row between"><div><h2>Rendimiento del colegio</h2><p>Intentos, precisión, readiness y producción.</p></div><div class="row"><button class="btn btn-soft" data-export-report>Exportar CSV</button><button class="btn btn-primary" data-load-report>Actualizar</button></div></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Estudiante</th><th>Intentos</th><th>Precisión</th><th>Readiness</th><th>Writing</th><th>Speaking</th><th>Última sync</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.attempts}</td><td>${r.accuracy}%</td><td>${r.readiness||0}%</td><td>${r.writing||0}%</td><td>${r.speaking||0}%</td><td>${r.updated_at?new Date(r.updated_at).toLocaleString():'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Pulsa “Actualizar” para cargar estudiantes sincronizados.</div>'}</div></main></div>`)};

function unifiedProgressV5(){try{return window.PETQUEST_V468?.state?.summary||null}catch(_){return null}}
const oldDashboard=dashboard; dashboard=function(){const u=unifiedProgressV5(),pending=!!API.token&&!u,a=u?.activity||{},sk=u?.skills||{},r=u?Math.round(Number(u.preparation?.score||0)):pending?null:readiness(),acc=u?Math.round(Number(a.accuracy||0)):pending?null:accuracy(),attempts=u?Number(a.attempts||0):pending?null:data.history.length,w=u?Math.round(Number(sk.writing||0)):pending?null:avgWriting(),s=u?Math.round(Number(sk.speaking||0)):pending?null:avgSpeaking(),cards=[['reading','Reading',u?Math.round(Number(sk.reading||0)):pending?null:pct('reading')],['writing','Writing',w],['listening','Listening',u?Math.round(Number(sk.listening||0)):pending?null:pct('listening')],['speaking','Speaking',s]].map(([id,n,v])=>`<div class="card"><div class="label">${n}</div><div class="big-number" data-progress-skill="${id}">${v===null?'—':v+'%'}</div><div class="progress"><span data-progress-bar="${id}" style="width:${v===null?0:v}%"></span></div></div>`).join('');el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Mi progreso','Progreso unificado desde la evidencia guardada en PostgreSQL.')}<div class="dashboard-grid"><div class="card highlight"><div class="label">PET READINESS</div><div class="big-number" data-progress-readiness>${r===null?'—':r+'%'}</div><p>Prioridad: <b>${pending?'Sincronizando evidencia…':esc(weakFocus())}</b></p></div><div class="card"><div class="label">Precisión</div><div class="big-number" data-progress-accuracy>${acc===null?'—':acc+'%'}</div><p><span data-progress-attempts>${attempts===null?'—':attempts}</span> respuestas</p></div><div class="card"><div class="label">Banco disponible</div><div class="big-number">${BANK.reading.length+BANK.listening.length}</div><p>32 Reading + 25 Listening</p></div></div><div class="section-title"><div><h2>Habilidades</h2></div></div><div class="dashboard-grid four">${cards}</div><div class="card recommendation"><h2>Coach adaptativo</h2><p>${pending?'Estamos consultando tu progreso guardado.':esc(studyRecommendation())}</p><div class="row"><button class="btn btn-primary" data-view="plan">Ver plan</button><button class="btn btn-soft" data-view="answers">Reparar errores</button></div></div></main></div>`)};

mock=function(){const formats=Object.entries(FORMAT).map(([k,f])=>`<button class="card mock-card" data-start-mock="${k}"><div class="skill-icon">${{reading:'📖',writing:'✍️',listening:'🎧',speaking:'🎙️'}[k]}</div><h3>${SKILLS[k]}</h3><p>${f.parts} partes · ${f.questions} ${k==='speaking'?'tareas':'preguntas'} · ${f.minutes} min</p><span class="badge">25% del examen</span></button>`).join('');el(`<div class="app-shell">${topBar()}<main class="container">${screenHead('Mock Exam','Simulación cronometrada por sección.')}<div class="notice"><b>V5:</b> Reading contiene 32 preguntas y Listening 25 preguntas de práctica. Writing y Speaking utilizan sus talleres con rúbrica orientativa. Este contenido es original de PET Quest y no reproduce papers oficiales.</div><div class="mock-grid">${formats}</div></main></div>`)};

// Force the enhanced UI after the V4 bootstrap rendered once.
render();
